### ISSUE TITLE
Unsupported locale en-IN

### ISSUE THREAD

**Issue by JafarAbbas33** [crunchy-labs/crunchy-cli#102]
I got this error:
`a unexpected error occurred: url https://www.crunchyroll.com/watch/GZ7UV84W8/a-diabolical-scheme could not be parsed: validation_error - Unsupported locale en-IN`

**Comment by ByteDream** [comment]
What was the command you were using?
Which version did you use?

**Comment by JafarAbbas33** [comment]
The command was:
`./crunchy --etp-rt xx-xxx-xxxxx download -a en-IN -o "S{season_number}E{episode_number} ({title}).ts" https://www.crunchyroll.com/watch/GZ7UV84W8/a-diabolical-scheme`
and
`./crunchy --etp-rt xxx-xxx-xxx download -o "S{season_number}E{episode_number} ({title}).ts" https://www.crunchyroll.com/watch/GZ7UV84W8/a-diabolical-scheme`
The version is: `crunchy-cli 3.0.0-dev.7 (13f54c0 2023-01-08)`
OS: `Linux xxx 5.15.0-57-generic #63~20.04.1-Ubuntu SMP xxx x86_64 x86_64 x86_64 GNU/Linux`
Sorry for not mentioning.

**Comment by ByteDream** [comment]
Try again with
```
./crunchy --lang en-US --etp-rt xxx-xxx-xxx download -o "S{season_number}E{episode_number} ({title}).ts" https://www.crunchyroll.com/watch/GZ7UV84W8/a-diabolical-scheme
```
Crunchyroll has some problems with specific request locales (crunchy-cli tries to use your system locale as request language to show all results like titles in your language; `--lang` overwrites this language)
