### ISSUE TITLE
Found argument '--directory' which wasn't expected

### ISSUE THREAD

**Issue by JafarAbbas33** [crunchy-labs/crunchy-cli#105]
Command 1: `crunchy --lang en-US --etp-rt xx-xxx-xxxxx --directory "/xxx/{series_name} [S{season_number}] [{resolution}]" download --subtitle en-US --audio ja-JP --output "/xxx/{series_name} [S{season_number}] [{resolution}]/S{season_number}E{episode_number} - {series_name}.ts" https://www.crunchyroll.com/series/GVDHX8QZX/the-tale-of-outcasts[S1E2]`

Error 1: `error: Found argument '--directory' which wasn't expected, or isn't valid in this context
Usage: crunchy --lang <LANG> <--credentials <CREDENTIALS>|--etp-rt <ETP_RT>|--anonymous> <COMMAND>
For more information try '--help'`

I also tried placing it after download command

Command 2: `crunchy --lang en-US --etp-rt xx-xxx-xxxxx download --subtitle en-US --audio ja-JP --directory "/xxx/{series_name} [S{season_number}] [{resolution}]" --output "/xxx/{series_name} [S{season_number}] [{resolution}]/S{season_number}E{episode_number} - {series_name}.ts" https://www.crunchyroll.com/series/GVDHX8QZX/the-tale-of-outcasts[S1E2]`

Error 2: `error: Found argument '--directory' which wasn't expected, or isn't valid in this context
  If you tried to supply '--directory' as a value rather than a flag, use '-- --directory'
Usage: crunchy download <--audio <AUDIO>|--subtitle <SUBTITLE>|--output <OUTPUT>|--resolution <RESOLUTION>|--ffmpeg-preset <FFMPEG_PRESET>|--yes|URLS>
For more information try '--help'`

`OS:` LINUX Lubuntu (Ubuntu) 20.04
`Version:` crunchy-cli 3.0.0-dev.7 (13f54c0 2023-01-08)

I just want to download my anime according to seasons of anime. Btw I also saw the `--help` flag doesn't give a lot of important info. Very sorry if I missed something. Thanks.

PS - Love your amazing work!!

**Comment by ByteDream** [comment]
`-d`/`--directory` does not exist in v3 anymore. You can just use `-o`/`--output` to specify the output directory. Eg. `-o test_directory/{title}.ts` place all files in the `test_directory` directory.

**Comment by JafarAbbas33** [comment]
@ByteDream Oh okay but can't we also replace the directory's name?
`--output "/xxx/{series_name} [S{padded_season_number}] [{resolution}]/S{padded_season_number}E{padded_episode_number} - {series_name}.ts"`
created this file:
`/xxx/{series_name} [S{padded_season_number}] [{resolution}]/S01E01 - The tale of outcasts.ts`
Directory name was not changed. Only file name was changed. I was expecting something like:
`/xxx/The tale of outcasts [S01] [1920x1080]/S01E01 - The tale of outcasts.ts`
One more question - Is "--goroutines" depreciated? If not what is it's use? And can we create a discord or telegram group for small questions like these or something?

**Comment by ByteDream** [comment]
The path format issue is already fixed an will be available in the next release (#101).
The `-g`/`--goroutines` flag were also removed in v3, yes. The usage of it was mainly to control the number of "threads" (goroutines) which were downloading a video. The initial idea was to control the cpu usage (more goroutines = more cpu usage), but now the number of threads makes barely any difference which is why it got removed.
We already have a [discord](https://discord.gg/PXGPGpQxgk) (link to it is right on top of the README).

**Comment by JafarAbbas33** [comment]
@ByteDream Oh the discord icon was so small that I missed it. Thanks a lot for the explanation!
P.S. Love your work!
