### ISSUE TITLE
Ubuntu 22.04 Build Failure

### ISSUE THREAD

**Issue by zack-ani** [crunchy-labs/crunchy-cli#107]
**Describe the bug**
Won't build properly. 

**To Reproduce**
Steps / command to reproduce the behavior:
```
$  cargo build --release
```

**Expected behavior**
Build the project

**Screenshots**
![image](https://user-images.githubusercontent.com/39221871/211747327-f4c2abcf-f8f7-499f-983a-1af5bece2ebb.png)

**Client (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Comment by ByteDream** [comment]
The erroneous `let ... else` statement got recently stable in rust version `1.65`. You may update your rust version to build this successfully.
