### ISSUE TITLE
Use more performant AV1 encoder

### ISSUE THREAD

**Issue by bavellone** [crunchy-labs/crunchy-cli#108]
**Describe the bug**
Current av1 encoder (libaom-av1) takes forever to encode due to minimal CPU utilization, especially noticeable on high core CPUs (e.g. ~10% utilization on my Ryzen 5950X).

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy --ffmpeg-preset=av1 ...
```

**Expected behavior**
ffmpeg has other av1 encoders available to use with much better performance and CPU utilization.

Replace "libaom-av1" with "libsvtav1" in the ffmpeg preset options in `utils.rs`

**Client (please complete the following information):**
 - OS: Arch Linux
 - Version: v3.0.0-dev-6

**Additional context**
[FFMPEG SVT-AV1 docs](https://trac.ffmpeg.org/wiki/Encode/AV1#SVT-AV1)

ffmpeg added support for svt-av1 in version 4.4: https://github.com/FFmpeg/FFmpeg/blob/master/Changelog

I'm trying out the following changes with much greater CPU utilization and encoding speed, good results so far:

`utils.rs L300:`
```
FFmpegPreset::Av1 => {
    output.extend(["-c:v", "libsvtav1", "-crf", "22", "-preset", "6", "-g", "120"]);
}
```

Somewhat related side note - it'd be great to be able to have more control over the ffmpeg encoding options from the CLI instead of baking them into the source and compiling as I'm currently doing.

**Comment by ByteDream** [comment]
Thanks for mentioning that! I have not many experience with AV1 encoding and thought the used encoder was the only one available.
Adding custom ffmpeg options is rather "unhandy". Providing more options via a flag would eventually require quotes escaping and other ugly stuff. But I think providing them via an environment variable would be ok.

**Comment by JafarAbbas33** [comment]
`--ffmpeg-quality` could be a good option but I am one of those who prefer quality even if one episode is over 2gb size. I know it might sound dumb but I don't want to compromise in quality at any cost so it would be great if that is kept in mind going further into development.
PS - Love this great tool!!
