### ISSUE TITLE
Feature request: Skip existing files instead of overwriting

### ISSUE THREAD

**Issue by bavellone** [crunchy-labs/crunchy-cli#109]
**Client (please complete the following information):**
 - OS: Arch Linux
 - Version: v3.0.0-dev-6

**Current Behavior**
Currently, the `archive` command (and I assume `download` as well) will overwrite any destination file if it exists, e.g. if running the same command twice.

This behavior is problematic when using the series URL (e.g. https://beta.crunchyroll.com/series/GEXH3WKK0/vinland-saga) of an ongoing series to download episodes each week a new episode comes out - it will re-download, re-encode, and overwrite every prior episode.

**Desired behavior**
It would be great if there was an additional CLI argument to skip files that already exist, respecting the `-o` parameter to determine the formatted file name. Perhaps `--skip-existing` or `--ignore-existing` (ala [rsync](https://linux.die.net/man/1/rsync#:~:text=files%20on%20receiver-,%2D%2Dignore%2Dexisting,-skip%20updating%20files))?

This would mean, for example, the first time you ran the command `cruncy archive --ignore-existing https://beta.crunchyroll.com/series/GEXH3WKK0/vinland-saga`, all episodes of all seasons of the series would be downloaded. When running the same command again, no additional episodes would be downloaded (assuming a new episode wasn't released between running the two commands).

**Additional context**
I use a script to save which series I'm currently watching and download their latest episodes every week. Before I run the script, I have to manually update the series URL (e.g. from `https://beta.crunchyroll.com/series/GEXH3WKK0/vinland-saga[S2E1]` to `https://beta.crunchyroll.com/series/GEXH3WKK0/vinland-saga[S2E2]`) in order to prevent `crunchy-cli` from unnecessarily re-downloading and encoding the previous episodes. I would much rather just specify the bare series URL (e.g. `https://beta.crunchyroll.com/series/GEXH3WKK0/vinland-saga`) and pass a CLI argument (e.g. `--ignore-existing`) instead, and let it skip episodes that have already been downloaded.

Here's what my script currently looks like for more context:
```js
#!/usr/bin/env node
import { spawnSync } from 'child_process'
import { mkdirSync } from 'fs'

[
    {
        dir: `/data/plex/Vinland Saga/Season 02`,
        url: `https://beta.crunchyroll.com/series/GEXH3WKK0/vinland-saga[S2E1]`,
        dub: false
    },
].map((series) => {
    mkdirSync(series.dir, {
        recursive: true,
    })
    spawnSync(
        `crunchy`,
        [
            `archive`,
            ...(series.dub ? [`--locale`, `en-US`] : [`--locale`, `ja-JP`, `--subtitle`, `en-US`]),
            `-o`,
            `S{padded_season_number}E{episode_number}_{title}.mkv`,
            `--ffmpeg-preset`,
            `av1`,
            series.url,
        ],
        {
            cwd: series.dir,
            stdio: 'inherit',
            shell: true
        }
    )
})
```

Note - now that #101 is fixed in 3.0.0-dev.8, I can simplify this script a bit and go back to using the `-o` option to auto-create the directory with the correct path.

**Comment by BlastBolt5** [comment]
When I use the archive command it creates a new file instead of overwriting the existing one it just adds a (1).
I had suggested something similar in #67 to do an archive file like yt-dl has, this was functionality I was basically wanting

**Comment by BlastBolt5** [comment]
> That said, the end result is effectively the same and having a flag to ignore/skip an episode instead of duplicating would be fantastic.
 100% agreed i was just like huh i wonder why yours does it that way and mine this way

**Comment by ByteDream** [comment]
> 100% agreed i was just like huh i wonder why yours does it that way and mine this way

I was too focused on the file idea as you suggested in your PR. I haven't thought about a simple flag.

**Comment by BlastBolt5** [comment]
yeah it was just how yt-dlp did the not redownloading episodes thing, i didn't even think about it either
