### ISSUE TITLE
Subtitle on Archive is out of sync

### ISSUE THREAD

**Issue by Serverfrog** [crunchy-labs/crunchy-cli#119]
**Describe the bug**
Subtitles inside the MKV are out of sync. I dont know if its because i was searching inside the video or if they are out of sync completely

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive -s de-DE -s en-US -o "S{season_number}E{relative_episode_number} {title}.mkv" --skip-existing https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece
```

**Expected behavior**
Downloaded Subtitle and Crunchyroll Player Subtitle should be shown on the exact same point

**Screenshots**
would not help much i think ;)

**Client (please complete the following information):**
 - OS: Linux
 - Version crunchy-cli 3.0.0-dev.8 (32691e6 2023-01-19)

**Additional context**
used the latest version because of the relative episode number option. For a Anime that is so long it is really helpful ;) also for the skip existing one to resume the download

**Comment by Serverfrog** [comment]
Is more information needed or can somebody confirm this?

**Comment by LetMeByte** [comment]
Can't confirm, can you provide a specific season, episode and subtibtle language?

**Comment by Serverfrog** [comment]
Season 1 Episode 1 subtitle is German.
I noticed that the downloaded Video starts some seconds later as in Crunchyroll. Due to that fact the timings in the subtitles are off.

ffmpeg
```
ffmpeg version 4.3.5-0+deb11u1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
```

**Comment by ByteDream** [comment]
Does this still occur in [v3.0.0-dev.10](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.10)?

**Comment by Serverfrog** [comment]
@ByteDream 
I get with the latest checkout, dev10 and dev9 the following error:

> a unexpected error occurred: (content.get_video_streams_v2.cms_service_error) -  (https://www.crunchyroll.com/content/v2/cms/videos/GKKFNXN72/streams?locale=en-US)

CLI I Used
`crunchy archive -s de-DE -s en-US -o "S{season_number}E{relative_episode_number} {title}.mkv" --skip-existing https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece`

I already removed the ETP Token and re added it via `crunchy login`

**Comment by ByteDream** [comment]
Does this appear before any download starts?
My guess is that this is some kind of new rate limiting introduced with the new endpoints but if my guess is right #189 should've fixed it.
From my experience this error resolves itself after half an hour. Does it still appear (if it does please let me know and try later tomorrow again as I can't reproduce it AMT)?

**Comment by Serverfrog** [comment]
After some time, new pull and waiting i could retry it.
It seems something was changed, so it seems to work now. I just tested the First Episode. I did not Test all 13 Seasons i already downloaded, but i will start to archive it again and will look into some of them.
Do you know which PR could be the culprit why it is fixed now? ;) (the desync issue, the other one is then also tested on my side)

**Comment by Serverfrog** [comment]
But i could already seen that #189 did not fixed the rate limiting. I downloaded just the first episode and now i can't go further. Not even on the Crunchyroll Site it allows me to view anything so an IP Based Rate Limiting is in place then

**Comment by ByteDream** [comment]
> I just waited, now its downloading some episodes but will get the same rate limiting after some time (for me it was 41 episodes but i think that it is some kind of time constraint)

That'

**Comment by ByteDream** [comment]
> I just waited, now its downloading some episodes but will get the same rate limiting after some time (for me it was 41 episodes but i think that it is some kind of time constraint).

Good to hear. But that the limiting still hits is a bit concerning :/

>  also noticed in the code that both, h264 and h265 with nvidia HW uses the same ffmpeg decoder it seems (h264_cuvid).

The decoder is only responsible for decoding the video which Crunchyroll provides, which is always h264 encoded.

**Comment by Serverfrog** [comment]
> Good to hear. But that the limiting still hits is a bit concerning :/

yhea, kinda is. After it once hits, it will still hit everywhere on the same network. We need some further research what exactly triggers it and how to avoid it. Maybe even Limit the amount of downloads in a certain time

> The decoder is only responsible for decoding the video which Crunchyroll provides, which is always h264 encoded.

Ahh ok. Then i maybe need to build ffmpeg myself in some time. But thats very very low prio for me

**Comment by Serverfrog** [comment]
Seemed to be fixed. Dont have any problems with any series i currently have downloaded
