### ISSUE TITLE
Archive error

### ISSUE THREAD

**Issue by TheBinaryLoop** [crunchy-labs/crunchy-cli#128]
**Describe the bug**
:: a unexpected error occurred: url archive could not be parsed: Invalid url

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive archive -l ja-JP -l de-DE  https://www.crunchyroll.com/series/G8DHV7WJP/skeleton-knight-in-another-world
```

**Expected behavior**
Archive to be created.

**Client (please complete the following information):**
 - OS: LINUX
 - Version: 3.0.0-dev.8

**Comment by ByteDream** [comment]
You have to call archive once.
```diff
- $ crunchy archive archive -l ja-JP -l de-DE  https://www.crunchyroll.com/series/G8DHV7WJP/skeleton-knight-in-another-world
+ $ crunchy archive -l ja-JP -l de-DE  https://www.crunchyroll.com/series/G8DHV7WJP/skeleton-knight-in-another-world
```

**Comment by TheBinaryLoop** [comment]
Sorry for bothering you. I think I need to sleep more :smile:
