### ISSUE TITLE
"Command 'crunchy' not found," (HELP)

### ISSUE THREAD

**Issue by Medory13** [crunchy-labs/crunchy-cli#129]
I didn't use terminal tools before... idk but i'm getting this issue when I try to run this command:
$ crunchy --etp-rt "abcd1234-zyxw-9876-98zy-a1b2c3d4e5f6"

error: Command 'crunchy' not found, did you mean:
  command 'crunch' from deb crunch
Try: sudo apt install <deb name>

please help me :(

**Comment by adracea** [comment]
Hello! How did you get the cli and which version are you trying to use?
`https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.8` Should be the latest dev release that works.
Since you seem to be on a linux distribution you can run the following:
```bash
wget https://github.com/crunchy-labs/crunchy-cli/releases/download/v3.0.0-dev.8/crunchy-v3.0.0-dev.8_linux
chmod +x ./crunchy-v3.0.0-dev.8_linux
mkdir ~/crunchy-cli
mv ./crunchy-v3.0.0-dev.8_linux ~/crunchy-cli/crunchy
export PATH=$PATH:~/crunchy-cli/crunchy
```
and I'd recommend adding the `export PATH=$PATH:~/crunchy-cli/crunchy` to your `.rc` file.

The command should work as intended afterwards.

**Comment by Medory13** [comment]
> Hello! How did you get the cli and which version are you trying to use? `https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.8` Should be the latest dev release that works. Since you seem to be on a linux distribution you can run the following:
> 
> ```shell
> wget https://github.com/crunchy-labs/crunchy-cli/releases/download/v3.0.0-dev.8/crunchy-v3.0.0-dev.8_linux
> chmod +x ./crunchy-v3.0.0-dev.8_linux
> mkdir ~/crunchy-cli
> mv ./crunchy-v3.0.0-dev.8_linux ~/crunchy-cli/crunchy
> export PATH=$PATH:~/crunchy-cli
> ```
> 
> and I'd recommend adding the `export PATH=$PATH:~/crunchy-cli` to your `.rc` file.
> 
> The command should work as intended afterwards.

thanks now it work!

but when I try to download https://www.crunchyroll.com/series/GEXH3WKK0/vinland-saga it gives me this errors:
:: → Season 1 of series VINLAND SAGA is not available with en-US audio
:: → Episode 1 (Slave) of season 2 (VINLAND SAGA Season 2 (English Dub)) of VINLAND SAGA has no espanol subtitles

command used: $crunchy download -s espanol https://www.crunchyroll.com/series/GEXH3WKK0/vinland-saga[1] 

so please how to make default audio to Japanese and how to put subtitle (what is countries encoding?)
