### ISSUE TITLE
how to login to Crunchyroll from windows terminal?

### ISSUE THREAD

**Issue by Medory13** [crunchy-labs/crunchy-cli#132]
Thanks for all devoloper its amazing tool :)

I have kali linux in my vmware but idk how to install ffmpeg on it..
So I went back to Windows and did everything and I added the crunchy-cli path but when I type this command:
`.\cr --credentials "user:password"`
I get this Error: `.\cr --credentials "user:password`

And the same error for other flags.. What I do wrong?

**Comment by ByteDream** [comment]
I think you pasted the incomplete version of the error log. Can you send the full log?

Btw. to install ffmpeg on kali, you'll have to use
```
apt install ffmpeg
```

**Comment by Medory13** [comment]
`C:\Users\*******\*******\********\*******\Crunchyroll>.\cr --refresh-token etp-rt
=> An error occurred: unknown flag: --refresh-token

C:\Users\*******\*******\********\*******\Crunchyroll>.\cr -refresh-token etp-rt
=> An error occurred: unknown command "etp-rt" for "crunchy-cli"

C:\Users\*******\*******\********\*******\Crunchyroll>.\cr -refresh-token -etp-rt
=> An error occurred: unknown shorthand flag: 'r' in -refresh-token

C:\Users\*******\*******\********\*******\Crunchyroll>.\cr --etp-rt
=> An error occurred: unknown flag: --etp-rt

C:\Users\*******\*******\********\*******\Crunchyroll>.\cr --credentials "user:password"
=> An error occurred: unknown flag: --credentials`

*I replaced the name of crunchycli to "cr.exe"*

**Comment by adracea** [comment]
Hello, the command to log in is `cr.exe --credentials "user:password" login` . You're missing the `login` at the end :).

**Comment by Medory13** [comment]
> Hello, the command to log in is `cr.exe --credentials "user:password" login` . You're missing the `login` at the end :).

![image](https://user-images.githubusercontent.com/108600718/215867396-3add805e-6254-42a8-8134-2e1a304b78f5.png)

I know the command and yes its not work :)

**Comment by adracea** [comment]
I'm pretty sure using the email is not the same as using the username

**Comment by Medory13** [comment]
> I'm pretty sure using the email is not the same as using the username

not work too :)
![image](https://user-images.githubusercontent.com/108600718/215872121-f3b9d935-7a38-4449-a3e1-ccd522d378a7.png)

**Comment by adracea** [comment]
Could you try the same in powershell? I'm just curious if this might be a cmd thing.

**Comment by ByteDream** [comment]
And which version are you using? (`crunchy --version`)

**Comment by Medory13** [comment]
> And which version are you using? (`crunchy --version`)



> Could you try the same in powershell? I'm just curious if this might be a cmd thing.

![image](https://user-images.githubusercontent.com/108600718/215933404-ef2deaaf-721b-4947-aa3b-2524ccafbf3d.png)

So is there any way to fix it? Is there anyone test it on windows?

**Comment by Medory13** [comment]
ohk xD
I was using old version (Marked stable)
now it work guys

**Comment by Medory13** [comment]
![image](https://user-images.githubusercontent.com/108600718/215957713-eecad696-400e-4c4a-9bcc-6a2dc9dc4e3a.png)

change it :)
Thanks for everyone helped me
