### ISSUE TITLE
Questions about proxies

### ISSUE THREAD

**Issue by ltsj** [crunchy-labs/crunchy-cli#142]
This is not a bug submission , i just want to ask, before version v2.3.6, proxies were supported, but v3.0.0 does not seem to support the use of proxies, Is it removed? and will it be supported in the future? Because some animations are only available in certain regions...

**Comment by ByteDream** [comment]
Yes, this can be re-added.

**Comment by ByteDream** [comment]
I'm working on proxy support ATM but I think this won't be implemented. As far as I can see socks5 and http(s) proxies aren't forwarding the TLS settings which are required to bypass Cloudflare. So proxies would work in theory but Cloudflare blocks all traffic unless the TLS config of the proxy server is especially configured to bypass the CF bot protection.

**Comment by ltsj** [comment]
Perhaps, the download part should not go through the proxy, which sometimes slows down the download speed. If it is just to unblock the region, you only need to proxy crunchyroll's api
