### ISSUE TITLE
Failed to Parse url 1 - Error while recieving format for nickname: 403 invalid json response invalid character

### ISSUE THREAD

**Issue by gundamvr** [crunchy-labs/crunchy-cli#143]
**Describe the bug**
Getting this error when trying to dl series. 
![image](https://user-images.githubusercontent.com/79481692/219456115-49d64e55-bd90-4712-b5df-3f9910b0db5c.png)

**To Reproduce**
Steps / command to reproduce the behavior:
```
crunchy.exe download -o "{series_name} - Season{season_number} - Episode {episode_number} - {title}.mkv" --subtitle en-US https://www.crunchyroll.com/series/G6X02X3EY/chiruran-12
```

**Expected behavior**
The system should parse the URL and dl the series. 

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows 
 - Version Latest Release

**Additional context**
I have tested various urls this happens with all best I can tell. My guess is they did recent api changes as this was working just afew days ago with no issues.

**Comment by adracea** [comment]
Hey are you using the 2.x release? If so, I recommend using the latest 3.x dev releases. The setup process is a bit different but it should work better.

**Comment by gundamvr** [comment]
Roger, I was using the public release figured the dev stuff was still WIP. I will give that a shot! Thanks for the fast reply

**Comment by gundamvr** [comment]
Thats working... thanks! I will keep the dev builds in mind for the future

**Comment by LetMeByte** [comment]
If you still need help, please provide more information. Otherwise, please close the issue.
