### ISSUE TITLE
Make output format configurable

### ISSUE THREAD

**Issue by mboman** [crunchy-labs/crunchy-cli#151]
It would be great if the output format string could be configured and stored in the configuration file so one does not need to re-enter it every time.

**Comment by LetMeByte** [comment]
A config file containing custom default values would be nice in general, but until that's implemented you could do something like [this](https://github.com/LetMeByte/crunchy.fish/blob/master/download/full-show), which is what I do.

**Comment by ByteDream** [comment]
This is out of scope (for now). I think something like this could be easily archived by writing a wrapper script which does this work.
