### ISSUE TITLE
Windows Dev release (3.08) and others don't ever seem to complete download?

### ISSUE THREAD

**Issue by gundamvr** [crunchy-labs/crunchy-cli#159]
**Describe the bug**
Tried using the latest dev releases available and while they do start a download they never finish, I left an attempt sitting for over a day and it just sits there in the 90% range... It is also very slow to get to 90% where the prior stable release when it worked still would almost instantly dl eps. 

**To Reproduce**
Steps / command to reproduce the behavior:
```
crunchy.exe download -o "{series_name} - Season{season_number} - Episode {episode_number} - {title}.mkv" --subtitle en-US https://www.crunchyroll.com/series/G9VHN97K8/chobits
```

**Expected behavior**
Should quickly download and complete episodes. 

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows 10
 - Version v3.0.0-dev.8 (have tried other earlier dev releases as well.. same issue for me). 

**Additional context**

**Comment by gundamvr** [comment]
It doesn't have any errors shown in the console just sits there stuck.. I am trying with other shows to see what happens. I use a VPN do you think that has anything todo with it?

**Comment by gundamvr** [comment]
So here is an example not using chobits.. I also disconnected from the vpn. This has been sitting here at 85% for about 
 10 minutes... If there is any more information I can provide let me know. 

Command used was 

crunchy.exe archive -o "{series_name} - Season{season_number} - Episode {episode_number} - {title}.mkv" -l en-US -l ja-JP https://www.crunchyroll.com/series/GRZX4PK4Y/chronicles-of-the-going-home-club

![Screenshot 2023-02-27 120340](https://user-images.githubusercontent.com/79481692/221658484-ac59cfd4-afe9-4575-a9d9-f32fa3d63d75.png)

**Comment by LetMeByte** [comment]
Coincidentally, `Chronicles of the Going Home Club` is also not available in Germany. Using a VPN, which did not cause any problems so far, I've been able download the both of the example shows, without any hickups.

**Comment by gundamvr** [comment]
I see well I guess I will just wait for the next official non dev release then because its not my PC spec/storage wise plenty of power and storage... but this has been stuck here for hours with no progress.. Hopefully the next official release will solve my issues. Thanks for your time. 
![Screenshot 2023-02-27 173416](https://user-images.githubusercontent.com/79481692/221721683-72682a90-77e3-48cd-83c6-3b77551a32e1.png)
![Screenshot 2023-02-27 173433](https://user-images.githubusercontent.com/79481692/221721685-8469a460-320c-4050-bb12-528205c0c8e1.png)
