### ISSUE TITLE
Unable to use login arguments (credentials,anonymous,erp-rt)

### ISSUE THREAD

**Issue by jauadbou** [crunchy-labs/crunchy-cli#160]
**Describe the bug**
I am not able to login with any login method. The arguments '--credentials','--erp-rt','--anonymous' are not being recognized.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy login --credentials "user:password"
```

**Expected behavior**
I am expecting to be able to login with my premium account (still works with v2.3.6)

**Screen
![Screenshot from 2023-02-27 02-51-56](https://user-images.githubusercontent.com/60118616/221453958-cff436c7-11de-4fcd-9ead-dec140a02e88.png)
shots**

**Client (please complete the following information):**
 - OS: Alpine Linux (Docker)
 - Version: 3.0.0-dev.8

**Additional context**

**Comment by LetMeByte** [comment]
As the [documentation](https://github.com/crunchy-labs/crunchy-cli#login) says, the `login` module has the following syntax:
```bash
$ crunchy --etp-rt "abcd1234-zyxw-9876-98zy-a1b2c3d4e5f6" login
```

The syntax will eventually be changed, but this is not exactly a bug. Please refer to the documentation before opening an issue.
