### ISSUE TITLE
since #156 login wont work till manual creating the folder

### ISSUE THREAD

**Issue by Serverfrog** [crunchy-labs/crunchy-cli#164]
**Describe the bug**
#156 changed the way of the configuration in that way, that now a folder with files inside, instead of single files, are used.
The problem arise when the Folder does not exists.
If the folder `/crunchy-cli/` is not created, it will get a "No such file or directory (os error 2)" error.
Additional its nowhere logged what the folder is, or where the error occurred.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ git pull
$ cargo build --release
$ crunchy --etp-rt xxxxx login
```

**Expected behavior**
Folder would be created, file with cookie will be written. No Error

**Client (please complete the following information):**
 - OS: Linux
 - Version 19f9d26af9dc84ce12a5498f13b4dc25c42bdda8

**Comment by ByteDream** [comment]
We indeed missed that, thanks for opening the issue. It should be fixed with commit d6f1262.
