### ISSUE TITLE
[Windows] "An error occurred: ffmpeg is needed to run this command correctly"

### ISSUE THREAD

**Issue by Terroosh** [crunchy-labs/crunchy-cli#173]
Trying to use the archive command and i get:
`[err] An error occurred: ffmpeg is needed to run this command correctly`

I have ffmpeg installed and listed in the environmental variables. Using ffmpeg gives:
```
ffmpeg version n5.0.1-20220406 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
```

How do I get crunchy-cli to recognize ffmpeg?

**Comment by lludu** [comment]
how did you solve this?
