### ISSUE TITLE
Archive/download issue

### ISSUE THREAD

**Issue by cakarlen** [crunchy-labs/crunchy-cli#179]
**Describe the bug**
I am still receiving a bug when attempting to download/archive `Attack on Titan (Dubs)` series using the latest build with and without the `--experimental-fixes` flag (see #171)

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli --vv --anonymous --experimental-fixes download https://www.crunchyroll.com/series/G24H1NM05/attack-on-titan-dubs
```

**Screenshots**

<img width="1869" alt="CleanShot 2023-03-23 at 20 18 59@2x" src="https://user-images.githubusercontent.com/33635487/227392229-1d193f6e-8cc8-4915-af66-ddd97629cc62.png">

**Client (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Version: `crunchy-cli 3.0.0-dev.8 (1213880 2023-03-23)`

**Comment by cakarlen** [comment]
Output without `--experimental-fixes` flag:

<img width="1870" alt="CleanShot 2023-03-23 at 20 21 05@2x" src="https://user-images.githubusercontent.com/33635487/227392533-649ad80d-d181-4a95-910b-4195eacc65d6.png">

**Comment by ByteDream** [comment]
You need Crunchyroll Premium to download this series.
