### ISSUE TITLE
cms_service_error After downloading a series

### ISSUE THREAD

**Issue by KoffeinKaio** [crunchy-labs/crunchy-cli#180]
**Describe the bug**
After you download one series (which works) you cant download anything after
error given: content.get_video_streams_v2.cms_service_error
If you want to watch via crunchyroll website it also gives a 403 content.get_video_streams_v2.cms_service_error
("try later")

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli archive -l ja-JP -l de-DE -s de-DE -o"{series_name}/Season {season_number}/S{season_number}E{episode_number} - {title}.mkv" https://www.crunchyroll.com/de/series/G63K98PZ6/one-punch-man
```

**Client (please complete the following information):**
 - OS: Linux Arch
 - Version crunchy-cli 3.0.0-dev.8 (1213880 2023-03-24)

**Additional context**
Might be a temporary block, had it yesterday and today I could download one series just fine, happened again afterwards

**Comment by ByteDream** [comment]
I'm investigating this. This error could be some sort of rate limiting although the error message doesn't really fit.

**Comment by Serverfrog** [comment]
@ByteDream i will switch from #119 to here, due to the fact that it is now this Problem ;)

I tested a bit and noticed that, before i start to try to download, everything is fine. Crunchyroll works and i can view things.
After i try to start to download, it will get the Episode list, waits a longer time then before i updated it and then this error happens. After this, all crunchyroll content is locked form quite some time.

**Comment by ByteDream** [comment]
The cause of this error is the stream endpoint, after 40-50 calls to the endpoint this error occurs (according to the tests I've ran).
2 months ago Cruchyroll shifted to a new streams endpoint which then got adopted in [crunchyroll-rs v0.3.0](https://github.com/crunchy-labs/crunchyroll-rs/releases/tag/v0.3.0) (the library used to make calls to Crunchyroll) and, resulting to the library update, in [v3.0.0-dev.9](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.9) too. And this new endpoint is now erroneous.
As the old stream endpoint, which was used until [v3.0.0-dev.8](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.8), still works it is possible to backport things and use the old endpoint again. But it is always possible that the old endpoint gets shut down at some point, so let us just hope that this doesn't happen or the error / rate limiting gets removed/fixed until then.
