### ISSUE TITLE
Failed to parse url 1

### ISSUE THREAD

**Issue by Laserstrahl** [crunchy-labs/crunchy-cli#181]
Maybe I'm doing it wrong, but it worked before:

.\crunchy-v2.3.6_windows.exe archive -o '{series_name}_S{season_number}E{episode_number} - {title}.mkv' -r 720p https://beta.crunchyroll.com/de/series/GRMG8ZQZR/one-piece[E1037-]

Results in:
=> Failed to parse url 1
=> An error occurred: failed to get episodes: error for endpoint https://beta-api.crunchyroll.com/cms/v2/DE/M3/crunchyroll/videos/streams?locale=de-DE (403): invalid json response: invalid character '<' looking for beginning of value

Anyone has an Idea what's wrong? It worked a month ago :/

Update: Just realized that it doesn't matter if I try to download a archive mode or download directly a video from the direct url... always the same issue :O

Example:
.\crunchy-v2.3.6_windows.exe download https://www.crunchyroll.com/de/watch/GMKUX2D94/believe-in-luffy-the-alliances-counterattack-begins

Results:
=> Failed to parse url 1
=> An error occurred: error while receiving format for Glaubt an Ruffy! Die Allianz holt zum Gegenschlag aus!: error for endpoint https://beta-api.crunchyroll.com/cms/v2/DE/M3/crunchyroll/videos/streams?locale=de-DE (403): invalid json response: invalid character '<' looking for beginning of value

I guess it is related to:
https://github.com/crunchy-labs/crunchy-cli/issues/137

**Comment by ByteDream** [comment]
Crunchyroll removed some endpoints. Version 2 of the cli is discontinued, try one of the version 3 dev releases from the [releases page](https://github.com/crunchy-labs/crunchy-cli/releases). Note that there are some changes in the cli flags / behavior (see the [README](https://github.com/crunchy-labs/crunchy-cli#readme) for examples).
