### ISSUE TITLE
[v3.0.0-dev.10] Archive with specific audio and/or subtitles gives `unexpected argument`

### ISSUE THREAD

**Issue by koo04** [crunchy-labs/crunchy-cli#194]
**Describe the bug**
When trying to use the archive command with `-a` and/or `-s`. The error `error: unexpected argument '-a/-s' found` is thrown.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive -a ja-JP -s en-US {url}
```

**Expected behavior**
I would expect no error and it run like normal

**Client (please complete the following information):**
 - OS: Ubuntu 22.04 Server (headless)
 - Version 3.0.0-dev.10 (ee1344f 2023-04-09)]>

**Additional context**
On Windows 11, although it does error. It seem subsequent calls do end up having having those settings. Not the same on Linux.

**Comment by ByteDream** [comment]
The flag to set audio languages in `archive` is `-l`, not `-a` (a bit confusing that `archive` and `download` have different flags to specify the audio, I think I'll change this).

**Comment by koo04** [comment]
Okay. I was following the README, so would be awesome to see the flags updated to match. For now I will use `-l`. Thank you for the quick response!
