### ISSUE TITLE
[mov,mp4,m4a,3gp,3g2,mj2] error reading header on 8th episode of Naruto

### ISSUE THREAD

**Issue by ameerabdallah** [crunchy-labs/crunchy-cli#197]
**Describe the bug**

Was downloading Naruto and the first 7 episodes downloaded successfully but then on the 8th episode, it failed:
```
:: a unexpected error occurred: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/.crunchy-cli_xkg6oe.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:23:15.40, start: 0.066733, bitrate: 706 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 624x480 [SAR 129:130 DAR 129:100], 702 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5633d88a0200] error reading header
/tmp/.crunchy-cli_C02kw9.m4a: Operation not permitted
```

I did this under WSL Ubuntu 20.04 and then decided to also try SSHing into my Synology NAS to see if it was a platform issue. They both produced the same results.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive https://www.crunchyroll.com/series/GYQ4MW246/naruto-shippuden -a ja-JP -s en-US -o "Naruto Shippuden - E{episode_number}.mkv"
```

**Expected behavior**
Continue downloading the other episodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/24537535/232729212-2a96d1a5-e410-49a6-83a6-5ba99f793a86.png)

**Client (please complete the following information):**
 - OS: 
   - WSL Ubuntu 20.04
   - Synology NAS
 - Version [e.g. 3.0.0-dev.12 (e277b42 2023-04-17)] 
 I also tried under 3.0.0-dev.11 and same thing

**Comment by ByteDream** [comment]
The important message is
```
...
/tmp/.crunchy-cli_C02kw9.m4a: Operation not permitted
```

This sounds like a permission error rather than a crunchy-cli/ffmpeg issue. For me it works on my machine as well as in docker (debian & alpine).

**Comment by ameerabdallah** [comment]
> The important message is
> 
> ```
> 
> ...
> 
> /tmp/.crunchy-cli_C02kw9.m4a: Operation not permitted
> 
> ```
> 
> 
> 
> This sounds like a permission error rather than a crunchy-cli/ffmpeg issue. For me it works on my machine as well as in docker (debian & alpine).
> 
> 
> 
> Edit: Although it's weird that it happens after the 8th episode and not earlier.

I was thinking the same thing about it being a permissions issue, except that like you mentioned, it's weird that it only happened after the 8th episode. I'll look to see what the stream specs for that episode compared to the others and get back to you.

**Comment by ameerabdallah** [comment]
Update: 

I was able to get it working by upgrading to ffmpeg version 4.4.3-0ubuntu1~20.04.sav5

The version that I was having the issue with was 4.2.7 which was the latest provided by apt repo. My Synology NAS had version 4.1.8 so it seems like the bugs been around for a while. 

Either way the fix for this was adding savoury1/ffmpeg4 ppa and updating:
```bash
sudo add-apt-repository ppa:savoury1/ffmpeg4
sudo apt-get update && sudo apt-get upgrade
```
