### ISSUE TITLE
error when saving using .ts format

### ISSUE THREAD

**Issue by MasterNoobNinja** [crunchy-labs/crunchy-cli#198]
**Describe the bug**
when saving without putting the information "-o file.ts" it works normally, he save the file in .mp4 format
when I use the -o file.ts option, I get the error

**To Reproduce**
does not work: crunchy-cli --credentials "aaa:aa" download -o file.ts -r 720p -s pt-BR -a en-US https://www.crunchyroll.com/watch/G2XU0QDE2/of-solitude-and-self
work: crunchy-cli --credentials "aaa:aa" download -r 720p -s pt-BR -a en-US https://www.crunchyroll.com/watch/G2XU0QDE2/of-solitude-and-self

**Expected behavior**
:: √ Generating output file                                                                                             :: a unexpected error occurred: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\AppData\Local\Temp\.crunchy-cli_YaWpCP.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:26:22.46, start: 0.000000, bitrate: 3994 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 3991 kb/s, 24 fps, 24 tbr, 90k tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\AppData\Local\Temp\.crunchy-cli_761x4X.m4a':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:26:22.51, start: 0.000000, bitrate: 131 kb/s
  Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Input #2, ass, from 'C:\Users\AppData\Local\Temp\.crunchy-cli_rpoyt5.ass':
  Duration: N/A, bitrate: N/A
  Stream #2:0: Subtitle: ass
Automatic encoder selection failed for output stream #0:2. Default encoder for format mpegts (codec none) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:2

**Client (please complete the following information):**
 - OS: Windows 10 and Windows 11
 - version	"v3.0.0-dev.12"
 - ffmpeg version 4.4-full_build and ffmpeg 6.0 full build

**Comment by luizoti** [comment]
Same problem here, i will test without -o, but the error exists.

**Comment by MasterNoobNinja** [comment]
in release dev. 9
there was a change, Default file extension got changed from .ts to .mp4

but they removed the option to use the file as .ts
my solution was to use a release previous to version: v3.0.0-dev.9

https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.9

I leave a suggestion to be able to continue downloading the .ts file

**Comment by ByteDream** [comment]
Fixed in [v3.0.0-dev.13](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.13). However it's recommended to switch to `mp4` as converting to `ts` is resource intensive and slow.

**Comment by luizoti** [comment]
thx
