### ISSUE TITLE
Running crunchy-cli in a docker container

### ISSUE THREAD

**Issue by l0westbob** [crunchy-labs/crunchy-cli#203]
Hi,

I wanted to run crunchy-cli without installing it on my M1 mac. I've read about issues with the M1 runners and decided to create a docker image and a docker compose file to run it in a docker container. 

I have created a repository with my result and wanted to share my solution:
https://github.com/l0westbob/crunchy-cli

Thanks for creating crunchy-cli !

Have a good day :)

**Comment by ByteDream** [comment]
I'm closing this. The recommended way to build `crunchy-cli` is using `cargo` (as described in the README). People who want to run this in docker/want to build this in docker are probably experienced enough to install cargo and compile it themself so I won't add a build docker file. And if they want to use docker nevertheless they may find this issue via the GitHub search and adapt it.
