### ISSUE TITLE
Download subtitles only

### ISSUE THREAD

**Issue by ltsj** [crunchy-labs/crunchy-cli#204]
Is it possible to add parameters to only download subtitles in the specified language of the subtitle video? Just like yt-dlp
~~Another one is to support the video link in crunchyroll rss~~

**Comment by ByteDream** [comment]
This was already requested in #70. I know that #70 is already open for a while but it's still on the list of things to add.

**Comment by ltsj** [comment]
> This was already requested in #70. I know that #70 is already open for a while but it's still on the list of things to add.

Sorry, I didn't pay attention to see, thanks for reply
