### ISSUE TITLE
I can¡t download multiple subtitles

### ISSUE THREAD

**Issue by Mayansito** [crunchy-labs/crunchy-cli#205]
I'm using
Crunchyroll download -s es-ES -s es-LA -s en-US -a ja-JP -o "name.mkv" link
Crunchyroll download -l es-ES -l es-LA -l en-US -a ja-JP -o "name.mkv" link

And not working. 
"is not available with es-ES es-LA en-US subtitles"

**Comment by ByteDream** [comment]
Which series or episode do you try to download?

**Comment by Mayansito** [comment]
https://www.crunchyroll.com/es-es/watch/G50UZ1D27/believe-in-yourself

Have this 3 subs.

**Comment by Mayansito** [comment]
![image](https://github.com/crunchy-labs/crunchy-cli/assets/98242308/e7199ccf-62d5-4691-86fc-9985603615b2)

**Comment by ByteDream** [comment]
You need `archive` instead of `download` if you want multiple subtitles.

E.g.
```
crunchy archive -a ja-JP -s es-ES -s es-LA -s en-US https://www.crunchyroll.com/es-es/watch/G50UZ1D27/believe-in-yourself
```

**Comment by Mayansito** [comment]
Okey, another question. Which is the quality for 720p? 1080p is best.

**Comment by Mayansito** [comment]
Oke, and for download 720p? ik for 1080 and 480.

**Comment by ByteDream** [comment]
> Oke, and why subs look like that? Only happens on certain animes xd.
> 
> ![image](https://user-images.githubusercontent.com/98242308/239989498-2eb1b160-6772-403a-a864-3a71a354eb80.png)

Can you give some example which anime have this "broken" subtitles?

**Comment by Mayansito** [comment]
Happens with some of them, not all.
This ss is from https://www.crunchyroll.com/es/watch/G2XU0D10D/heat-and-complications

**Comment by ByteDream** [comment]
It works fine in other players and as the [website of MPC-HC](https://mpc-hc.org/) states it's not active developed anymore since 2017. I do not plan to implement fixes for legacy players who themselves say that you should use another player.
