### ISSUE TITLE
Organization / Metadata

### ISSUE THREAD

**Issue by RedCommander735** [crunchy-labs/crunchy-cli#209]
**Is your feature request related to a problem? Please describe.**
I've downloaded a series, but it gets really hard to organize, if you only have the title.

**Describe the solution you'd like**
It would be extremely helpful, if the episode number / season could be written at the beginning of the file name 
(like "[S1E1] _EpisodeName_")or in the file metadata and if crunchy would create a folder per series, with respective subfolders for each season.

**Comment by ByteDream** [comment]
This can be done with the `-o` / `--output` flag. You can see the available metadata which can be replaced by running `crunchy-cli download --help` / `crunchy-cli archive --help` in the help section for `-o` / `--output`.
