### ISSUE TITLE
Download just one video track, but two audio tracks

### ISSUE THREAD

**Issue by ToMattBan** [crunchy-labs/crunchy-cli#214]
**Describe the bug**
My goal is to download an EP that will have two audio tracks and one subtitle. I'm making it with the comand

```
$ crunchy archive -a ja-JP -a pt-BR -s pt-BR URL[S1]
```
but it download two video tracks, the japanese one and the portuguese one. 

What I wanted to do is to download just one video track (It should be the same between both languages) but the two audio tracks. 

The audio change works really well, the subtitles also works, but downloading two times the same video tracks seems a waste of time and internet XD

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/50156748/dbe5fab8-5ccc-4c4b-bb8b-bca771d378c1)

**Client (please complete the following information):**
 - OS: Windows
 - Version: 3.0.0-dev.13

**Comment by ToMattBan** [comment]
Ok, I discovered that sometimes it happens
![image](https://github.com/crunchy-labs/crunchy-cli/assets/50156748/6c1ff61b-0e49-47a7-b2b7-233dfee9fd08)
This image is from "To your etternity"

But, in other animes it download two video tracks
![image](https://github.com/crunchy-labs/crunchy-cli/assets/50156748/dc5c8eec-ea50-4735-abbc-ded7e2a849d5)
This image is from "Dr. Stone"

**Comment by ByteDream** [comment]
This behavior only occurs if Crunchyroll reports that the episode are different in length. But if you're sure that the episode videos are the same, you can pass the `-m audio` flag which forces to only download one video (documented in the `Merge behavior` section under the [archive examples](https://github.com/crunchy-labs/crunchy-cli#archive))

**Comment by ToMattBan** [comment]
Hmm, I didn't know that Crunchyroll make things this way. Thank you for explaining. 
I will use the `-m audio` option, I just checked some of these eps and they have the same length, maybe is some milliseconds of difference? I didn't watched the full episode to see if they differ in some other thing.

Thank you again
