### ISSUE TITLE
'crunchy' not recognized as name of cmdlet, function, script....

### ISSUE THREAD

**Issue by lludu** [crunchy-labs/crunchy-cli#218]
**Describe the bug**
Running the command to login throws an error "The term 'crunchy' is not recognized as the name of a cmdlet, function, script file, or operable program"  (see below)

**To Reproduce**
Once fully installed after completing these commands:
```
git clone https://github.com/crunchy-labs/crunchy-cli
cd crunchy-cli
cargo build --release
cargo install --force --path .
```

**Running the command to login throws an error:   (using abcd token replacement for my actual token)**
```
crunchy --etp-rt "abcd1234-zyxw-9876-98zy-a1b2c3d4e5f6" login


PS D:\Stream Downloaders\crunchy-cli> crunchy --etp-rt "abcd1234-zyxw-9876-98zy-a1b2c3d4e5f6" login

crunchy : The term 'crunchy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ crunchy --etp-rt "0303e165-461c-4d42-bdb7-b57b962144fb" login
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (crunchy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

The powershell is running inside of the same install folder i was just using

  <img width="955" alt="powershell" src="https://github.com/crunchy-labs/crunchy-cli/assets/62399229/c26031b4-836d-4e82-b231-280d33bb466c">

**Comment by ByteDream** [comment]
Try using `crunchy-cli` instead of `crunchy`

**Comment by lludu** [comment]
> Try using `crunchy-cli` instead of `crunchy`

Yes thank you that worked fine, now i just need to figure out how to address configurations to use ffmpeg, getting an error downloading series
