### ISSUE TITLE
Help with FFmpeg file location

### ISSUE THREAD

**Issue by lludu** [crunchy-labs/crunchy-cli#219]
**Describe the Issue / Help Needed (not bug)**

Trying to download the series from crunchyroll, says FFmpeg is needed. I have the entire FFmpeg github cloned into the main crunchy-cli folder, as well as the ffmpeg, ffplay, ffprobe executables. But i still receieve the error, how can i configure the crunchy-cli to use the ffmpeg? is there a specific file that needs changed, or should i place the ffmpeg files in a certain location?

```
PS D:\Stream Downloaders\crunchy-cli> crunchy-cli download https://www.crunchyroll.com/series/G4PH0WXVJ/spy-x-family
:: Misconfigurations detected: FFmpeg is needed to run this command
```

**Screenshots**
<img width="818" alt="crunchy-cli" src="https://github.com/crunchy-labs/crunchy-cli/assets/62399229/e29aa4c9-765e-43f1-ab96-fd805d846401">

**Client (please complete the following information):**
 - Windows 11

**Comment by ByteDream** [comment]
[This article](https://phoenixnap.com/kb/ffmpeg-windows) covers how to install ffmpeg on Windows.

**Comment by lludu** [comment]
> [This article](https://phoenixnap.com/kb/ffmpeg-windows) covers how to install ffmpeg on Windows.

Yeah you're amazing for that, thanks! its all good now
