### ISSUE TITLE
Add Hardsubs command

### ISSUE THREAD

**Issue by Anekoi** [crunchy-labs/crunchy-cli#221]
Could you please add an option to download hardsubs directly from crunchyroll servers?

Crunchy has its titles with burned subtitles for those devices that do not support subtitles in the ass format, and to avoid having to burn the subtitles locally you could implement a special command to download the video with hardsubs, and thus save time that the video would take encoding with ffmpeg

Here I show an example of the url that is used for a video with hardsubs:

> https://v.vrv.co/evs3/9fefa2b2caa5b102d56e1568f7cf0427/assets/bf6739d464ee1725967f1bde259f5b44_5195679.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMzLzlmZWZhMmIyY2FhNWIxMDJkNTZlMTU2OGY3Y2YwNDI3L2Fzc2V0cy9iZjY3MzlkNDY0ZWUxNzI1OTY3ZjFiZGUyNTlmNWI0NF8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg4MzEyNjA4fX19XX0_&Signature=fWiMwONLzsy~X3SMAAN2GZ0~c3jwiKEz1XvmnaAkLeZH526uN57lLAF~xfmsm7UBVDcaovLL5NpSOx0LmSqfXVJo0GrK4OPkGMnVrHXRnj5xl-52~J11hHv7IMrNiG5ymPAmGCzMYMrvAOCRsR~wCwxP07hTHtYfFSk4mkMnKeTGoSEbqqFwHhhqEtPcmAoeeWGvtaR2R7a1s-DkPUTdcxtDvjhSJqcK10ZPE4t8b8B59lubWKUrmJQwfW2j545tZtIn2-PbMTFdzBVV~gDnJaGHO0inGV7WxMvPmiwPZ1NwRgDVqV9zthjnEeM-eyNKfvmwlclerjpRt4xYx1u9zw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA

**Comment by ByteDream** [comment]
The `--force-hardsub` flag to enforce burning of the subtitles with `download` got implemented in [v3.0.0-dev.15](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.15).
