### ISSUE TITLE
support the old version url

### ISSUE THREAD

**Issue by ltsj** [crunchy-labs/crunchy-cli#224]
Hope to support the old version url like this : http://www.crunchyroll.com/me-roboco/episode-3-her-roboco-904892 🥹

**Comment by ByteDream** [comment]
Support for this got implemented in [v3.0.0-dev.15](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.15) (internally it just follows the redirect to the "new" url).
