### ISSUE TITLE
One piece doesn't get all the episodes and it can't find the dubs for most of them even though 900+ exist

### ISSUE THREAD

**Issue by jlw4049** [crunchy-labs/crunchy-cli#225]
**Describe the bug**
One piece doesn't get all the episodes and it can't find the dubs for most of them even though 900+ exist

**To Reproduce**
Steps / command to reproduce the behavior:
./crunchy archive url/one-piece

**Comment by jlw4049** [comment]
Actually seems like it's crunchy roll maybe having issues and not the tool. As some of the episodes randomly are showing up without the audio.

**Comment by ByteDream** [comment]
This is partially an Crunchyroll issue. Over at r/Crunchyroll there are [several complains](https://www.reddit.com/r/Crunchyroll/search/?q=one%20piece) about it... . Some episodes randomly aren't dubbed for some reason. But this only affect(ed) the `download` command, `archive` should work fine.

**Comment by ByteDream** [comment]
Fixed in [v3.0.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0). A warning is printed if a episode is detected which is missing dub even if it should have one.
