### ISSUE TITLE
no subtitles 

### ISSUE THREAD

**Issue by fragilegirl** [crunchy-labs/crunchy-cli#226]
**Describe the bug**
we have tried to download an episode with english subtitles but it seems to not want to every videos we download with the command it doesn't get the subtitles 
$ .\crunchy-cli.exe archive -o "[S{season_number}E{episode_number}] {title}.mkv" -a ja-JP -s en-US https://www.crunchyroll.com/watch/G2XU0DM97/the-sacrifice-and-the-night-of-the-ritual

![image](https://github.com/crunchy-labs/crunchy-cli/assets/50789094/c492d315-7b03-429e-8955-0ebaa9b9d153)

**Client (please complete the following information):**
 - OS: [e.g. Windows 11]
crunchy-cli main branch

**Comment by ByteDream** [comment]
So the subtitle is not present in the output file? When I run it locally everything is fine

**Comment by apalmer223** [comment]
hey yea i'm having a similar issue . when i specify the subtitle language i get that the program is downloading the english subtitles but the output has no subtitles. this is the command im currently running 

"""
crunchy-cli download -s en-US -a ja-JP https://www.crunchyroll.com/watch/GRNV9W296/the-one-who-has-my-heart-my-mind-and-soul
"""

**Comment by Nannk** [comment]
Have the same issue. tried en-US and de-DE. None worked. `archive` did not work too.

**Comment by ByteDream** [comment]
For me the subtitles are there, both with the video from the original question as well as the video from the command @apalmer223 has posted.

![Screenshot_20231011_223349](https://github.com/crunchy-labs/crunchy-cli/assets/63594396/04784c9a-9b94-46dd-b6f3-70743da730ac)
![Screenshot_20231011_223528](https://github.com/crunchy-labs/crunchy-cli/assets/63594396/138d52fa-68ab-4704-bd28-678c187ad833)

**Comment by Nannk** [comment]
So it is not a Hardsub anymore?

Im opening with mpv, on mkv file it sees the sibtitles track, but i cant select them. Can it be a mpv issue? 

Ill try with another player.

**Comment by ByteDream** [comment]
Yes it is not hardsub anymore. With `archive` it was always softsubs and with `download` we switched to softsubs for `.mp4` and `.mov` files a while ago to reduce the processing time. But if you want hardsubs nevertheless, you can pass the `--force-hardsub` flag to force burning in the subs

**Comment by Nannk** [comment]
Then i find readme misleading. Ive opened an [issue](https://github.com/crunchy-labs/crunchy-cli/issues/252) and if you dont mind, would like to discuss how the readme should be written and make a PR later.
