### ISSUE TITLE
Subtitles don't have spacing/number support in english

### ISSUE THREAD

**Issue by xackery** [crunchy-labs/crunchy-cli#228]
**Describe the bug**
Playing with dev release, I noticed this oddity with subtitles (ASS, non-burned into video): no spacing.

**To Reproduce**
```
$ crunchy-rust archive --skip-existing -a ja-JP -r 480x360 -o "s{season_number}e{episode_number}.mkv" https://www.crunchyroll.com/series/GMEHME55K/the-worlds-finest-assassin-gets-reincarnated-in-another-world-as-an-aristocrat[S1E1]
```

**Expected behavior**
Proper spacing, proper numbers on subtitles

**Screenshots**
<img width="849" alt="Screen Shot 2023-07-14 at 6 44 42 AM" src="https://github.com/crunchy-labs/crunchy-cli/assets/845670/02fc1607-162f-4956-baf7-5de1dcc2f79a">
<img width="316" alt="Screen Shot 2023-07-14 at 6 44 32 AM" src="https://github.com/crunchy-labs/crunchy-cli/assets/845670/f893a212-3164-4bf0-8ca9-810b23dfbfcd">

**Client (please complete the following information):**
 - OS: linux (ubuntu)
 - Version: crunchy-cli 3.0.0-dev.14 (f4682e0 2023-06-19)

**Additional context**

**Comment by ByteDream** [comment]
Which video player did you use?

**Comment by xackery** [comment]
Plex

**Comment by xackery** [comment]
I also did hard coded subtitles, and had a similar experience

**Comment by ByteDream** [comment]
This is probably because your plex host is missing the font(s) used by the subtitles, in this case `Arial`. This is a known plex [issue](https://forums.plex.tv/t/incorrect-subtitle-rendering/838042). Explicitly configuring plex to not burn in subtitles seems to [fix the issue](https://forums.plex.tv/t/incorrect-subtitle-rendering/838042/20) too.

**Comment by xackery** [comment]
This fixed the issue. Thank you!
