### ISSUE TITLE
Archive v/a stream and subtitles separately, mergeble with mkvmerge

### ISSUE THREAD

**Issue by hajimekun** [crunchy-labs/crunchy-cli#229]
**Is your feature request related to a problem? Please describe.**
Not a problem but will be better if we able to store the video+audio and subs separately, and make it mergeble using mkvmerge from system instead of ffmpeg.

**Describe the solution you'd like**
Adding possibility to archive in subfolder the raw files in raw format (.ts .aac .ass or mp4+ass) and create a new option to merge them using mkvmerge from system path only on archive method. 

**Additional context**
At this moment there isn't an option to download subtitles only or video + audio sub and the only way to create mkv is ffmpeg.
I don't like using ffmpeg to generate mkv then I'd like to have the possibility to merge the files by myself or store it whitout and additional step.

Your efforts will be appreciated

**Comment by ByteDream** [comment]
The `download` and `archive` commands are designed to create ready-to-play video files with as little effort and as few dependencies as possible. They are made for this specific use case, just downloading the files isn't in scope for those.
For any other extend requirements, the search command (#217) got implemented in [v3.0.0-dev.14](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.14) which gives you more freedom with the results, thus it requires additional logic as the command only returns urls to the streams and subtitles.
