### ISSUE TITLE
Anime fails to download, causes fail at src/media/streaming.rs:97:48

### ISSUE THREAD

**Issue by xackery** [crunchy-labs/crunchy-cli#231]
**Describe the bug**
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crunchyroll-rs-0.5.0/src/media/streaming.rs:97:48

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli archive --skip-existing -a ja-JP -s en-US -r 480x360 -o "s{season_number}e{episode_number}.mkv" https://www.crunchyroll.com/series/GW4HM7N7X/hajime-no-ippo-the-fighting
```

**Expected behavior**
Successful download

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Ubuntu
 - Version: crunchy-cli 3.0.0-dev.15 (db156d3 2023-07-21)

**Additional context**
N/A

**Comment by ByteDream** [comment]
Fixed in [v3.0.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0).
