### ISSUE TITLE
Audio Downloads Full But Video Not Full Length

### ISSUE THREAD

**Issue by bunnygirl6** [crunchy-labs/crunchy-cli#232]
**Describe the bug**
While Downloading Video & Audio Both Shows 100% and Output File is Generated But Output Size is lower compared to shown in command line. Video length shows full 24 min but in reality audio is 24 min video is 12min and after that its struck frame and audio only, it happens sometimes only and after trying 2-3 times full video is downloaded.

**To Reproduce**

crunchy download -a en-US https://www.crunchyroll.com/watch/G6JK7W70R/girl-of-steel

**Client (please complete the following information):**
 - OS: [Windows]
 - Version: [crunchy-cli v3.0.0-dev.15]

**Comment by ByteDream** [comment]
Does this still occur? I've tried to reproduce it multiple times, on Windows and Linux but had no success so far.

**Comment by bunnygirl6** [comment]
No, it was temporary maybe
