### ISSUE TITLE
a unexpected error occurred: expected value at line 1 column 1 at 1:1

### ISSUE THREAD

**Issue by MoAlakhres** [crunchy-labs/crunchy-cli#234]
**Describe the bug**
a unexpected error occurred: expected value at line 1 column 1 at 1:1

**To Reproduce**
$ crunchy-cli --experimental-fixes archive -r best -a ja-JP -s en-US -a en-US -o "[S{season_number}E{episode_number}] {title}.mkv" https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece

**Expected behavior**
I am trying to archive entire series of One-Piece but when it gets to about 117 episodes in it give out this error as seen in the images. 

**Screenshots**

![Screenshot (2)](https://github.com/crunchy-labs/crunchy-cli/assets/76079608/a9e3dd76-3bcb-4618-bec6-b8f935776a6c)

**Client (please complete the following information):**
 - OS: Windows 11 x64 WorkStation Edition
 - Version: crunchy-cli 3.0.0

**Comment by MoAlakhres** [comment]
:: Downloading The Weirdest Guy Ever! Jango the Hypnotist! to '[S01E10] The Weirdest Guy Ever! Jango the Hypnotist! (1).mkv'
::      Episode: S01E10
::      Audio: ja-JP
::      Subtitles: en-US
::      Resolution: 1920x1080
::      FPS: 23.97
:: Downloading video #1      1.39 GiB  61.75 MiB/s [####################################################################################################################################################################################] 100%:: Downloading ja-JP audio  23.44 MiB   5.68 MiB/s [####################################################################################################################################################################################] 100%:: Downloading subtitles    en-US
:: √ Output file generated
:: a unexpected error occurred: expected value at line 1 column 1 at 1:1 (https://www.crunchyroll.com/cms/v2/US/M3/crunchyroll/videos/GPPFXD44K/streams?Signature=nsxwxAaGe2olxZWatrCS6uwe7PlQgQLOjsBXixyuORyA4hFcwiQeOmyy0N-goVp0zwafZ92o%7EOazEq-WEMNLbTWsfX%7EfNFS1MiTqUS55oFDTVkH5MGsUdnZ%7Eip2MJGg0oB79jkEmpDnQ5QUHT-96fDLQ-a%7EEu85%7E9C2Ar5iTlAjTDK3vTM1X850gLuH-3f0jeMbkI-0vDvWGQvv4BTS1u0PMEtabNvLQ92hfsJwmIoBEtPjtPfH%7EjU2%7EqECLTVzU%7EuYM9cCGiz5RjMuVFKEyjUk-ALXdupn-d3qOZuUHxPOWzcADX2C9sS6OKmRV4Oc6W2qXGSTVa1SAfQwUEq0YOA__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMy9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkxOTczNzA0fX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&locale=en-US): : <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'www.crunchyroll.com',cType: 'interactive',cNounce: '42876',cRay: '7f5d164369b92bab',cHash: '5eef48e23b9551f',cUPMDTk: "\/cms\/v2\/US\/M3\/crunchyroll\/videos\/GPPFXD44K\/streams?Signature=nsxwxAaGe2olxZWatrCS6uwe7PlQgQLOjsBXixyuORyA4hFcwiQeOmyy0N-goVp0zwafZ92o%7EOazEq-WEMNLbTWsfX%7EfNFS1MiTqUS55oFDTVkH5MGsUdnZ%7Eip2MJGg0oB79jkEmpDnQ5QUHT-96fDLQ-a%7EEu85%7E9C2Ar5iTlAjTDK3vTM1X850gLuH-3f0jeMbkI-0vDvWGQvv4BTS1u0PMEtabNvLQ92hfsJwmIoBEtPjtPfH%7EjU2%7EqECLTVzU%7EuYM9cCGiz5RjMuVFKEyjUk-ALXdupn-d3qOZuUHxPOWzcADX2C9sS6OKmRV4Oc6W2qXGSTVa1SAfQwUEq0YOA__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMy9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkxOTczNzA0fX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&locale=en-US&__cf_chl_tk=IfwaqeHIgzH6vfGsWuxTxRd1FjGPhjNHnlrIYHK8ZGI-1691889116-0-gaNycGzNFTs",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "",fa: "/cms/v2/US/M3/crunchyroll/videos/GPPFXD44K/streams?Signature=nsxwxAaGe2olxZWatrCS6uwe7PlQgQLOjsBXixyuORyA4hFcwiQeOmyy0N-goVp0zwafZ92o%7EOazEq-WEMNLbTWsfX%7EfNFS1MiTqUS55oFDTVkH5MGsUdnZ%7Eip2MJGg0oB79jkEmpDnQ5QUHT-96fDLQ-a%7EEu85%7E9C2Ar5iTlAjTDK3vTM1X850gLuH-3f0jeMbkI-0vDvWGQvv4BTS1u0PMEtabNvLQ92hfsJwmIoBEtPjtPfH%7EjU2%7EqECLTVzU%7EuYM9cCGiz5RjMuVFKEyjUk-ALXdupn-d3qOZuUHxPOWzcADX2C9sS6OKmRV4Oc6W2qXGSTVa1SAfQwUEq0YOA__&amp;Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMy9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkxOTczNzA0fX19XX0_&amp;Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&amp;locale=en-US&amp;__cf_chl_f_tk=IfwaqeHIgzH6vfGsWuxTxRd1FjGPhjNHnlrIYHK8ZGI-1691889116-0-gaNycGzNFTs",md: "UDdETpSUzbOH0SV5ndKzEtlQiPL.D5vIDQnlDk4w0UU-1691889116-0-ATVO9Q0IuyEUwekh75D8z4vyQ_TvHkNgoP6Ag7Ui6uZMoOk2rdvAvPD_tqHrsthZd-oKklo8R_ZciS-ly5LDGp7ImZPNznjeO5qlW12WtUzYR69-BM4D3ZBqR4XeQ_Vutm6Z_yu1zoQmGgsmmloKIz84d52WXL5whMvQtiPN04othp8KT-U9d4HeI6CzmgXfWQkCcu5htoZiF-sy9g1_dyL0YSCCKJV-AUWjYp6Dr2kLpFSo2iBktCHQBDkE0Q0MhU09t--EMlPFMZ8KBZaa5trTI8m42rgBp2Vo31ak4QbLSWZ-LQdEG7Xd-9gZA-clsu04Phu_i6IcL4ik3MqqkKo4PIjEtidN8Le3nJuw2GmulToRd4s_qs-UUvNjooqOx-X2WqjWXCrElthLEyTuvqPWh7u6I1hMrwM4Lz_Q1i8wSE49fz-k9YiNZuMz_nDbUVEc22xaDxWB93bYz_4NND4GR20xpDZpF6mxX_xsZ4-M71NZc8MV_ptpc1jycHORyzw6iqvsOq2zrX4uEDWur1gsF6zf12IEt9OP2Q9yHQcVu_x74ndas2_nGztpRiaMK563U5EiDSHEV0MSz6_vlIq20H6NiezbRGKKhseCH00LMTrqWUIZLBMdMSHS7wDOzu6pRSuMRNajj5v_7ZFfMzy6qQO89uWboW9SSRxlgBqXJyTXR034OuE-NLT1-d5SvOvQ-81C_xOVgXqM0oabcFKt3EJHpuIfPavess9qvncokkmw5CsULyk33zsET0HVu8rzEu-X8cx8tku-YsLg-2-jYOAtePO6EGT1U31wndmAgmksoS1jeV6QyRgwEvrNjTRRGTKI5ST_63j0Ai5JYSJEtEngmkvl-c8vPB1u2EFf8SSCBguZP-dl3kh29h2ZoQ7YnC5cQywVdJ4BS_BePt_CdB6sOP4_38Hs5v0rYp10KOBZ3cn08UR2TiNm4c4ku34pn0W4xgKoNWaY9P29HfDnWRG1Mq95awu7L-G6YWnfsCWnFrGlBNhCK8YXHMD2soxCinGS0cB7nz-zlJuDrGan_tOoUx5_aYLkGWkgs8-qGiCKjci7Kzob3ZB4ahgI4N4aE_80vy8n2DAKSzW5UvlaerJRUjCBA3ZxJ2H9BnoA2D6ViE5wMo7I05gjP7sqyT2g7aEyU-mP4g__BoXyUtZtYU3IOIDp1nVYZt-5dEZTHr7OZYuFwxkGiCxAJeP_P_hu9qgGangHyXnyOPyrRnm-fmfsjLTJ-fmYLRVuOpziScXBtEXBb5nkFcZSRxwU4wj-tFQ_AZ1TUajkG5zZPMMGTXAMtU2qn8hjOfeInR2MNjJ-NMHlKbpl_AdEktoBMqgoPfdcTw11rUD1iJhHV8xMdOZvY5lvzT0Snaf9yKxoxTtJI-9fADkTvTtjFNRoX2El4TJYZvw0BUMVI6q0ee6NhMKDTunaoHsIyRTdmXd6jQFHpJHHkctBEciJ3opWncTvASB4x-B2DSeZFU2afaLy3nbR6gySp-J0myhXOMItVLo8sGlpq57t1tsV9UoYPzvqzfMtbi9Ggh7HhjWaatx7BYg5FlOfLOjIdP4pc-68X_28xrmJmZsDyj1nnHhBf7sJY_PG5mty_g0r3S4tUikzjy0iZdMZ8ZNgHunkroPliQZpCHI13-FfyybXN6LyE-KUQEEHqrDXMdBnoKYGJM5IX9mRVJFLONCD3bXTwYLeKjfrNnpNpaVFTm1jAGDiWVHyMXmzU6bKfa6KQDU5F7L8UY-vYNHIqkxQ9kMM-fKT5QuB3ImBXDZEkBQ-xb3T05eEBY4GGSmQlbEfkWojVcZgyKeY9fW0tsMJ6iCKPDf7_9AXyRws_QCFG7_fm0m-Pt2ge-z1ZDcipMl0BXLiJqFLcFO-9eLqjkE4u46pg-PX9fGvRQUsSQVMe4952yDVBJNcqJAmbP1qomR5ySE0ai5tps8t_yAWYCyZH5DF2zmUQYe42sPeMNCl1qZiBwUyllwSi2A1VJN9hhqSKoX4Av1-GjuCvXQtoGpYS8uq3ojPXPmdqYxTofTuKUJyxSBzLxUJkcs8zzj9dZHWabMrAU7-D8FyJ8jCAtzr0L6fIlal_ptb_gpYiI2ap8VMyGXGT1K69Wht2OyVxyKfHKus6t6MXGeehNf74ar2j-Qk9Rvn-gBQRuw2WTqy1xyUfh9LBqyzKltCpnPxlQ_Wr4gJypmg_STlay9f9lHe2nN7EQirCbaFcEqVHCxSozFeqlGUSId90YJBrf6S0kCIL1GKHhLe_iGXEpmnKz0jmJJCTJIkwkJ9oQLCPzpjZSRpUc64f3g3ZYz7WRxdqjCM3H0JKwob7QCcCjmU2sFkT8wAFf3GQiYblcUSaw_NSI-__QVK43IZPOXwGULxerorAElq8cEwRqUvfCZ-d5W6RGY1vcXy0IgbTNh6uHLl2pJYglxqAiyH27PMZ8YasxSQ5nO9f_MXa-cqLepS86Ht_Ed5OqeLAza_7rTA3CMZjP49XxmnbqqZOCvYwMRi_6ETxewPSn25oRH96Vg6w7xv-udogfh2oX8Bj-KdyvRxK5ZjZ3fQbUNVayLuIMKwkulbYB9HVusalNTBpxLglZLfCtrRDdtyO4iLPZe-mMDF0nkm-ldfrmr994tXVc5fTKSU6SwIrmX6PhUoOly9jmGRSUKjUFgAJUBWSLuzvMvX0F1g2fxHcxOtgPoFg3zyWGXgS0qSkOvUe4nV_cr6rrLhb48pEEtseNj7ITezWkkEcIKOXiC4oLZO7TTdu-z4eEVF6H3VMO6NU8t94bwpSJvnsokx6K7WuSHFBOwXey4X-8uzHlLTqHAscktzOI7DjCFqdMVDW6TkilJ4LFJX0gEsGci_lyz2LJu-5acKHTynbfiXs-PMredQd8EE1JMcOovmEsvg_cTQxIYnhKSwIeSJ0TgoEQbBG5tmPbNgCiy-W8tRN24WT7glWlP57bzfEEJnaVPm8j63_mPwMg7_SyymQhzEaaJXbpcWrK3tgyVKi_aEagGTPvvLpRz0jC3Hcay1pu9zXVj05QU9dv791StKmiHJuSHGeQEIbZQxMUhOQnmjvmwroQsSW0lwJj2JL_NshpqqXuhUa_4PuTyXMMCUiC8nZy7hPWH9CwSOj9shZOV65cimhCWbLjV9grPje1lrVOmwOg9Fe4JLn4LgC_1iqAA8c-X2zpjMNqdBTPuHJ0DcUIFYkTjFnV8jzUb1TcTcn85oE9Zw5etwXSjgePcVt7KZxdlqFszFnY5vi6ZeV-3OWqzA1ESWC6FuUt13s-BS6vatnJmorUsGA-K5Trbfgw9a6rdKgYgdK4aSL6R26Cms4bW2vZX57hl6TWn9a5cDNQPxC8oS6CfqLi__oa9mu1Ay6_s-AO77lAZFCzFIWbwAcdIGJtmkedRb8-f5lfRtWsK3plrdy4JY7kZW-Lruz4PFRuSyQi_HjkGF60spLCZk3VcJOoX-7uOELE7jN4IJxTfcJygctI9z4ifO14sdf1gASYDzl0PXfzL_wEJDlDP2kOycsY4yi0eMIlbOPEzN5jLspkxdzHfW4eI9MrxiwwjWcJVfP-p5UC6sIiHQ3SSs-2quHy1MT2wOcY9G-NU80Mxt3X0uM80vTyAgHKOUBA0XmRrFtIePJnFYMMdpQQG_mPzJQ3UrNV4K2HElOBsQ2qm0_GH_s371b2-gaDw8MGPN8TsyuQj5X676YQAbdPEqYvbfUfVANnixHnJ9guabRtb06D46r0xlOh5D1WicTz5vZlL7aBwu8RijscTziICkYqItZ6sMMYeFkoO9resWiNpDUM733_Fm7QNIAw75zCRbCRW3AxXNZF3HhtwoZEMmGNws2-Wc3Ux2IEdbfF6vRTIx9VtLi1fKsN5OCXTcNXEPvE8px-LX7W7KgKKb0FuOe9-znw6CpSPkNO-ZD1uLnDCNk2ZOet7SOH1qoz7VH6bFToPpgnpoG0DM5XoeFxOnDKaq9ZJXYU8VPv-bt61BC0s6RYgrf75lV1C8HEZIuQKL905K79Ih6MxMoNFh_532QB4cnwkkq8gMfynhss-cCYqLY6gpALO9vhmjU9Yx5C_tIs4-vhIqDWtP4zIBijyqoL9ZKKOD56-D-FkB983zXYNQIJ0-JpQhFKzVyWiNgVEI-GtcOnBNWPyxuidFdPsjq6vbD59Fo6nZ1ng60JchLfEvxiYTA8R69QmjaifCnlDHDP5dJzd646Dx1CLlPE1YqljZNMxMhoTtLbbmXLuNsO3PHhDaaEAMVa1mYoNRv9tT3qC4XK4IZFbMuU6A1Ogo6nHlYm1-ckVojHi5ZvEOlQR2SSv_iQh0PKdXfK4OpPYo-BWVWSyCIgmOxF5bZAXHXqF1xkAv6B7vpWgOzBP4RI6dQewSVf1Lc5tTg_Fq1cUCDZ_ahbgW5-qiJbr8GzGLxAoE2y7BH2oTniokkO28bfYgxrEW0emWY4ur1tj36AQxQi47JJ1p2gcS9Q4ViDYkZcvXMaRwrFti4lRMWNsi2J8xN8dH6-IsHxfPMBKsbbQL_d4AKWH4UimjkR4s7LwfAtHYDcgaYm1f4s2LoRj4UmBMFUmspqPcQX6Q8UUpikIW9GbZmKqUBKOSd8LS0PMo8eCxqFOF7nGMnHxwaO0aXWyZjxHybWzh-Kkuz_gVOkylkG9tpTdVLh0DJMxZYQTdUF1Xl9u3UMLc_hbwULHxK76hC35uc_Kig8IBFEN5nfRMo3meq7X3Xht1uf71EA6utjQSqV6MMJmD1AJjUbS6ESoyynvpPTnIWINn_Wgveio8cDRxNAvnvi2IddJmX9hvdIy2-vPM20wpt9DEJ-rhfh1r71hkmzUWqw3mhFml0kQtrnqLb5O1rG_e93qEV8MPX0sPA_SV7CfDk9Mf0eHhCWYr_19oWRssavuwpJ6FnL1SYuggLWDP9CDNLFuYWPtytso64iZqqh_7Y5tIaWMQt22v-XFR61ZOxAtcxv1Yv1-Y7GqqoejKGqmvwiLEdbRy9Nlr5FTqClMltL-CwupKcpyaFm9D6VxKpIs2JZnJubmBb_lkHoyy_RN1joiBua8X685ytRFeoCXerjR3-kHQcife-aOIXjmYytUMTMhIVbOpmR6cu1rP79kDwQEO2n8WE9aAgbYch-lITDIEFETcbd314y4Ue3AqSExQLin7VTz3DsI-mUuORLVBXu0ZXflcti7rB6qJNf_N4Sy7pALnhGNKqn7fwm733alMpggU6IDLx_pEeuIE5sMjlk86uasefW7GHz3lyDoaIvxM_L9mDaa6o4j-khPGa7dvcAkUVAbbUeYDC7O-eEGASSNtKmeoqvJK9TQc_ucAMkXe4fmNKjMCnybO73dMBDgOJVAANMLOcpTtMiXfc5YYpVUacLv7wwkGNQ",cRq: {ru: 'aHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Mi9VUy9NMy9jcnVuY2h5cm9sbC92aWRlb3MvR1BQRlhENDRLL3N0cmVhbXM/U2lnbmF0dXJlPW5zeHd4QWFHZTJvbHhaV2F0ckNTNnV3ZTdQbFFnUUxPanNCWGl4eXVPUnlBNGhGY3dpUWVPbXl5ME4tZ29WcDB6d2FmWjkybyU3RU9hekVxLVdFTU5MYlRXc2ZYJTdFZk5GUzFNaVRxVVM1NW9GRFRWa0g1TUdzVWRuWiU3RWlwMk1KR2cwb0I3OWprRW1wRG5RNVFVSFQtOTZmRExRLWElN0VFdTg1JTdFOUMyQXI1aVRsQWpUREszdlRNMVg4NTBnTHVILTNmMGplTWJrSS0wdkR2V0dRdnY0QlRTMXUwUE1FdGFiTnZMUTkyaGZzSndtSW9CRXRQanRQZkglN0VqVTIlN0VxRUNMVFZ6VSU3RXVZTTljQ0dpejVSak11VkZLRXlqVWstQUxYZHVwbi1kM3FPWnVVSHhQT1d6Y0FEWDJDOXNTNk9LbVJWNE9jNlcycVhHU1RWYTFTQWZRd1VFcTBZT0FfXyZQb2xpY3k9ZXlKVGRHRjBaVzFsYm5RaU9sdDdJbEpsYzI5MWNtTmxJam9pYUhSMGNITTZMeTkzZDNjdVkzSjFibU5vZVhKdmJHd3VZMjl0TDJOdGN5OTJQeTlWVXk5Tk15OWpjblZ1WTJoNWNtOXNiQzhxSWl3aVEyOXVaR2wwYVc5dUlqcDdJa1JoZEdWTVpYTnpWR2hoYmlJNmV5SkJWMU02UlhCdlkyaFVhVzFsSWpveE5qa3hPVGN6TnpBMGZYMTlYWDBfJktleS1QYWlyLUlkPUFQS0FKTVdTUTVTN1pCM01GNVZBJmxvY2FsZT1lbi1VUw==',ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzExNC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMTQuMC4xODIzLjY3YQ==',rm: 'R0VU',d: 'jliamBPgOfWC4tdfp2drDb5x8lh4OXpd4OwvoL3NpZFyhvgqCsSTTADK95nbxPdXl8mxIvDVZzEQF1B//rvkHzxuja7aoPpkWSi/hhPMMxI5+Yr8d9Hx3ttx/TiuGvgFln0I4rTew7xrutLxvtUGgC24Ad9VTNOk0tZoIwLj0DGOvPj9DWz2UcByGc84I6J60ZHn2tOxNPZnmmczrMwGsheMQgxpe78VEP/ckXjp6zEB0eqQd7JKkt91xKjC/O7n/x3hQsRHiV3zBrGe63pSOd0BoYWMJDbhN6QOY7Gamqxp+npLi4th42C7LNR59WaglScSCXWtblKlbE8Y/pKDmymNqe0uMh7NC6EMsY7u8GTRdh+em3G+bDaRnZGHOM7ngE41bhuqGTN4Z5eIjbXolHBdDXPvSUA2Bf64gdsbUhgKNMOKDEjmYLBg4baLmamhTFTVvFgkFInh4uCj9Oc9b9qmN/V8VatOEwxn870aRjMaqKXcqsSsXPM96AFxLWE+pXlXLHsTUweXsUfxV7sDuAR2j0Y/j11oSEFabJMKjtk=',t: 'MTY5MTg4OTExNi43MDMwMDA=',cT: Math.floor(Date.now() / 1000),m: 'BHfo4Bw9knLnHja+2uZxJLHaet/G025ZyVu0BRfZ/6M=',i1: '7LL+0IWZykYRgFs+Gh5bIg==',i2: 'rQpNNtLNfRpKEuGa80gPgQ==',zh: 'qQz4tblgEgtOKuLwUaA7NrEUXyzFHvjAH4jkpQCn35I=',uh: 'khEF8jUex0IHaWvQrTOSJ7wstwSk8MX26uyppCHwbfo=',hh: 'X/ui56Hpfhv5vN0FUDU58Tk8kOdH4hwp+B7yjRL1zVA=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=7f5d164369b92bab';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/cms\/v2\/US\/M3\/crunchyroll\/videos\/GPPFXD44K\/streams?Signature=nsxwxAaGe2olxZWatrCS6uwe7PlQgQLOjsBXixyuORyA4hFcwiQeOmyy0N-goVp0zwafZ92o%7EOazEq-WEMNLbTWsfX%7EfNFS1MiTqUS55oFDTVkH5MGsUdnZ%7Eip2MJGg0oB79jkEmpDnQ5QUHT-96fDLQ-a%7EEu85%7E9C2Ar5iTlAjTDK3vTM1X850gLuH-3f0jeMbkI-0vDvWGQvv4BTS1u0PMEtabNvLQ92hfsJwmIoBEtPjtPfH%7EjU2%7EqECLTVzU%7EuYM9cCGiz5RjMuVFKEyjUk-ALXdupn-d3qOZuUHxPOWzcADX2C9sS6OKmRV4Oc6W2qXGSTVa1SAfQwUEq0YOA__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMy9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkxOTczNzA0fX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&locale=en-US&__cf_chl_rt_tk=IfwaqeHIgzH6vfGsWuxTxRd1FjGPhjNHnlrIYHK8ZGI-1691889116-0-gaNycGzNFTs" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);};}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

**Comment by Denoder** [comment]
You're being blocked by cloudflare see https://github.com/crunchy-labs/crunchy-cli/issues/104

**Comment by ByteDream** [comment]
Yes this is a cloudflare issue, as @Denoder correctly said. The only workaround to prevent this from happening is using a VPN or proxy.
I've added a proper error message in [v3.0.1](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.1) which makes it a bit clearer when a cloudflare block occurs.
