### ISSUE TITLE
nix flake: failed to create symbolic link 

### ISSUE THREAD

**Issue by lachydavies25** [crunchy-labs/crunchy-cli#235]
I am having issues with installing crunchy-cli using nix

**To Reproduce**
`nix --extra-experimental-features "nix-command flakes" run github:crunchy-labs/crunchy-cli `

`failed to create symbolic link '/nix/store/56g9g326h70gm1bcjayq9q0insga7b0j-cargo-vendor-dir/native-tls-0.2.11/9dr71sh81nqhp3797mxzgdvz01iicxrg-native-tls-0.2.11': Permission denied`

**Screenshots**
<img width="1491" alt="Screenshot 2023-08-16 at 8 10 48 pm" src="https://github.com/crunchy-labs/crunchy-cli/assets/37570905/a30df6fe-3524-4768-8997-a6b1c4f51635">

**Client: M2 MacBook Air 2 15"**
 - OS: MacOS public beta - Sonoma beta 3

**Comment by ByteDream** [comment]
@stepbrobd any idea why this fails?
If I'm correct this failure exists since dc6bc0d. Beginning with this commit the `native-tls` crate got replaced by a [fork](https://github.com/crunchy-labs/rust-not-so-native-tls) of it. If I remove the [line](https://github.com/crunchy-labs/crunchy-cli/commit/dc6bc0d9516e8d7bb19d1f8a02189987a4c53643#diff-10cfc24be365e55208a2b7a89029f15105ed856666f103a148422d387822be7fR39) which overwrites the crate with the fork, the error disappears.

**Comment by stepbrobd** [comment]
> If I'm correct this failure exists since https://github.com/crunchy-labs/crunchy-cli/commit/dc6bc0d9516e8d7bb19d1f8a02189987a4c53643. Beginning with this commit the native-tls crate got replaced by a [fork](https://github.com/crunchy-labs/rust-not-so-native-tls) of it. If I remove the [line](https://github.com/crunchy-labs/crunchy-cli/commit/dc6bc0d9516e8d7bb19d1f8a02189987a4c53643#diff-10cfc24be365e55208a2b7a89029f15105ed856666f103a148422d387822be7fR39) which overwrites the crate with the fork, the error disappears.

<details>

<summary>
Good catch! The line you mentioned resulted in two `native-tls` entries present in `Cargo.lock`, this is not supported by `buildRustPackage`.
</summary>

1.

```toml
 [[package]]
 name = "native-tls"
 version = "0.2.11"
 source = "git+https://github.com/crunchy-labs/rust-not-so-native-tls.git?rev=570100d#570100d3391bd9aab7a390cfef0d1a28e8efe200"
 ...
```

2.

```toml
 [[package]]
 name = "native-tls"
 version = "0.2.11"
 source = "registry+https://github.com/rust-lang/crates.io-index"
 ...
```

</details>

There are couple ways to solve this:

1. Removing `native-tls` [fork](https://github.com/crunchy-labs/rust-not-so-native-tls) from dependencies, or
2. Writing patch to remove duplicate entries in the `Cargo.lock` file, or
3. Try using a [community maintained toolchain](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#using-community-maintained-rust-toolchains-using-community-maintained-rust-toolchains), they might support duplicate entries in `Cargo.lock` (haven't tested this yet, will look into it).

Related:

- https://github.com/NixOS/nixpkgs/issues/22177
- https://discourse.nixos.org/t/rust-with-git-deps-symbolic-link-error-to-cargo-vendor-dep/28841
- https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md

**Comment by ByteDream** [comment]
I removed duplicated entry from `Cargo.lock` / now only rely on the `[patch.crates-io]` section in `Cargo.toml`.
@lachydavies25 you should be able to run it via nix now.
