### ISSUE TITLE
homebrew tap

### ISSUE THREAD

**Issue by kennedy** [crunchy-labs/crunchy-cli#237]
**Is your feature request related to a problem? Please describe.**
Installing `crunchy-cli` from Homebrew (`brew`) would make ease of use for macOS users

**Describe the solution you'd like**
Have a new repo called `homebrew-tap` with the cask for `crunchy-cli` along with the darwin_amd64 missing version.

**Additional context**

**Comment by kennedy** [comment]
Someone already made a `homebrew-core` pr for `crunchy-cli` https://github.com/Homebrew/homebrew-core/pull/139018

**Comment by kennedy** [comment]
The original PR was abandoned, but was also re-building the binary.

I created my own cask pr because it doesnt need to be rebuilt. 

https://github.com/Homebrew/homebrew-cask/pull/158759

**Comment by ByteDream** [comment]
Thanks for doing this. I'm not a Mac/Homebrew user myself, so it had low priority to me

**Comment by kennedy** [comment]
@ByteDream :) it was a good opportunity for me to learn how to contribute to homebrew and participate in hacktoberfest. Unfortunately, my `cask` PR was rejected. I am going to attempt to revive your previous `core` PR with another PR. Hopefully that would get traction. 

An alternative would be to create a new repo called `homebrew-tap` within `crunchy-labs` and have users pull directly. This gives the org more control, only requiring the version number to be bump in the same release cadence. I already created this way as well. 

Let me know which way you would like to proceed.

**Comment by kennedy** [comment]
yay we did it. 

https://github.com/Homebrew/homebrew-core/pull/152666
https://github.com/Homebrew/homebrew-core/pull/152679

https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fcrunchy-cli
