### ISSUE TITLE
Relative episode number are sometimes wrong

### ISSUE THREAD

**Issue by GauvainWizard** [crunchy-labs/crunchy-cli#238]
Hello ! I have experienced a bug with relative episode number.

**Describe the bug**
For some series, the relative episode number are wrong.
For example, for Tokyo Revengers, episode 1 of season 1 is marked as relative episode number of 25.
Episode 2 is 26, etc..

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli archive --yes --skip-existing -a ja-JP -a fr-FR --default-subtitle fr-FR -o '{series_name}/Season {season_number}/{series_name} - S{season_number}E{relative_episode_number} ({episode_number}).mkv'
```

**Expected behavior**
Episode 1 of season 1 should be marked as relative episode number of 01.

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/20990951/466695e3-bcb8-4975-83a1-e52408199b2c)

**Client (please complete the following information):**
 - OS: Ubuntu 23.01
 - Version v3.0.1

**Additional context**
I tried with "--experimental-fixes", but it didn't change anything.
I understand this could be a problem related to the way Crunchyroll is matching episodes number to a season but was wondering if you could do something about it.

Thank you !

**Comment by ByteDream** [comment]
Fixed in [v3.0.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.2).
