### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by Blazzycrafter** [crunchy-labs/crunchy-cli#239]
**Describe the bug**
yeah thats its....
invalid_grant (auth.obtain_access_token.invalid_credentials) -  (https://www.crunchyroll.com/auth/v1/token)
if i try to acess the provided link i get an does not work error
https://i.imgur.com/GLAxvDU.png

maybe the api is broke?
¯\_(ツ)_/¯

**Expected behavior**
its should login

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/39300111/0bcef111-c1ce-4060-8f1d-d9963c12c02b)

**Client (please complete the following information):**
 - OS: windows 11 Insider Build: 22631.2129
 - Version: latest master release

**Comment by ByteDream** [comment]
Are your credentials correct? If the contain any special letter Windows/your shell might interpret it wrong, try wrapping them in quotation marks if this is the case.

It works fine when I use my credentials.

**Comment by Blazzycrafter** [comment]
> Are your credentials correct? If the contain any special letter Windows/your shell might interpret it wrong, try wrapping them in quotation marks if this is the case.
> 
> It works fine when I use my credentials.

Thanks.....
