### ISSUE TITLE
Relative Episode Numbers - Ignore 0.5

### ISSUE THREAD

**Issue by ohitstom** [crunchy-labs/crunchy-cli#241]
Some series have .5 episodes quite often, i wouldnt class these as whole episodes and this can mess with metadata providers.

Maybe ignore all special episodes or round numbers?

or maybe just an option alltogether to ignore specials

**Comment by ByteDream** [comment]
This is a design choice. I know that it cause trouble with some series (there was a similar issue with episodes whose episode number is 0 (#206)) but `relative_episode_number` is for people who want their episode number always relative to the season the episode belongs to. This format option isn't meant to interact in any way with the "real"/provided episode numbers (like .5).
