### ISSUE TITLE
Subtitles are very squashed together. Hard to read

### ISSUE THREAD

**Issue by admin-at-ajrich-co-uk** [crunchy-labs/crunchy-cli#243]
**Describe the bug**
Since 3.0.0 the subtitles in en-US have been very squashed together making it hard to read them. The words seem to join together 

**To Reproduce**
Steps / command to reproduce the behavior:
```
.\crunchy-cli-v3.0.0-windows-x86_64.exe download --skip-existing --audio ja-JP --subtitle en-US --resolution best --output "../{series_name}/Season {season_number}/{series_name} - S{season_number}E{relative_episode_number} - {title} - {resolution}.mkv" https://www.crunchyroll.com/series/G6VN7WW0R/girls-bravo
```

**Expected behavior**
Normal subtitles with better spacing. 
<img width="1091" alt="Screenshot 2023-08-23 at 22 04 43" src="https://github.com/crunchy-labs/crunchy-cli/assets/141287256/6e6f1a9e-27bb-4497-b11a-ca105478a58f">

**Screenshots**
![Uploading Screenshot 2023-08-23 at 22.04.43.png…]()

**Client (please complete the following information):**
 - OS: :Windows and linux (ubuntu) both tested
 - Version 3.0.0

**Additional context**
Seems to happen with any Anime producing ASS subtitles

**Comment by ByteDream** [comment]
This is probably because your system doesn't have the required fonts. Most subtitles are using the _Arial_ font. Ubuntu doesn't have it pre-installed as this font is [proprietary](https://i.imgur.com/TGYC0Q2.jpeg) but on Windows it should be fine though.

**Comment by admin-at-ajrich-co-uk** [comment]
Didn't even consider that. I'll download the Arial font - thanks!

**Comment by admin-at-ajrich-co-uk** [comment]
I've tested it again now with the font installed and it seems to be converting it to mkv with ffmpeg causes the subs to look like this. When i download as MP4 it's fine. Ill redownload as mp4 for now, not sure if this is an ffmpeg issue or not

**Comment by ByteDream** [comment]
I think this is rather a issue of your video player than ffmpeg. On my computer™ it works fine with vlc.
