### ISSUE TITLE
Ability to download only audio, subs or both without video

### ISSUE THREAD

**Issue by DefaultLP** [crunchy-labs/crunchy-cli#244]
My apologies if this feature was already requested or is already implemented. I looked through the Issues but did not find a similar problem. I also tried the `--ffmpeg-preset` but with no success.

**Is your feature request related to a problem? Please describe.**
Not really so much a problem, but more an inconvenience. I already have the required video files but wanted additional audio and subtitle files. Since where I live one can only download German subtitles and no English. So I resorted to downloading both files twice in different regions.

**Describe the solution you'd like**
Possibly an additional argument like `--no-video` that disregards the video portion.

Another solution would be to not combine the downloaded video, audio and sub files. When downloading multiple audio and sub files each one could append like `{title}.en.aac` and `{title}.en.srt`. I thought at first that `-m/--merge`  would support this but it is only considered when the video length does not match the audio length.

**Additional context**
I'm unsure of how easy this is to implement. On the one hand, the different files are downloaded separately so it could be as simple as to just not combine them. On the other, I know that not combining them could lead to unexpected problems that would need to be addressed.

**Comment by ByteDream** [comment]
You can utilize the `search` command for this. This might require some additional work as this command isn't as simple as `download` and `archive`.

I can give you two examples which works on Linux:
- Download english audio of the first episode of darling in the franxx:
  ```shell
  $ ffmpeg -i $(crunchy-cli search --audio en-US -o '{{stream.hls_url}}' https://www.crunchyroll.com/watch/GRDKJZ81Y/alone-and-lonesome) test.mp3
  ```
- Download english subtitles of the first episode of darling in the franxx:
  ```shell
  $ curl -o test.ass $(crunchy-cli search --audio ja-JP -o '{{subtitle.locale}} {{subtitle.url}}' https://www.crunchyroll.com/watch/GRDKJZ81Y/alone-and-lonesome | grep 'en-US' | awk '{print $2}')
  ```

**Comment by DefaultLP** [comment]
Ah, I see. Thank you very much! I only focused on the `download` and `archive` commands.

While it is a bit more involved, it certainly is a lot simpler than writing a custom bash file for it.

 Thank you for making such an awesome tool!
