### ISSUE TITLE
Override default configuration with a file

### ISSUE THREAD

**Issue by kennedy** [crunchy-labs/crunchy-cli#245]
**Is your feature request related to a problem? Please describe.**

When using a media organizer (i.e tinymediamanager), its best to organize files in `{series_name}/Season{season_number}/S{season_number}E{relative_episode_number} - {title}.mp4`. However, the default configuration is `{title}.mp4`. I would either have to write that template out over and over, scroll through cli history, or forget and have to redownload/use a renaming tool. This can be quite error prone.

**Describe the solution you'd like**
Most cli applications can override default configurations using some kind of config file such as `.env`. It would be great if `crunchy-cli` can read a config file and override defaults for download, search, or achieve. This way, it would be consistent every time and easily referenced.

**Additional context**

**Comment by Nannk** [comment]
Using alias would be one of the solutions.
As example, ive set mine like that:
`alias crunchy-cli-archive="crunchy-cli archive --ffmpeg-preset av1-lossless --skip-existing -s de-DE -a ja-JP -o \"S{season_number}E{episode_number} {series_name} - {title}.mkv\""`

**Comment by bytedream** [comment]
I'm closing this issue for now. The alias option suggested by @Nannk is a very good alternative way which I personally prefer.
I already started a implementation twice but questioned the usefulness of it and discarded the changes. I see some advantages of a config file but they aren't high enough to convince me to implement and maintain it.
