### ISSUE TITLE
Getting ALL audio by default/using a param?

### ISSUE THREAD

**Issue by momokinou** [crunchy-labs/crunchy-cli#247]
Hello,
Thank you for your work.
I have a question, I've read the md and I can't understand something. How can I find out automatically which audio files are available on a series?

I would like to know if it is possible to download everything by default or by using something like "-a all"

I'm new to Rust and would like to know if I can try to implement your cli in a Rust Tauri?
Thanks for everything :D
Have a nice day.

**Comment by ByteDream** [comment]
There is currently no easy way to see which audio languages are available but it should always be the case that the languages which are available via the app/website are also the one which can be downloaded.
`-a all` to download all available audios is already implemented (for the `archive` sub-command).

**Comment by ByteDream** [comment]
> I'm new to Rust and would like to know if I can try to implement your cli in a Rust Tauri?

Sure. Depending on your needs/what you want to implement you can also use the underlying [library](https://github.com/crunchy-labs/crunchyroll-rs).
