### ISSUE TITLE
Error hit a rate limit when downloading

### ISSUE THREAD

**Issue by kazrhak** [crunchy-labs/crunchy-cli#248]
**Describe the bug**
I installed the crunchy-cli for the first time using Windows, I did it with the commands that you indicate in the Readme, with the Scoop and when I download any chapter, I get the error: "You've probably hit a rate limit".

I have tried several chapters and several series and the same thing happens in all of them.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy download --force-hardsub -a ja-jp -s es-419 -r 720p -o "{series_name} Season {season_number} - Capítulo {episode_number} [{resolution}].mkv" https://www.crunchyroll.com/es/watch/GWDU8Q28Q/dead-or-love
```

**Expected behavior**
Download correctly with crunchy-cli

**Screenshots**
![limite CR](https://github.com/crunchy-labs/crunchy-cli/assets/58183590/0d429c90-bef0-47cb-973b-d2fcc38a9b99)

**Client (please complete the following information):**
 - OS:[Windows
 - Version V.3.0.2

**Comment by ByteDream** [comment]
This should be fixed in [v3.0.3](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.3). The update isn't in the scoop repos yet but I think it should be in there in the next few hours (depending on the schedule the scoop repo update service has)

**Comment by koo04** [comment]
I also did run into this. v3.0.3 did fix it.

**Comment by kazrhak** [comment]
Hello!

With version 3.0.3 it has already been solved!

Thanks!!
