### ISSUE TITLE
Missing Key-Pair-Id query parameter or cookie value

### ISSUE THREAD

**Issue by Fridleif** [crunchy-labs/crunchy-cli#249]
**Describe the bug**
I don't know if it's really a but or if I'm doing something wrong. At some anime I got this error:

`<Error><Code>MissingKey</Code><Message>Missing Key-Pair-Id query parameter or cookie value</Message></Error>
`

**To Reproduce**
Steps / command to reproduce the behavior:
```
crunchy-cli.exe download -o "{series_name} - S{season_number}E{episode_number} - {title}.mkv" https://www.crunchyroll.com/de/series/GRX0M59K6/strike-the-blood[S03]
```

**Expected behavior**
Downlaod the file

**Screenshots**
![Bildschirmfoto 2023-09-24 um 11 06 25](https://github.com/crunchy-labs/crunchy-cli/assets/5839847/a1418669-8100-4bde-adcc-a9ac28e3af5f)

**Client (please complete the following information):**
 - OS: Windows 11
 - Version 3.0.2

**Additional context**
I'm not that familiar with reporting errors or asking for help on github. So please be gentle Thanks :D

**Comment by ByteDream** [comment]
This might be an account type issue. Did you login with a premium account to use the cli?

**Comment by Fridleif** [comment]
> This might be an account type issue. Did you login with a premium account to use the cli?

Sure I do ... but it's a new account and in the 14 days test period... maybe is that an issue? 
Maybe interesting to know: the first season was downloaded without any issues

**Comment by Fridleif** [comment]
I don't know why - I've changed nothing not even installed a windows update or rebooted the pc ...
It's working now...
