### ISSUE TITLE
Download Speed Limiter

### ISSUE THREAD

**Issue by koo04** [crunchy-labs/crunchy-cli#250]
**Is your feature request related to a problem? Please describe.**
Although not a *problem*, I would like to have the ability to slow down the speeds as to not bog down my entire internet.

**Describe the solution you'd like**
Would like to see a flag (say `--speed-limit`) that can take a `MB` or `Mb` per second for limiting. I only just started getting into Rust and have not learned if that is possible with the stuff being used here, but it is not a new concept. So I am assuming it can be done.

**Additional context**
No other context needed, for now.

**Comment by bytedream** [comment]
Added in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0)
