### ISSUE TITLE
Misleading readme

### ISSUE THREAD

**Issue by Nannk** [crunchy-labs/crunchy-cli#252]
The readme is a bit misleading regarding usage and outdated regarding subtitles.

> Besides the audio, you can specify the subtitle language by using the -s / --subtitle flag. The subtitles will be burned into the video track (cf. hardsub) and thus can not be turned off.

The subtitles are not hard anymore. It is mentioned later but not directly.

The additional flags description is easy for misinterpretation.
Writing something like `crunchy-cli --flag [option]` should help in my opinion.

**Comment by ByteDream** [comment]
The last sentence can be replaced with the explanation that subtitles in `.mp4`, `.mov` and `.mkv` are stored as soft-subs and in all other formats as hard-subs

**Comment by Nannk** [comment]
What do you think about changing it like [this](https://github.com/Nannk/crunchy-cli/commit/34edbd4598695cb1c1c2f36167f8c319dc7b2ec1)?

**Comment by ByteDream** [comment]
Looks good👍
