### ISSUE TITLE
os error 87

### ISSUE THREAD

**Issue by ToMattBan** [crunchy-labs/crunchy-cli#253]
**Describe the bug**
I'm trying to download "Jobless Reincarnation" with dual audio and brazilian subtitle, but it always five me this error after donwloading video and audio. It says incorrect parameters.

![image](https://github.com/crunchy-labs/crunchy-cli/assets/50156748/4fc74867-1852-49ca-9bf7-bb6ffc1bad20)

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive -a ja-JP -a pt-BR -s pt-BR -m audio -o "../_Novos/Mushoku Tensei: Jobless Reincarnation (2021) {tmdb-371310}/S{season_number} E{episode_number} - {title}-org.mkv" https://www.crunchyroll.com/series/G24H1N3MP/mushoku-tensei-jobless-reincarnation[S01E01-E100,S02-S50]
```

**Expected behavior**
Donwload the anime, with audio in Japanese and Portuguese and Brazilian subtitles.

**Client (please complete the following information):**
 - OS: Win10
 - Version 3.0.3

**Comment by valentinegb** [comment]
I was unable to reproduce this on macOS using the latest commit of `crunchy-cli`, I installed two episodes before I interrupted the command.

**Comment by ByteDream** [comment]
This is a Windows specific error. When looking for the error on the internet and given that I cannot reproduce this on Linux too, the cause is probably that the underlying ffmpeg command is too long for Windows (once again a weird windows-only edgecase 🙃).
The command can be shortened down by using ffmpegs' `-f concat`, I can see if it really works/fix it later today.

**Comment by ToMattBan** [comment]
=P 
I will get the linux version then and run in my other computer

@ByteDream if you want me to test something here on Windows, just ask.

**Comment by valentinegb** [comment]
> (once again a weird windows-only edgecase 🙃)

Gotta love those Windows-only bugs lol

**Comment by ByteDream** [comment]
> Gotta love those Windows-only bugs lol

Yes windows got me once or twice with its weird behavior (e.g. d090a5a1daa781be9aac83950a8318267ccd5317 I was so pissed when I did this commit)

**Comment by ByteDream** [comment]
So I've tried the command on a Windows VM and I also got an error but with a different error code. The cause may not be the length of the underlying command but special characters in the filename which are forbidden on Windows ([there are plenty](https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3)). Can you re-try the command without any of the colon `:` character in the filename?

**Comment by ToMattBan** [comment]
Ok @ByteDream now I'm just feeling dumb. The anime name have a ":" and this was the cause of the error.

But it still is a strange behavior, since it downloads all the video and audio tracks and just throw an error when trying to download the subtitle, as show in my screnshot up there.

**Comment by valentinegb** [comment]
> But it still is a strange behavior, since it downloads all the video and audio tracks and just throw an error when trying to download the subtitle, as show in my screnshot up there.

It's probable that it had finished downloading the subtitles and had gone into the FFmpeg phase, which is right after.

**Comment by ToMattBan** [comment]
Makes sense @valentinegb since the subtitles are what is faster to download (I believe)

**Comment by ByteDream** [comment]
I had sanitation already in place to prevent such errors but it would only sanitize the replaced [output template options](https://github.com/crunchy-labs/crunchy-cli#output-template-options) instead of the full output argument.
The commit above fixes this

**Comment by bytedream** [comment]
I reverted the commit in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0). There are simply too many cases where the fix breaks other parts/possibilities (on Windows 🙃), e.g. Windows named pipes, locations on other drives (#289), ...

**Comment by ToMattBan** [comment]
Yeah man, Windows sucks with this, don't worry too much. Maybe add something on the readme about it?
"The path of the output can't contain any `:` or `/`"
