### ISSUE TITLE
Thread "main" panicked error

### ISSUE THREAD

**Issue by exus85** [crunchy-labs/crunchy-cli#258]
**Describe the bug**
I can't download since last week

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive -a ja-JP -s it-IT -s en-US  -m audio -o "x:\anime\One Piece\S21\{series_name} E{episode_number} {title}.mkv" --skip-existing https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece[S13E1079-]
```

**Screenshots**
![error YtDlp](https://github.com/crunchy-labs/crunchy-cli/assets/27153298/59d70b82-ef3b-4029-a6ec-48361871d0ab)

**Client (please complete the following information):**
 - OS: Windows 11
 - Version 3.0.3 (same error with 3.0.2 etc..)

**Additional context**
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crunchy-cli-core\src\utils\download.rs:742:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ByteDream** [comment]
Which ffmpeg version do you use? (to check execute `ffmpeg -hide_banner -version`)

**Comment by exus85** [comment]
ffmpeg version 6.0-full_build-www.gyan.dev

**Comment by ByteDream** [comment]
Okay mhh, I cannot reproduce this atm. Could you execute `ffmpeg -y -hide_banner -i <some video file>` on some video file you have and share the output?
This internally used ffmpeg command is the cause of the error, I want to see if it gives any unexpected output on your end

**Comment by ByteDream** [comment]
No, everything is there as expected, which makes the issue more even weirder. I can build a workaround which just defaults to a specific variable and does not let the program crash anymore if I can't make it reproducible with further testing

**Comment by exus85** [comment]
I think the cause of this error is my primary ISP connection.
I activated the verbose output and I saw that it was downloading the video chunks from http://prod.gccrunchyroll.com/.... and on the browser it's showing something related to google edge cloud
During the last days I experienced issues when using my primary connection (blocked connection with error 403 to various google services like cloud/domains). If I switch to my backup connection the download works fine.

**Comment by YewTreeWeb** [comment]
I am also getting this error when I try `crunchy-cli --credentials $login download -a en-US -r best -s en-US -o "{series_name}/Season {season_number}/{series_name}-S{season_number}E{episode_number}-{title}.mp4" https://www.crunchyroll.com/series/GQWH0M9N8/my-dress-up-darling` 

Unfortunately, I can't give a verbose output as whenever I try to pass verbose I get the error `unrecognized subcommand`

**Comment by YewTreeWeb** [comment]
Ok I've got verbose to work and I get the same with the video chunks coming from `from http://prod.gccrunchyroll.com/` I don't have a back-up connection to use sadly. This has relatively only just started to happen to me so it's odd

**Comment by YewTreeWeb** [comment]
I’m not a Rust developer, I’m a JS developer by trade so you will know much more than me but I found this just now. Thought it might be useful with potential solving the issue https://users.rust-lang.org/t/code-has-started-to-panic/101416

**Comment by bytedream** [comment]
Starting with [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0), it will show a proper error message. I can't do anything beyond that as it seems to be a local domain blocking issue
