### ISSUE TITLE
Split internals into a separate library

### ISSUE THREAD

**Issue by orowith2os** [crunchy-labs/crunchy-cli#259]
This project looks really interesting, and I would like to see if I can utilize bits of it to, say, make my own Crunchyroll client, such as for an HTPC. Would there be any interest on the crunchy-cli dev's side to split the internals, that manage the Crunchyroll API, into another library that one can use in their own projects?

**Comment by ByteDream** [comment]
The underlying api implementation is already present in a separate library, [crunchyroll-rs](https://github.com/crunchy-labs/crunchyroll-rs)
