### ISSUE TITLE
Feature: Generate autocompletion within executable

### ISSUE THREAD

**Issue by kennedy** [crunchy-labs/crunchy-cli#260]
**Is your feature request related to a problem? Please describe.**
Autocomplete requires downloading a separate collection to be installed.

**Describe the solution you'd like**
Having the executable generate the autocomplete would allow easy installation in shell configurations

```zsh
//.zshrc
eval "$(crunchy-cli completion zsh)"; compdef _op op
```

**Additional context**
This allows installs to go easier.

**Comment by kennedy** [comment]
Got this idea from a comment by a homebrew maintainer: https://github.com/Homebrew/homebrew-core/pull/152666#discussion_r1375304520

**Comment by ByteDream** [comment]
I've placed it outside of the main package to reduce the amount dependencies needed by the final binary, and because such a command would probably be executed only once, if at all.
