### ISSUE TITLE
Write to stdout without a TTY

### ISSUE THREAD

**Issue by jkrzefski** [crunchy-labs/crunchy-cli#265]
**Is your feature request related to a problem? Please describe.**

I am trying to embed crunchy-cli into a custom frontend that I am working on. When I execute the command from a PHP script, I cannot capture its stdout. stderr works fine. When I attach a TTY to the sub-process, it writes to stdout, but I cannot capture it programmatically. I tried to use a PTY, but it seems that is not supported on one of my target operating systems.

**Describe the solution you'd like**

Always write stdout, regardless of having a TTY.

**Comment by ByteDream** [comment]
The default output isn't well suited for this kind of application. The most output is hidden for non tty targets as the [indicatif](https://github.com/console-rs/indicatif) library, which handles almost all of the default output, doesn't really supports it.
I recommend using the `-v` flag instead (`crunchy-cli -v ...`). This will give you more information + in a more structured way than the default output

**Comment by jkrzefski** [comment]
Thanks you. This flag helps a lot.
