### ISSUE TITLE
AUR chunchy-cli-bin: failed to parse srcinfo

### ISSUE THREAD

**Issue by Nannk** [crunchy-labs/crunchy-cli#266]
**Describe the bug**
```
....
Aur (1) crunchy-cli-bin-3.1.0-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 (1/1) crunchy-cli-bin-3.1.0-1                       [--------------------------------------------------------------]
error: failed to parse srcinfo for 'crunchy-cli-bin-3.1.0-1': key 'sha256sums' requires a value: Line 18: sha256sums_x86_64 =
```

**To Reproduce**
Steps / command to reproduce the behavior:
```
paru -S crunchy-cli-bin
```

**Expected behavior**
package installed normally

**Client (please complete the following information):**
 - OS: Arch Linux x86_64 
 - Version: 3.1.0-1

**Additional context**
A problem with AUR packaging.

**Comment by ByteDream** [comment]
I've identified and fixed the bug in the ci pipeline. I don't have access to the AUR repo atm, I'll push the fix to the AUR when I'm back home

**Comment by Nannk** [comment]
Thank you

**Comment by ByteDream** [comment]
Update is now also available in the AUR

**Comment by Nannk** [comment]
It works now, 
Thank you.
