### ISSUE TITLE
Crunchy-cli or crunchyroll-go

### ISSUE THREAD

**Issue by Davidrsf** [crunchy-labs/crunchy-cli#267]
Hello, o see the post:

https://www.reddit.com/r/DataHoarder/comments/tkb6qc/crunchyrollgo_a_cli_to_download_episodes_or/

 as a windows user, is there any basic tutorial on how to use this method to download animes in crunchyroll?

thank you so much

**Comment by ByteDream** [comment]
`crunchyroll-go` got renamed to `crunchy-cli` a while ago. The still existing [crunchyroll-go](https://github.com/crunchy-labs/crunchyroll-go) repository is deprecated and all cli download capabilities have been removed from it.
For questions how to use it, please refer to our [discord server](https://discord.gg/PXGPGpQxgk), similar questions where already asked there (I know a wiki entry would be better for general questions than a discord server but I didn't had the motivation to create a wiki yet).
