### ISSUE TITLE
Implement hardsub without post-processing soft sub

### ISSUE THREAD

**Issue by OctoCharm** [crunchy-labs/crunchy-cli#268]
As we know, CR has two kinds of streams: a video with a soft sub (mostly used on browsers and mobile phones) and a video with a hard sub (mostly used on OTT [Android TV, Apple TV, Roku TV, Amazon Fire TV, Windows Apps]).

Using these current algorithms is not efficient and wasteful of computing resources.
1. Download the video track
2. Download the audio track
3. Download the subtitle
4. Remux all the tracks (video, audio, subtitle) using FFmpeg

Instead of directly downloading a hard subbed version from CR without performing any post-processing, such as rendering the soft sub into a hard sub.

![image](https://github.com/crunchy-labs/crunchy-cli/assets/54127572/b9854462-1849-4aae-9105-3d252142ee33)

**Comment by ByteDream** [comment]
We originally did this, but streams with hard-subbed episodes aren't always available (https://github.com/crunchy-labs/crunchy-cli/issues/81#issuecomment-1381687150).
To lower maintenance time, I've kicked them completely out in favor of manual burning. But I think this can be re-added with manual burning only necessary if the requested hardsubs doesn't already exist.

**Comment by OctoCharm** [comment]
Sure, it would be better to use manual burning (a.k.a post-processing hard-sub) as a fallback, not a primary one.

**Comment by ByteDream** [comment]
Implemented in [v3.1.1](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.1.1).
