### ISSUE TITLE
Show ffmpeg progress

### ISSUE THREAD

**Issue by Nannk** [crunchy-labs/crunchy-cli#270]
**Is your feature request related to a problem? Please describe.**
As av1 encoding on a cpu takes quite a long time, in my opinion, a progress indicator would be quite helpful.

**Describe the solution you'd like**
ffmpeg has an `-stats output` and `-progress output ` option. [source](https://manpages.org/ffmpeg)
One of the solutions is to use ffprobe before ffmpeg, grab the frame counter from `-progress output` and calcutate the progress in percent. [source](https://blog.programster.org/ffmpeg-output-progress-to-file).

There are also multiple wrappers available, most of them use js, python or php.
Bash implementation: https://github.com/zamanuhina/ffmpeg-progress

**Comment by bytedream** [comment]
Added in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0)
