### ISSUE TITLE
Random Data loss

### ISSUE THREAD

**Issue by Nannk** [crunchy-labs/crunchy-cli#271]
**Describe the bug**
Sometimes, the output video has a tail of it lost. The audio is still there, but the videoplayer is showing the last frame before corruption? and the filesize is quite low. Subtitles do not appear after that point either.

Redownloading the episode helps.

Ive encountered this bug at least 3 times already.

**To Reproduce**
Steps / command to reproduce the behavior:
I use alias to set up the default configuration:
```
alias crunchy-cli-archive="crunchy-cli archive --ffmpeg-preset av1-lossless --skip-existing -s de-DE -a ja-JP -o \"S{season_number}E{episode_number} {series_name} - {title}.mkv\""
```
then 
```
crunchy-cli-archive https://www.crunchyroll.com/series/GR49WNQE6/recovery-of-an-mmo-junkie
```

**Expected behavior**
Videos are not corrupted.

**Client (please complete the following information):**
 - OS:[fedora 39 and arch linux]
 - Version [3.1.1 (440ccd9 2023-11-20)]

**Comment by ByteDream** [comment]
Does the same happen when using no/another preset?

**Comment by Nannk** [comment]
I think it happened to once when i used no preset.

**Comment by Nannk** [comment]
It might be a connection issue, so ill close it for now and reopen if this happens again.

**Comment by Nannk** [comment]
I also have encountered this bug again.
```
ls -alh
total 26M
drwx------ 1 nannk nannk   0 Jan 10 19:44  .
drwx------ 1 nannk nannk   0 Jan 10 19:57  ..
-rwx------ 1 nannk nannk 26M Jan 10 19:44 'S01E01 Doctor Elise: The Royal Lady with the Lamp - Atonement.mkv'
```
Its not the internet connection, as i just got a new , really stable one today.

I have a nextcloud in local network mounted as dav. Im running the command directly in the destination folder. (set as wd in Terminal)
The command is the same.

**Comment by Nannk** [comment]
I got the bug again on ep 5 of Villainess Level 99.
here is the log:
https://0x0.st/Hknh.txt

**Comment by Frooastside** [comment]
got the same problem with https://www.crunchyroll.com/series/GVDHX8DM5/86-eighty-six S01E01 just downloaded 144MB

**Comment by RazerBlade07** [comment]
I got the same problem. If i download a season from any show some random episodes are corrupted. This is very annoying because I have to check every single episode for errors
