### ISSUE TITLE
Add forced flag to mkv subtitle tracks

### ISSUE THREAD

**Issue by p47-6** [crunchy-labs/crunchy-cli#274]
**Describe the solution you'd like**
Is it Possible to add the Forced flag to all (CC) subtitle tracks in the output mkv file ?

**Comment by ByteDream** [comment]
What would be the benefit of this?

**Comment by ByteDream** [comment]
You can set the forced flag for one subtitle stream by providing the `--default-subtitle` flag.
Applying the forced flag to every CC subtitle by default will likely cause some issues. For example, if the mkv file contains multiple CC subtitles in different languages, they may be shown above each other or a random CC subtitle of the available forced options is picked.

**Comment by p47-6** [comment]
I've mainly using PLEX as media library and have never seen that problem. I've also checked other media files just to be sure and there are definitly multiple ones marked as forced. Here is an example mkvinfo output:
```
| + Track
|  + Track number: 6 (track ID for mkvmerge & mkvextract: 5)
|  + Track UID: 8
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Forced display" flag: 1
|  + "Lacing" flag: 0
|  + Language: ger
|  + Codec ID: S_HDMV/PGS
|  + Language (IETF BCP 47): de
|  + Name: Deutsch Forced (PGS)
| + Track
|  + Track number: 7 (track ID for mkvmerge & mkvextract: 6)
|  + Track UID: 15178870140572590589
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Forced display" flag: 1
|  + "Lacing" flag: 0
|  + Language: ger
|  + Codec ID: S_VOBSUB
|  + Codec's private data: size 348
|  + Language (IETF BCP 47): de
|  + Name: Deutsch Forced (VobSub)
| + Track
|  + Track number: 8 (track ID for mkvmerge & mkvextract: 7)
|  + Track UID: 4939342997478923845
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Forced display" flag: 1
|  + "Lacing" flag: 0
|  + Language: ger
|  + Codec ID: S_TEXT/UTF8
|  + Language (IETF BCP 47): de
|  + Name: Deutsch Forced (SRT)
| + Track
|  + Track number: 9 (track ID for mkvmerge & mkvextract: 8)
|  + Track UID: 6
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Lacing" flag: 0
|  + Language: ger
|  + Codec ID: S_HDMV/PGS
|  + Language (IETF BCP 47): de
|  + Name: Deutsch SDH (PGS)
|  + "Hearing impaired" flag: 1
| + Track
|  + Track number: 10 (track ID for mkvmerge & mkvextract: 9)
|  + Track UID: 10260309544658459880
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Lacing" flag: 0
|  + Language: ger
|  + Codec ID: S_VOBSUB
|  + Codec's private data: size 348
|  + Language (IETF BCP 47): de
|  + Name: Deutsch SDH (VobSub)
|  + "Hearing impaired" flag: 1
| + Track
|  + Track number: 11 (track ID for mkvmerge & mkvextract: 10)
|  + Track UID: 10
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Lacing" flag: 0
|  + Codec ID: S_HDMV/PGS
|  + Language (IETF BCP 47): en
|  + Name: English SDH (PGS)
|  + "Hearing impaired" flag: 1
|  + "Original language" flag: 1
| + Track
|  + Track number: 12 (track ID for mkvmerge & mkvextract: 11)
|  + Track UID: 4621194038152181430
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Lacing" flag: 0
|  + Codec ID: S_VOBSUB
|  + Codec's private data: size 348
|  + Language (IETF BCP 47): en
|  + Name: English SDH (VobSub)
|  + "Hearing impaired" flag: 1
|  + "Original language" flag: 1
```

Could it be that you are mixing the forced with the default flag ?

**Comment by p47-6** [comment]
I've just verified with the mkv tech notes. They do no mention that it is not valid to have multiple forced subtitle tracks. Also there is an example for subtitle selection by the player: https://www.matroska.org/technical/notes.html#subtitle-selection
Here is the important bit:

> However, the case where the Portuguese audio track is selected has an important catch: a Forced track in Portuguese is present. This may contain translations of onscreen text from the video track, or of portions of the audio that are not translated (music, for instance). This means that even if the user’s preferences wouldn’t normally call for captions here, the Forced track should be selected nonetheless, rather than selecting no track at all. On the other hand, if the user’s preferences do call for captions, the non-Forced tracks should be preferred, as the Forced track will not contain captioning for the dialogue.

Also, as of my understanding the "default" flagged subtitle track should not have the forced flag on if it is not a "(CC)" subtitle.

**Comment by ByteDream** [comment]
Okay I see, my bad. Thanks for providing the sources/links.

**Comment by p47-6** [comment]
I've tested the ci/cd generated bin and it seems like it only tags the first added subtitle:
```
| + Track
|  + Track number: 5 (track ID for mkvmerge & mkvextract: 4)
|  + Track UID: 5
|  + "Lacing" flag: 0
|  + Name: German
|  + Language: de-DE
|  + "Default track" flag: 0
|  + "Forced display" flag: 1
|  + Codec ID: S_TEXT/ASS
|  + Track type: subtitles
|  + Codec's private data: size 1976
| + Track
|  + Track number: 6 (track ID for mkvmerge & mkvextract: 5)
|  + Track UID: 6
|  + "Lacing" flag: 0
|  + Name: German (CC)
|  + Language: de-DE
|  + "Default track" flag: 0
|  + Codec ID: S_TEXT/ASS
|  + Track type: subtitles
|  + Codec's private data: size 2510
| + Track
|  + Track number: 7 (track ID for mkvmerge & mkvextract: 6)
|  + Track UID: 7
|  + "Lacing" flag: 0
|  + Name: English (US)
|  + Language: en-US
|  + "Default track" flag: 0
|  + Codec ID: S_TEXT/ASS
|  + Track type: subtitles
|  + Codec's private data: size 3099
| + Track
|  + Track number: 8 (track ID for mkvmerge & mkvextract: 7)
|  + Track UID: 8
|  + "Lacing" flag: 0
|  + Name: English (US) (CC)
|  + Language: en-US
|  + "Default track" flag: 0
|  + Codec ID: S_TEXT/ASS
|  + Track type: subtitles
|  + Codec's private data: size 1260
```
I'm not a rust developer but if i read the code correctly wouldn't it be the easiest to add it directly while adding the subtitles somewhere around here: https://github.com/crunchy-labs/crunchy-cli/blob/8613ea80cc9bde3dccfcc1429823aea3cdcec484/crunchy-cli-core/src/utils/download.rs#L331C1-L347C10

**Comment by bytedream** [comment]
Added in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0)
