### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by ZenxKz** [crunchy-labs/crunchy-cli#275]
Can you share me api key(s) of Crunchyroll, please?
If possible please share me.

**Comment by ByteDream** [comment]
You generate an API key whenever you login into Crunchyroll. You can easily extract it from the browser cookies (`etp_rt` cookie). This key has the same permissions as your account has, so if you don't have a premium subscription you also don't have access to premium content.
If you're here to ask for a key generated by a premium account, I'm sorry to say that I won't do that, please consider subscribing to premium yourself.

**Comment by ZenxKz** [comment]
Very thanks for your reply, but I want to download the subtitles using api, I got etp_rt as you mentioned, but I don't know where to put it in 'https://www.crunchyroll.com/content/v2/cms/series/{content_id}/seasons'🥹
