### ISSUE TITLE
The fonts aren't appearing in the attachment section for subtitles within mkvtoolnix.

### ISSUE THREAD

**Issue by DKB0512** [crunchy-labs/crunchy-cli#277]
**Describe the bug**
Experiencing an issue with downloaded episodes that lack font attachments along with subtitles. Upon inspecting the output file in mkvtoolnix, the attachment section doesn't display the expected fonts or any attachments. In comparison, downloading the same episode via yt-dlp includes the necessary fonts. This problem persists across all files downloaded using crunchy-cli.

Note : Also want to ask what are these tags present in the final-output file? I can't find them on the yt-dlp downloaded file.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive  "https://www.crunchyroll.com/watch/G0DUND50X/our-breakup-story-the-experienced-you-and-the-inexperienced-me-break-up"
```

**Expected behavior**
The output file should contain all the fonts/attachments.

**Screenshots**
I am attaching two screenshot.
1) Crunchy-cli :
![image](https://github.com/crunchy-labs/crunchy-cli/assets/23116307/41838818-99b4-479c-a11b-3518a482d3dd)

2) Yt-DLP or Anidl/multi-downloader-nx : 
![image](https://github.com/crunchy-labs/crunchy-cli/assets/23116307/cbf2ec90-8536-44e0-a997-922e31e12d88)

3) Just wanna ask what are these tags in Crunchy-cli file : 
![image](https://github.com/crunchy-labs/crunchy-cli/assets/23116307/f80e27c0-19da-4c14-997a-22e11aebac47)

4) Yt-DLP or Anidl/multi-downloader-nx (for that tag comparison) : 
![image](https://github.com/crunchy-labs/crunchy-cli/assets/23116307/c724b23c-dabf-44d2-a27b-cf2f7426ceee)

**Client (please complete the following information):**
 - OS:  Windows
 - Version: crunchy-cli v3.1.1

**Additional context**
None. If you want more details, let me know

**Comment by bytedream** [comment]
There is/was no support for this in the first place. But thanks for opening this issue, I just added support for this, it will be available in the next release

**Comment by bytedream** [comment]
> Note : Also want to ask what are these tags present in the final-output file? I can't find them on the yt-dlp downloaded file.

I guess they are from ffmpeg and can't be turned off (at least I couldn't figure out how)

**Comment by bytedream** [comment]
Added in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0) with the `--include-fonts` flag
