### ISSUE TITLE
quite flag results in error

### ISSUE THREAD

**Issue by patrickwuerth** [crunchy-labs/crunchy-cli#281]
**Describe the bug**
Using the -q or --quite flag results in an error.

error: unexpected argument '-q' found

  tip: to pass '-q' as a value, use '-- -q'

Usage: crunchy-cli download [OPTIONS] <URLS>...

For more information, try '--help'.

**To Reproduce**
```
$ crunchy-cli download -q https://www.crunchyroll.com/series/...
```

**Client (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Version crunchy-cli 3.1.1

**Comment by ByteDream** [comment]
You have to place the flag before the subcommand
```shell
$ crunchy-cli -q download https://www.crunchyroll.com/series/...
```

---

This behavior will be changed in the next release (so that `-q` can be used after a subcommand, just as you tried)
