### ISSUE TITLE
Some titles doesn't download the subtitles

### ISSUE THREAD

**Issue by Dokman** [crunchy-labs/crunchy-cli#283]
**Describe the bug**
Some animes doesn't dowload the subtitles

**To Reproduce**
Steps / command to reproduce the behavior:

- Try to download with command below
- Not load the subtitles

```
$ crunchy-cli archive -s es-LA --default-subtitle es-LA -m audio -o "[CR] {series_name} - S{season_number}E{episode_number} [{resolution}].mkv" https://www.crunchyroll.com/es-es/series/G6VN7WW0R/girls-bravo
```

**Expected behavior**
Download with subtitles

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/2290904/6ed558c6-74fa-4654-b91a-a4cb6e730fa1)

**Client (please complete the following information):**
 - OS: Windows
 - Version 3.1.1

**Comment by bytedream** [comment]
Try again with `es-419` instead of `es-LA` for subtitles. I don't really know the difference but from what I can tell, they are both the languages codes for `Spanish (Latin America)`. Idk why Crunchyroll has both

**Comment by Dokman** [comment]
ok it's working why this happens?
