### ISSUE TITLE
Better renaming variables (for example "1920x1080" -> "1080p")

### ISSUE THREAD

**Issue by evilsh3ll** [crunchy-labs/crunchy-cli#284]
**Is your feature request related to a problem? Please describe.**
It's no easy to build a title with p2p formatting, so with dots for example **Serie.2001.720p.CR.WEB-DL.AAC.H.264-TAG**

**Describe the solution you'd like**
- Introduce the chance to fill all white spaces with a separator like a dot
- Make the resolution from 1920x1080 to **1080p**, only the height followed by "p"
- Add the year variable usable for the file name 

**Additional context**
n/a

**Comment by bytedream** [comment]
I added a few more options, `{release_year}`, `{release_month}`, `{release_day}`, `{width}` and `{height}`. I think the names are self-explanatory.
I won't add an option to replace the whitespace. This can be archived relatively easy with other programs (e.g. on linux: `mv $filename $(echo $filename | tr ' ' '.')`).

The additions will land in the next release

**Comment by bytedream** [comment]
Added in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0)
