### ISSUE TITLE
Remove track names like "Video #1" "Video #2"

### ISSUE THREAD

**Issue by evilsh3ll** [crunchy-labs/crunchy-cli#285]
**Is your feature request related to a problem? Please describe.**
Tracks have tag names like "Video #1" "Video #2", it's not very handy because you will need to remove them after the download to make the file more clean

**Describe the solution you'd like**
remove the track names (maybe without re-muxing so using a simple mkvproedit command `mkvpropedit <file-path> --edit info  --tags all:` you can remove all names for all tracks in the file)  

**Additional context**
n/a

**Comment by bytedream** [comment]
This is necessary to see which audio belongs to which video, if multiple video streams exist

**Comment by evilsh3ll** [comment]
Could it be removed after the mux?

**Comment by bytedream** [comment]
There are multiple video streams because in some languages the video length may differ between videos in different languages (because of restrictions, dub differences, ...)
