### ISSUE TITLE
Download Subtitle only 

### ISSUE THREAD

**Issue by W3bP3n** [crunchy-labs/crunchy-cli#287]
Hello, 

At first, i would like to say thank you for crunchy-cli. It is awesome. 
May i know its possible just download subtitle only?  

Sometimes I already have the video, just not the subtitles.
Would be great to save a lot of time if i can just download subtitle. 

Thank you.

**Comment by bytedream** [comment]
You can use the `search` command for this -> https://github.com/crunchy-labs/crunchy-cli/issues/244#issuecomment-1692262479
