### ISSUE TITLE
Episode filtering not working correctly for specific show.

### ISSUE THREAD

**Issue by Penthious** [crunchy-labs/crunchy-cli#290]
**Describe the bug**
When trying to download Darling in the Franxx using episode filtering its downloading episodes outside of the filter.

IE my filter should only download episodes 25 and up, but when I run the script it starts downloading episode 24

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli --etp-rt "xxxx" archive --skip-existing -a ja-JP -a en-US -r worst -o "{series_name}-_-{season_number}-_-{episode_number}-_-{title}.mkv" https://www.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[S1E25-]
```

**Expected behavior**
To not download any show

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/12500410/139cb628-2a30-4703-828a-6f26651526e7)

**Client (please complete the following information):**
 - OS: Windows
 - Version: crunchy-cli 3.1.1

**Additional context**

**Comment by bytedream** [comment]
Crunchyroll is internally mislabeling the episode number which crunchy-cli uses to filter the episodes. Crunchyroll has 3 different approaches to label episode numbers but no one has a 100% accuracy.
In your case, only the number which is intended to be shown to the user correctly says `E24`, all others, including the number crunchy-cli uses to filter episodes, are reporting that the episode is episode 25. I won't add a fix for this case, unless this happens for more series.
