### ISSUE TITLE
Archive skip existing improvment

### ISSUE THREAD

**Issue by patrickwuerth** [crunchy-labs/crunchy-cli#292]
**Background**
I run the following command on a list of URLs. That's where I add new shows and keep the existing once so that when I run it regularly to get the new episodes:

crunchy-cli -q --user-agent "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)" archive -a de-DE -a en-US -a ja-JP -s en-US -s de-DE --skip-existing --yes -t 32 -o "/mnt/loader/{series_name}/{series_name} - S{season_number}E{episode_number}.mkv" URL

I would like to have the episodes in EN, JP, and DE. Of course the newer episodes are only available in JP which gets downloaded. 

**Describe the solution you'd like**
It would be great if the --skip-existing flag or a new flag would not only check if the file exists but compare the audio and subtitle languages and re-downloads the episodes that have additional audio/subtitles. 

**Additional context**
This would help to run the crunchy-cli in a chron job to execute every x days to update the current shows.

**Comment by bytedream** [comment]
I added a new flag for this. You can read the details over at #325. It would be great to get some feedback on this (pre-built binaries are available [here](https://github.com/crunchy-labs/crunchy-cli/actions/runs/7742374482))
