### ISSUE TITLE
Open-ended Episode Filtering [S1E3-] Skipping Episodes < E# in Subsequent Seasons

### ISSUE THREAD

**Issue by mamanakis** [crunchy-labs/crunchy-cli#293]
**Describe the bug**
When using episode filtering [S1E3-] S1E1 and S1E2 are correctly skipped, but S2E1-E2 and S3E1-E2 and S25E1-E2 are incorrectly skipped. 

**To Reproduce**
Steps / command to reproduce the behavior:
crunchy-cli archive -a en-US -s en-US --default-subtitle en-US -o "{series_name} - s{season_number}e{episode_number} - {title}.mkv" (https://www.crunchyroll.com/series/GRJ0J828Y/kaguya-sama-love-is-war[S1E3-])

**Expected behavior**
Skip S1E1 and S1E2 and fetch all subsequent episodes including S2E1, S2E2, S3E1, S3E2, S25E1, S25E2, etc.

**Screenshots**
None

**Client (please complete the following information):**
 - OS: Windows
 - Version 3.1.1(crunchy-cli-v3.1.1-windows-x86_64)

**Additional context**
None

**Comment by bytedream** [comment]
Fixed in [v3.2.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.0)
