### ISSUE TITLE
Telegram integration

### ISSUE THREAD

**Issue by systemerror-codenotfound** [crunchy-labs/crunchy-cli#300]
This works perfectly, but it's a bit messy to access the cli and manually write the commands in order to download.
Also you ahve to be there in order to start the download with the cli command

So, i think that integrating this with a telegram bot can be a lot faster

You can have a telegram bot and at first start configure it with the needed parameters that each one needs, and store that as an alias on linux.
After that you only need to share the URL to the bot and it will automatically start to do his magic as the telegram bot will run the alias command + url

And the telegram bot should listen to the output and feed the user over telegram with the status of the download

**Comment by bytedream** [comment]
This is definitely out of scope, this rather sound like a idea for a separate project which acts as a bridge between telegram and the cli.
