### ISSUE TITLE
Ffmpeg Protocol not found (download & archive)

### ISSUE THREAD

**Issue by GarouTheDevil** [crunchy-labs/crunchy-cli#303]
Cammand : same use for archive 
crunchy-cli download -o "{series_name} S{season_number}E{episode_number} {title}.mkv" -r 1080p -t 100 -s en-US -a ja-JP https://www.crunchyroll.com/watch/GWDU8J729/mash-burnedead-and-the-divine-visionaries

Output :
:: MASHLE: MAGIC AND MUSCLES Season 2 (MASHLE: MAGIC AND MUSCLES The Divine Visionary Candidate Exam Arc)
::  1. Mash Burnedead and the Divine Visionaries » S02E13
:: Downloading Mash Burnedead and the Divine Visionaries to 'MASHLE: MAGIC AND MUSCLES S02E13 Mash Burnedead and the Divine Visionaries.mkv'
::  Episode: S02E13
::  Audio: ja-JP
::  Subtitles: en-US
::  Resolution: 1920x1080
::  FPS: 23.97

:: An error occurred: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/.crunchy-cli_yznTcp.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:23:40.00, start: 0.000000, bitrate: 7989 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 7986 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/.crunchy-cli_3PT4p6.m4a':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:23:40.05, start: 0.000000, bitrate: 131 kb/s
  Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Input #2, ass, from '/tmp/.crunchy-cli_hhm5DK.ass':
  Duration: N/A, bitrate: N/A
  Stream #2:0: Subtitle: ass
MASHLE: MAGIC AND MUSCLES S02E13 Mash Burnedead and the Divine Visionaries 1080p.mkv: Protocol not found

**Comment by bytedream** [comment]
The `:` sign in the file name confuses ffmpeg. I added a fix which will be available in the next release. Until then, you just can add a `./` to the output flag and it should work fine (e.g. `crunchy-cli ... -o "./{series_name} S{season_number}E{episode_number} {title}.mkv" ...`)

**Comment by GarouTheDevil** [comment]
> The `:` sign in the file name confuses ffmpeg. I added a fix which will be available in the next release. Until then, you just can add a `./` to the output flag and it should work fine (e.g. `crunchy-cli ... -o "./{series_name} S{season_number}E{episode_number} {title}.mkv" ...`)



> The `:` sign in the file name confuses ffmpeg. I added a fix which will be available in the next release. Until then, you just can add a `./` to the output flag and it should work fine (e.g. `crunchy-cli ... -o "./{series_name} S{season_number}E{episode_number} {title}.mkv" ...`)

Hmm thank you shall i close

**Comment by bytedream** [comment]
Fixed in [v3.2.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.2)
