### ISSUE TITLE
Crunchy-cli login issue invalid_client

### ISSUE THREAD

**Issue by GarouTheDevil** [crunchy-labs/crunchy-cli#304]
Cammand:
crunchy login --credentials nimpxxxxxx@gmail.com:John@xxxx

My email and password are correct 

Output :
:: invalid_client (auth.obtain_access_token.client_inactive) -  (https://www.crunchyroll.com/auth/v1/token)

**Comment by Kyuuso** [comment]
Got the same time ago

**Comment by Vamoelysian** [comment]
Same issue/error for me. Last worked fine on Sunday.

**Comment by westhecool** [comment]
I was also having this issue but I can confirm it's fixed with the latest comment.

**Comment by Vamoelysian** [comment]
Still giving me the same error, new to using CLI though, is there something I need to do to update it? Sorry for the movie query.

**Comment by bytedream** [comment]
Crunchyroll changed the credentials which are used to authenticate the login process. I've applied the changes in [v3.2.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.2) which should resolve all related issues.
