### ISSUE TITLE
Generating output file 0% - (--ffmpeg-preset ) - crunchy-cli-v3.2.2-windows-x86_64.exe

### ISSUE THREAD

**Issue by 4fpc** [crunchy-labs/crunchy-cli#305]
Generating output file 0% - (--ffmpeg-preset ) - crunchy-cli-v3.2.2-windows-x86_64.exe

Command:
crunchy-cli-v3.2.2.exe archive --ffmpeg-preset h265-nvidia  -o "{series_name} S{season_number}E{episode_number} {title}.mkv" https://www.crunchyroll.com/series/GZJH3D719/tsukimichi--moonlit-fantasy-[S02E01]

gets stuck, doesn't generate the file

**Comment by xCymylx** [comment]
### Same issue here. Command:
crunchy-cli-v3.2.2.exe archive -a ja-JP -s en-US --ffmpeg-preset h265-nvidia-lossless --skip-existing --yes --output ".\{series_name}\Season {season_number}\{series_name} - S{season_number}E{sequence_number} - {title}.mkv" https://www.crunchyroll.com/series/G649PJ0JY/blue-exorcist

:: Downloading video #1      1.43 GiB 105.45 MiB/s [##############################################################] 100%:: Downloading ja-JP audio  24.00 MiB  39.30 MiB/s [##############################################################] 100%:: Downloading subtitles    en-US
:: Generating output file   [-------------------------------------------------------------------------------------]   0%

### It hangs there for a moment. My GPU stays idle as well. Then an additional message:
:: An error occurred: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\username\AppData\Local\Temp\.crunchy-cli_nbQo2o.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:25:36.12, start: 0.000000, bitrate: 7987 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 7984 kb/s, 23.98 fps, 23.98 tbr, 90k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\username\AppData\Local\Temp\.crunchy-cli_IOspIG.m4a':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:25:36.17, start: 0.000000, bitrate: 131 kb/s
  Stream #1:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Input #2, ass, from 'C:\Users\username\AppData\Local\Temp\.crunchy-cli_aQUj3E.ass':
  Duration: N/A, bitrate: N/A
  Stream #2:0: Subtitle: ass
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))
  Stream #1:0 -> #0:1 (copy)
  Stream #2:0 -> #0:2 (ass (ssa) -> ass (ssa))
Press [q] to stop, [?] for help

It creates the mkv file but it appears to be empty.

**Comment by Kyuuso** [comment]
Comparing 3.1.1 which was the last working for me, with latest, it seems to be a flag added to ffmpeg which causes it to be stuck.

something among the lines of:
`-vstats_file \\.\C: …`

You can see it if you run it with -v option before the command archive or so.

Also happens on Windows 11, later the day I’ll put the correct flag which causes the issue here.

**Comment by bytedream** [comment]
Fixed in [v3.2.3](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.3)

**Comment by 4fpc** [comment]
@bytedream  in v3.2.3 Now it works, the video is generated, but ffmpeg progress is still not shown, from 0% it jumps to 100%.
A ".crunchy-cli_xxxxxx" file is generated within the folder where the video was saved and remains there after the process is complete, instead of being generated in the Temp folder and being deleted later.

**Comment by bytedream** [comment]
Aah I love Windows. Takes multiple hours and blue screens to get everything up and running a VM with more than enough resources, multiple GB to install a compiler toolchain, non-working pipes, ...; such a great fucking system 🙃

**Comment by Kyuuso** [comment]
![image](https://github.com/crunchy-labs/crunchy-cli/assets/12716750/96e92c10-e3c5-4c7e-97fc-dac747ddd957)
@bytedream seems to work 👍

**Comment by bytedream** [comment]
Fix landed in [v3.2.4](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.2.4)

**Comment by 4fpc** [comment]
@bytedream v3.2.4 Everything now working here too! Thanks!! You are amazing!!!
