### ISSUE TITLE
Compilation error on Alpine Linux

### ISSUE THREAD

**Issue by cimadure** [crunchy-labs/crunchy-cli#306]
**Describe the bug**
Unable to complete the compilation of the binary on Alpine Linux due to errors (mostly "`async` trait functions are not currently supported". Stop at `crunchy-cli-core` (lib) d
 
**To Reproduce**
Steps / command to reproduce the behavior:
```
$ export RUST_BACKTRACE=full
$ apk add git cargo pkgconfig openssl openssl-dev ffmpeg nano

$ git clone https://github.com/crunchy-labs/crunchy-cli
$ cd crunchy-cli
$ git checkout v3.2.2
$ cargo build --release
```

**Expected behavior**
A complete compilation

**Client (please complete the following information):**
 - OS: Alpine Linux
 - Version 3.19
 - running on ProxMox LXD [Linux crunchyroll 6.5.11-5-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-5 (2023-11-27T19:52Z) x86_64 Linux]
- rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0)
- cargo 1.72.1

**Additional context**

- Version 3.1.1 can compile
- **Note: the commit  https://github.com/crunchy-labs/crunchy-cli/commit/283a3802b22d556eade5b8fca6114025efc6f879 is the one where 'async-trait' library is no longer in use.** 

_Logging::_

error[E0706]: functions in traits cannot be declared `async`
  --> crunchy-cli-core/src/utils/filter.rs:80:5
   |
80 |     async fn finish(self, input: Vec<Self::T>) -> Result<Self::Output>;
   |     -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     `async` because of this
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait
   = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information

error[E0706]: functions in traits cannot be declared `async`
  --> crunchy-cli-core/src/lib.rs:31:5
   |
31 |     async fn execute(self, ctx: Context) -> Result<()>;
   |     -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     `async` because of this
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait
   = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information

error[E0658]: use of unstable library feature 'io_error_other'
  --> crunchy-cli-core/src/utils/rate_limit.rs:57:30
   |
57 |                     .map_err(io::Error::other)
   |                              ^^^^^^^^^^^^^^^^
   |
   = note: see issue #91946 <https://github.com/rust-lang/rust/issues/91946> for more information

Some errors have detailed explanations: E0658, E0706.
For more information about an error, try `rustc --explain E0658`.
error: could not compile `crunchy-cli-core` (lib) due to 31 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `crunchy-cli-core` (lib) due to 31 previous errors

**Comment by bytedream** [comment]
Your Rust version is too old. Please use at least Rust 1.75.0. You can use [rustup.rs](https://rustup.rs/) to manually install Rust.

**Comment by cimadure** [comment]
Thank you bytedream. It worked.

For information.I use 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
And probably use apk build-basen openssl-dev
export OPENSSL_INCLUDE_DIR=/usr/include
