### ISSUE TITLE
No login in Windows 10

### ISSUE THREAD

**Issue by OZocha** [crunchy-labs/crunchy-cli#307]
**Describe the bug**
usage not possible0
**To Reproduce**
Steps / command to reproduce the behavior:
crunchy-cli login [E-mail] [password]
$ crunchy ...
```

**Expected behavior**
login 

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Client (please complete the following information):**
 - OS: [Windows 10 5.120 (KB890830)]

**Additional context**
usage as described is not possible

crunchy-cli login email@mainproviger.com password123456789
Der Befehl "crunchy-cli" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.


i probably fucked something up

**Comment by Kyuuso** [comment]
@OZocha use it like the following, with credentials option
`crunchy-cli login --credentials "email:password"`

**Comment by OZocha** [comment]
After executing the provided crunchy-cli-v3.2.3-windows-x86_64.exe, the command "crunchy-cli" is neither found in cmd nor powershell.

**Comment by OZocha** [comment]
Issue can be closed, i forgot to open the right directory in cmd(I knew i botched something up myself).
