### ISSUE TITLE
Downloads freeze randomly

### ISSUE THREAD

**Issue by Penthious** [crunchy-labs/crunchy-cli#310]
**Describe the bug**
When running archive the downloads get stuck after some time. Currently downloading Boruto and it has froze a few times, downloaded 60 then froze, restarted downloaded 5 then froze, restarted downloaded 100 then froze. The last time I left it on all night where it got stuck to see maybe it'll panic out or continue downloading but it just stayed stuck at 94%. 

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli --etp-rt "" archive --skip-existing --skip-specials -a ja-JP -a en-US -r best https://www.crunchyroll.com/series/GR75Q020Y/boruto-naruto-next-generations[S1E113-]

```

**Expected behavior**
When downloading takes to long IE gets frozen or stuck would be nice to have it error out that way I can have a cron job rerun it where it last failed using the filter command: https://www.crunchyroll.com/series/GR75Q020Y/boruto-naruto-next-generations[S1Exxx-]

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/12500410/1cd2fc3f-5a59-4972-ae33-b6123cd741f6)

**Client (please complete the following information):**
 - OS: Ubuntu
 - Version 3.2.4

**Comment by Penthious** [comment]
Currently I have a Go script that I use to:
* read in yaml of shows I want to download
* exec the crunchy-cli for each show
* update and rename shows/episodes and move files for plex usage
* update yaml with current episode that I was able to download
I noticed my script would just freeze up on the download so thought it was my doing, tested running manually the command above and the same issue happens.

What would be nice to have is if it freezes up the download would retry or abort that way in my code it'll error out and I can handle that accordingly.

Right now I have to keep watch and once it freezes restart the script.

**Comment by Penthious** [comment]
One thing I noticed is when it does get stuck it's always at 94%

**Comment by bytedream** [comment]
I (re-)added a timeout for the download process in [v3.2.5](https://github.com/crunchy-labs/crunchy-cli/releases/edit/v3.2.5). If this issue is caused by a connection which gets never closes, it timeouts after 60 seconds and the program tries to re-request the timeouted url.
If this issue still exists for you in v3.2.5 (or later), please comment here
