### ISSUE TITLE
Including the {audio} in the file name causes a ffmpeg parameter unknown/error

### ISSUE THREAD

**Issue by kralverde** [crunchy-labs/crunchy-cli#318]
I believe the audio code (eg en-US) is not escaped so it reads -US as a parameter

**Comment by bytedream** [comment]
Please share the full command you've used and (error) output you got

**Comment by kralverde** [comment]
my bad, my known case takes a good while to process so I thought i could sneak this by. Ill re-download.

**Comment by kralverde** [comment]
I've boiled this down to a filesystem issue.
