### ISSUE TITLE
Can't download eps with "?" in the name

### ISSUE THREAD

**Issue by ToMattBan** [crunchy-labs/crunchy-cli#328]
**Describe the bug**
Here I am again with a similar problem hehe.
So, I'm trying to download some animes that in specific eps have a "?" in the title, and they are failing.

**To Reproduce**
I ran:
```
$ crunchy-cli archive -a ja-JP -a pt-BR -s pt-BR -m audio -o "./Animes/Hyouka/S{season_number} E{episode_number} - {title}.mkv" https://www.crunchyroll.com/series/G6P585256/[S1E18]
```

Which outputed:
```
:: Generating output file   [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0%:: An error occurred: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/.crunchy-cli_1YaAOj.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:25:42.04, start: 0.000000, bitrate: 7985 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 7982 kb/s, 23.98 fps, 23.98 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/.crunchy-cli_5SW6kD.m4a':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: iso5dashmsix
  Duration: 00:25:42.11, start: 0.000000, bitrate: 131 kb/s
  Stream #1:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Input #2, ass, from '/tmp/.crunchy-cli_gYI9Rn.ass':
  Duration: N/A, bitrate: N/A
  Stream #2:0: Subtitle: ass
/Animes/Hyouka/S01 E18 - Is the Mountain Range Clear?.mkv: Invalid argument

```

**Expected behavior**
The episode downloaded

**Screenshots**

**Client (please complete the following information):**
 - OS: Linux
 - Version 3.2.5 (6e01e9e 2024-01-14)

**Additional context**
All the other episodes downloaded with no problems. This happened in more than 1 show. The only thing they have in common is the "?" in the episode name

**Comment by kralverde** [comment]
the `--universal-output` option from the current master will likely fix this

**Comment by bytedream** [comment]
> @kralverde I'm not familiar with Rust or cargo, but I followed the Readme part about building it and I got this error when running `cargo build --release`:
> 
> error: Package `crunchy-cli v3.2.5 (/home/tomatt/Apps/Meus/crunchy-cli)` does not have feature `native-tls-crate`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

Strange issue, it still compiles fine on my (linux) system. But besides that, you can grab a pre-built binary from [the ci](https://github.com/crunchy-labs/crunchy-cli/actions/runs/7742232527) (at the bottom in the "Artifacts" section)

**Comment by ToMattBan** [comment]
@bytedream I tried to compile on my Debian 12. Didn't know what was wrong. 
But the --universal-ouput from the latest artifact helped me and it's working. Thank you
