### ISSUE TITLE
merge audio fails on archive

### ISSUE THREAD

**Issue by NightQuest** [crunchy-labs/crunchy-cli#348]
**Describe the bug**
When attempting to archive using merge mode audio, crunchy-cli instead produces the following error:
`An error occurred: invalid type: null, expected u32`

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli archive --merge audio https://www.crunchyroll.com/series/G6J0G49DR/tower-of-god
```

**Expected behavior**
it should not error, and instead download the specified content.

**Screenshots**
<img width="1070" alt="image" src="https://github.com/crunchy-labs/crunchy-cli/assets/129131/c54bf1ea-fb69-41ce-bb30-1b88c5bbd6a9">

**Client (please complete the following information):**
 - OS: macOS Senoma 14.3.1
 - Version: 3.3.0 (88a28e8 2024-03-10)

**Additional context**
This happens due to 56f0ed1795d971fb4342b9f0a66216e8af18fd6f, changing that to `None` provides a temporary workaround however. [command.patch](https://github.com/crunchy-labs/crunchy-cli/files/14551725/command.patch)

**Comment by bytedream** [comment]
Thanks for reporting. The issue originates from Crunchyroll (ONCE FCKING AGAIN) not delivering consistent api results. I fixed it in [v3.3.1](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.3.1)
