### ISSUE TITLE
Season not available with other audio than ja-JP

### ISSUE THREAD

**Issue by JorgeLNJunior** [crunchy-labs/crunchy-cli#353]
**Describe the bug**
When attempting to archive a season including other audios than ja-JP, chrunchy-cli exits with the message `Season X is not available with "language" audio`

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy-cli --anonymous archive --lang pt-BR -a pt-BR -s pt-BR "https://www.crunchyroll.com/series/GVDHX8QNW/chainsaw-man"
```

**Expected behavior**
It should download with selected audio tracks.

**Screenshots**
![image](https://github.com/crunchy-labs/crunchy-cli/assets/46247451/83399cb6-30d5-438f-a7ce-5f0681170970)

**Client (please complete the following information):**
 - OS: Manjaro KDE 23
 - Version 3.3.1 (26a858c 2024-03-10)

**Additional context**
I've tried with other audio languages too.

**Comment by dok1100** [comment]
You can use the download command instead of archive.
t's just an mp4 instead of mkv

**Comment by westhecool** [comment]
I was actually just about to open a issue about this. It seems that crunchyroll's API is incorrectly reporting always that the only language available for the series is "ja-JP". However if you query the episode list from the API you'll see that that's not the case. It's only being falsely reported in the series information.

**Comment by bytedream** [comment]
It works when removing the `--anonymous` flag (and using a premium account)
