### ISSUE TITLE
URL could not be parsed

### ISSUE THREAD

**Issue by 1nfiniteZest** [crunchy-labs/crunchy-cli#367]
I have been trying to download season 8 of One Piece in english but keep getting this error. I am able to download episodes individually though.
<img width="755" alt="Screenshot 2024-04-05 at 11 25 27 PM" src="https://github.com/crunchy-labs/crunchy-cli/assets/104391262/a6d6191f-86f4-4129-912c-73a92f869f89">

**Comment by DanielPfe** [comment]
The readme tells you how
`https://www.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[E1-E5]`
So try this
`...one-piece[S8]`

**Comment by bytedream** [comment]
As @DanielPfe said, your syntax is wrong, you'd have to use `https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece[S8]` as url

**Comment by 1nfiniteZest** [comment]
<img width="555" alt="Screenshot 2024-04-06 at 8 36 43 AM" src="https://github.com/crunchy-labs/crunchy-cli/assets/104391262/bc5f7fb7-1417-4f3a-9c92-33cfa5b33fc5">
Thats what i thought, but I keep getting this...

**Comment by gamer191** [comment]
Try putting the URL in quotation marks

**Comment by 1nfiniteZest** [comment]
> Try putting the URL in quotation marks

THANK YOU! You're amazing!
