### ISSUE TITLE
Batch File

### ISSUE THREAD

**Issue by Fu2chN** [crunchy-labs/crunchy-cli#396]
**Is your feature request related to a problem? Please describe.**
A setting to batch a file containing urls to download.

**Describe the solution you'd like**
Same as yt-dlp "-a, --batch-file FILE" proposes.

```$ crunchy-cli -b --batch-file FILE```

**Comment by bytedream** [comment]
Multiple URLs as input are supported. So you can simply pipe the file input in

E.g. on Linux:
```shell
$ crunchy-cli download $(cat urls.txt)
```
On Windows there probably is an equivalent

**Comment by Fu2chN** [comment]
> Multiple URLs as input are supported. So you can simply pipe the file input in
> 
> E.g. on Linux:
> 
> ```shell
> $ crunchy-cli download $(cat urls.txt)
> ```
> 
> On Windows there probably is an equivalent

Ok, I haven't tried that, I'm going to try it on Windows tomorrow.
