### ISSUE TITLE
Login error 

### ISSUE THREAD

**Issue by 2204852** [crunchy-labs/crunchy-cli#399]
dlc archive -a hi-IN -s all -r 720p -o "{series_name} S{season_number}E{episode_number} - {title} [{height}p] [{audio}].mkv" -t 20 -m audio --include-fonts --skip-existing --skip-specials -y https://www.crunchyroll.com/watch/G14U4GJ95/mash-burnedead-and-the-body-of-the-gods
:: ✔ Logging in                                                                 :: Please use a login method ('--credentials', '--etp-rt' or '--anonymous')

**Comment by bytedream** [comment]
You have to login to use the tool https://github.com/crunchy-labs/crunchy-cli?tab=readme-ov-file#global-flags. Please use the issue template the next time

**Comment by 2204852** [comment]
> You have to login to use the tool https://github.com/crunchy-labs/crunchy-cli?tab=readme-ov-file#global-flags. Please use the issue template or discussions the next time

I'm using this tool on Google colab yesterday it working but now its not working

**Comment by 2204852** [comment]
> You have to login to use the tool https://github.com/crunchy-labs/crunchy-cli?tab=readme-ov-file#global-flags. Please use the issue template or discussions the next time

Thanks but sorry for the trouble I'm using wrong virsion 😅
