### ISSUE TITLE
Retrieve stream by guid not by slug title

### ISSUE THREAD

**Issue by hazy-kun** [crunchy-labs/crunchy-cli#400]
**Is your feature request related to a problem? Please describe.**
Sometimes episodes don't have slug title, in this case the downloader crashes 'cause slug title is missing

**Describe the solution you'd like**
Use fixed endpoint to retrieve series, seasons and episodes data using only the guid.

**Comment by bytedream** [comment]
The receiving is done by guid. Episodes with empty slug titles also work, from what I saw on the Crunchyroll website, a url is always represented as `https://www.crunchyroll.com/watch/<guid>/<slug>`. The url works fine if the `<slug>` part is removed (`https://www.crunchyroll.com/watch/<guid>/`). Only when the last slash is missing (`https://www.crunchyroll.com/watch/<guid>`), the url can't be parsed.
But yea I can extend support for urls without a slug and trailing slash
