### ISSUE TITLE
3.6.0 - ass subtitles

### ISSUE THREAD

**Issue by dok1100** [crunchy-labs/crunchy-cli#403]
With version 3.6.0 all ass subtitles are underlined and crossed out.
Version 3.5.2 works

It seems that -1 become 0 and 0 becomes -1 in the styles (Bold, Italic, Underline, Strikeout) after the last Hexedecimal color value. 
I marked the default style so that it might be seen better,
and there is an **s** in ScaledBorderAndShadow which is not right.

**Comment by bytedream** [comment]
Duplicate of #402. Issue is know, I've already created a fix and just wait for it to be merged https://github.com/adracea/rsubs-lib/pull/45

**Comment by dok1100** [comment]
Ups sorry... I didn't see the other post
