### ISSUE TITLE
3.6.1 invalid_client or invalid_grant

### ISSUE THREAD

**Issue by transmatrix** [crunchy-labs/crunchy-cli#404]
Trying to login/authenticate with crunchy-cli latest. If I call via crunchy-cli, I get an invalid_client error. If I try using the full executable name, I get an invalid_grant error. Both have the same sub-message:
```
:: √ Logging in
:: invalid_grant - auth.obtain_access_token.invalid_credentials (https://www.crunchyroll.com/auth/v1/token)
```

**Comment by bytedream** [comment]
Did you use the [correct syntax](https://github.com/crunchy-labs/crunchy-cli#user-content-global-credentials) and your correct credentials?

**Comment by transmatrix** [comment]
So, issue is that I have to call the full exe name when connecting (realized I had a copy-paste mistake with my last attempt to connect via this method.) So, crunchy-cli login doesn't work, I have to do crunch-cli-v3.6.1-windows-x86_64.exe login to authenticate and then I can do the subsequent calls using just crunchy-cli. So, I have a work-around.

**Comment by transmatrix** [comment]
Actually, I'm having to call the full name of the exe for each call with this version. Not sure what changed. Otherwise I get the invalid_client error. Is there a way to see which exe is being called when you run the crunchy-cli command? Wondering if I have an old version somewhere in my System Path.

**Comment by bytedream** [comment]
> Is there a way to see which exe is being called when you run the crunchy-cli command

You can use the `--version` flag the get the version. If the version is below 3.5.0 this is probably the cause, they do not work anymore (#382)

**Comment by transmatrix** [comment]
Yeah, it's using 3.2.5 when I do just crunch-cli. I know at one point I was trying to "install" this software by putting it in my path. Now I just need to find the damn thing.

**Comment by transmatrix** [comment]
Just learned of the where command:

`c:\>where crunchy-cli`

**Comment by transmatrix** [comment]
Okay, found out my issue: at one point I installed via scoop but then I forgot and started replacing the executable.

**Comment by Frooastside** [comment]
just as a tip, you could use `where.exe crunchy-cli` so it also works on powershell
