### ISSUE TITLE
Download archive command not updating files

### ISSUE THREAD

**Issue by patrickwuerth** [crunchy-labs/crunchy-cli#418]
**Describe the bug**
I run Ubuntu 20.04 LTS and my command is the following:
crunchy-cli --user-agent "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)" archive --skip-existing-method audio -a de-DE -a en-US -a ja-JP -s en-US -s de-DE --yes -t 32 -o "/home/patrick/Anime/{series_name}/{series_name} - S{season_number}E{episode_number}.mkv" https://www.crunchyroll.com/series/GYQ4MW246/naruto-shippuden

When this runs, it will ignore any existing files and create doubles like:
Downloading Homecoming to '/home/patrick/Anime/Naruto Shippuden/Naruto Shippuden - S01E01 **(1)**.mkv'

If I run the command again it will create :
Downloading Homecoming to '/home/patrick/Anime/Naruto Shippuden/Naruto Shippuden - S01E01 **(2)**.mkv'

I am not sure why this happens. I am running the newest version:  crunchy-cli v3.6.1

**Expected behavior**
I would expect the --skip-existing-method audio to update/skip based on the audio difference and not create a new file each time it runs.

**Comment by Frooastside** [comment]
Im not quite sure but have you tried to also set the `--skip-existing` as addition to the `--skip-existing-method audio`?

**Comment by patrickwuerth** [comment]
That seems to work even though according to the documentation it is not required :). I ran into an error with this command:
crunchy-cli --user-agent "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)" archive --skip-existing --skip-existing-method audio -a de-DE -a en-US -a ja-JP -s en-US -s de-DE --yes -t 32 -o "/mnt/loader/Anime/{series_name}/{series_name} - S{season_number}E{episode_number}.mkv" https://www.crunchyroll.com/series/G4PH0WXVJ/spy-x-family

Resulting in the following error:
:: Downloading Berlint in Love / Nightfall's Daily Life to '/mnt/loader/Anime/SPY x FAMILY/SPY x FAMILY - S02E36.mkv'
::      Episode: S02E36
::      Audio: de-DE, en-US, ja-JP
::      Subtitles: de-DE, en-US
::      Resolution: 1920x1080
::      FPS: 23.97
:: Downloading de-DE audio  22.19 MiB  18.50 MiB/s 
100%:: Downloading en-US audio  22.19 MiB  20.90 MiB/s 
100%:: Downloading ja-JP audio  22.19 MiB  21.84 MiB/s 
100%:: Downloading video #1      1.32 GiB  67.96 MiB/s 
100%:: Downloading subtitles    en-US (CC), en-US (CC) /
                                                                                                                                                                                                                           thread 'main' panicked at /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/rsubs-lib-0.2.1/src/vtt.rs:601:63:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The previous 2 episodes worked without a problem. Is that a problem from my side or should I report a new bug ?

**Comment by Frooastside** [comment]
this issue is related to #408 and #416

**Comment by bytedream** [comment]
I've added a warning message in [v3.6.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.6.2) which makes a bit clearer that `--skip-existing` is required too.

> though according to the documentation it is not required

Is this the part you mean?
![image](https://github.com/crunchy-labs/crunchy-cli/assets/63594396/bf3bcece-adad-4452-aab8-1671ae31bbaf)
