### ISSUE TITLE
Output Template Options remove special characters

### ISSUE THREAD

**Issue by patrickwuerth** [crunchy-labs/crunchy-cli#419]
**Is your feature request related to a problem? Please describe.**
I use the following command:
crunchy-cli --user-agent "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)" archive --skip-existing --skip-existing-method audio --skip-existing-method subtitle -a de-DE -a en-US -a ja-JP -s en-US -s de-DE --yes -t 32 -o "/mnt/Anime/{series_name}/{series_name} - S{season_number}E{episode_number}.mkv" $(cat links.txt)

The problem I run into is that some {series_name} have special characters in them like :,? which cannot be used in a windows file system. Since I run this on a ubuntu 20.04 it works but my windows system has trouble viewing that from my network drive.

**Describe the solution you'd like**
Would it be possible to have a flag --remove-special-characters that would just remove/skip those when referring to:
{title} → Title of the video
{series_name} → Name of the series
{season_name} → Name of the season

**Additional context**
For testing, I had problems with the following:
WorldEnd: What do you do at the end of the world? Are you busy? Will you save us
Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs
Demon Slayer: Kimetsu no Yaiba

**Comment by bytedream** [comment]
The [`--universal-output`](https://github.com/crunchy-labs/crunchy-cli#user-content-download-universal-output) flag for this
