### ISSUE TITLE
 error at line 7: Parse("invalid float literal")

### ISSUE THREAD

**Issue by BattouKen** [crunchy-labs/crunchy-cli#427]
**Describe the bug**
An error occurred: error at line 7: Parse("invalid float literal")

**To Reproduce**
Steps / command to reproduce the behavior:
```
crunchy-cli archive -a ja-JP https://www.crunchyroll.com/es/watch/GK9U38KZD
```

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: win 10 64 home single lang
 - Version 3.6.5 last version with scoop

**Additional context**
![Windows PowerShell 22-05-2024 13_00_36](https://github.com/crunchy-labs/crunchy-cli/assets/81390696/12a00659-86d7-4a3f-8b31-868482f4ea4e)

**Comment by bytedream** [comment]
Thanks for reporting, got fixed in [v3.6.6](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.6.6)
