### ISSUE TITLE
Switch endpoint is now DRM encrypted

### ISSUE THREAD

**Issue by hajimekun** [crunchy-labs/crunchy-cli#439]
**Describe the bug**
Not properly a bug, the streams now available on the /console endpoint is now DRM encryped

**To Reproduce**
Download a video or audio and enjoy beautiful rainbow flashes

**Client (please complete the following information):**
 - OS: Windows
 - Version: crunchy-cli 3.6.6

**Additional context**
The problem is that program not support self-providing a wvd so now is unusable

**Comment by bytedream** [comment]
Duplicate of #438

**Comment by bytedream** [comment]
@hajimekun I'm sorry for changing the title/text, I thought OMA was a type. Apparently not, I just never heard of it
