### ISSUE TITLE
Undetected Spanish Dub

### ISSUE THREAD

**Issue by MauroS5** [crunchy-labs/crunchy-cli#44]
Totally not downloading es-419 (Spanish Dub) south american dub I think.
Happend with Love of Kill and DARLING in the FRANXX for example

Command used: crunchy archive  -l all -m auto -r best https://beta.crunchyroll.com/series/G0XHWM0XW/love-of-kill

![image](https://user-images.githubusercontent.com/52974793/185807962-0fee071f-158e-45b0-85cb-103d7c459965.png)

When download finish

![image](https://user-images.githubusercontent.com/52974793/185807984-d4ee28bf-601a-4093-89b6-09be10e366d4.png)

On page: 

![image](https://user-images.githubusercontent.com/52974793/185808155-d32c456a-5398-441d-81d6-55e4e239c36b.png)

**Comment by ByteDream** [comment]
Crunchyroll recently added or began using another spanish locale (`es-LA`). as far as I can see ... . Looking forward to fix / add it

**Comment by ByteDream** [comment]
Fixed in [v2.3.0](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v2.3.0).
