### ISSUE TITLE
Corrupted Windows Binary for Release 2.3.0

### ISSUE THREAD

**Issue by mkstephenson** [crunchy-labs/crunchy-cli#46]
**Describe the bug**
When attempting to run the binary for release 2.3.0, I get the error message that "The file or directory is corrupted and unreadable".

**To Reproduce**
Steps / command to reproduce the behavior:
- Download Windows binary from Github release for 2.3.0.
- Attempt to run (in the console or by double clicking, they both produce the same result).

**Client (please complete the following information):**
 - OS: Windows 10 x64
 - Version 2.3.0

**Comment by ByteDream** [comment]
Thanks for bringing this to my attention. The latest release added some platform specific code and due to this change, the binary must now be compiled on the target system (which was not required before).
I've replaced the binary with a working version.
