### ISSUE TITLE
[Request] Improve the Archive option

### ISSUE THREAD

**Issue by ErezZM** [crunchy-labs/crunchy-cli#49]
Hi,
I'm using the Archive option and it works perfectly,
But it isn't sorted well.

Can you make the Archive split dubs into different folders?

like:

EnglishDub/Ep1,Ep2,etc...
JapaneseDub/Ep1,Ep2,etc...
Spanish/Ep1,Ep2,etc...
etc/Ep1,Ep2,etc...

And i want the files be calling like:
One Piece Season 1 Episode 3
One Piece Season 3 Episode 23
etc...

How can i do that? how can i get the value of the episode number and use it as output?
Thanks :)

**Comment by ByteDream** [comment]
The different folder option might be a feature for a future release (when this project enters a state of active development again). But you can achieve something similar if you specify some flags. `crunchy archive -l en-US -d EnglishDub <url>` would download only episodes with english audio into the `EnglishDub` folder, `crunchy archive -l ja-JP -d JapaneseDub <url>` would download only episodes with japanese audio into the `JapaneseDub` folder, and so on.. .

Formatting the name of the output file can be done via the `-o` flag. The [wiki](https://github.com/crunchy-labs/crunchy-cli/wiki/Cli#format) has a section about it.

**Comment by 0xB00B** [comment]
@ByteDream i am facing an issue with archive option. i would like to have both Japanese and English audio tracks but its only saving japanese according to ffprobe.

### crunchy-cli command :
```
crunchy-cli archive -r 1080p -l ja-JP -l en-US -s en-US -d "video/{series_name} ({resolution})/S{season_number} - {season_name}" -o "E{episode_number} - {title}.mkv" https://www.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[E9]
```

### ffprobe ouput :
```
Input #0, matroska,webm, from 'video/DARLING in the FRANXX (1920x1080)/S01 - DARLING in the FRANXX/E09 - Triangle Bomb.mkv':
  Metadata:
    ENCODER         : Lavf57.83.100
  Duration: 00:24:00.10, start: 0.000000, bitrate: 8123 kb/s
    Stream #0:0(ja-JP): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : Japanese
      DURATION        : 00:24:00.063000000
    Stream #0:1(ja-JP): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Japanese
      DURATION        : 00:24:00.101000000
    Stream #0:2(en-US): Subtitle: ass
    Metadata:
      title           : English (US)
      DURATION        : 00:22:50.010000000
```

where is the english audio stream ?

**Comment by ByteDream** [comment]
Maybe the english version is not available in your country?
If I download it with your command (I've just reduced the video quality; my internet is currently a bit slow) the english audio is there.

```
Input #0, matroska,webm, from 'DARLING in the FRANXX (428x240)/S01 - DARLING in the FRANXX/E09 - Triangle Bomb.mkv':
  Metadata:
    ENCODER         : Lavf59.27.100
  Duration: 00:24:03.15, start: 0.000000, bitrate: 1129 kb/s
  Stream #0:0(ja-JP): Video: h264 (Constrained Baseline), yuv420p(progressive), 428x240 [SAR 320:321 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn
    Metadata:
      title           : Japanese
      DURATION        : 00:24:00.063000000
  Stream #0:1(ja-JP): Audio: aac (LC), 22050 Hz, stereo, fltp
    Metadata:
      title           : Japanese
      DURATION        : 00:24:00.194000000
  Stream #0:2(en-US): Video: h264 (Constrained Baseline), yuv420p(progressive), 428x240 [SAR 320:321 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn
    Metadata:
      title           : English (US)
      DURATION        : 00:24:03.117000000
  Stream #0:3(en-US): Audio: aac (LC), 22050 Hz, mono, fltp
    Metadata:
      title           : English (US)
      DURATION        : 00:24:03.149000000
  Stream #0:4(en-US): Subtitle: ass
    MetadataInput #0, matroska,webm, from 'DARLING in the FRANXX (428x240)/S01 - DARLING in the FRANXX/E09 - Triangle Bomb.mkv':
  Metadata:
    ENCODER         : Lavf59.27.100
  Duration: 00:24:03.15, start: 0.000000, bitrate: 1129 kb/s
  Stream #0:0(ja-JP): Video: h264 (Constrained Baseline), yuv420p(progressive), 428x240 [SAR 320:321 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn
    Metadata:
      title           : Japanese
      DURATION        : 00:24:00.063000000
  Stream #0:1(ja-JP): Audio: aac (LC), 22050 Hz, stereo, fltp
    Metadata:
      title           : Japanese
      DURATION        : 00:24:00.194000000
  Stream #0:2(en-US): Video: h264 (Constrained Baseline), yuv420p(progressive), 428x240 [SAR 320:321 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn
    Metadata:
      title           : English (US)
      DURATION        : 00:24:03.117000000
  Stream #0:3(en-US): Audio: aac (LC), 22050 Hz, mono, fltp
    Metadata:
      title           : English (US)
      DURATION        : 00:24:03.149000000
  Stream #0:4(en-US): Subtitle: ass
    Metadata:
      title           : English (US)
      DURATION        : 00:22:50.010000000:
      title           : English (US)
      DURATION        : 00:22:50.010000000
```

**Comment by ByteDream** [comment]
> Hi, I'm using the Archive option and it works perfectly, But it isn't sorted well.
> 
> Can you make the Archive split dubs into different folders?
> 
> like:
> 
> EnglishDub/Ep1,Ep2,etc... JapaneseDub/Ep1,Ep2,etc... Spanish/Ep1,Ep2,etc... etc/Ep1,Ep2,etc...
> 
> And i want the files be calling like: One Piece Season 1 Episode 3 One Piece Season 3 Episode 23 etc...
> 
> How can i do that? how can i get the value of the episode number and use it as output? Thanks :)

This is out of scope. Such special needs shouldn't be handled in the cli itself but rather in a separate script.
