### ISSUE TITLE
[Bug] (-l all -m audio) adding the English Dub when it isn't matching

### ISSUE THREAD

**Issue by ErezZM** [crunchy-labs/crunchy-cli#51]
-m audio - adds only English Dubs even when it isn't match.
Others are ignored, only English always added.

I've tried using this command:
app.exe archive --resolution best -l all -m audio --directory "Season {season_number}" --output "{series_name} [S{season_number}E{episode_number}] - {title} - [{resolution}][{audio}][{subtitle}].mkv" %stream%

and tried on Classroom of the Elite.
https://beta.crunchyroll.com/series/GRVN8MNQY

**Comment by ErezZM** [comment]
It adds all of the matching ones, and English, which isn't match.

**Comment by ByteDream** [comment]
What exactly are you trying to do?

**Comment by ErezZM** [comment]
I'm trying to make a video with multiple dubs.
When i'm choosing to merge the audio,
It says which dubs accurite to the jp video,
And merge them together.
The only problem is that it isn't detect that the English dub has different video, and it isn't accurate to the jp video source.

**Comment by ByteDream** [comment]
You have to remove the `-m audio` flag. It forces crunchy-cli to download just a single video (in this case, the japanese) and for all other dubs, store only their audio. You have to remove it if you want matching english video and dubs.
There is also a tiny [wiki](https://github.com/crunchy-labs/crunchy-cli/wiki/Cli#archive) section about this issue (down at `Archive`, before the flag table).

**Comment by ErezZM** [comment]
Oh, okay.
So it doesn't check if dubs is the same length as the jp-video?

And i have another request, can you add an option to download and mux fonts?
Because when, for example, you are download an Arabic Subtitles, it uses a font that Crunchyroll sends to the client.

**Comment by ErezZM** [comment]
Oh, and Crunchyroll tagged wrong the first season, they call it "S2 - Platinum End",
when i do try to use "-m audio" it isn't merge, i think because you programmed it to find dubs by season number.
I don't know what is going on Crunchyroll...
