### ISSUE TITLE
[Bug] -l all - After downloading the Japanese Dub, it's merging without using -m auto

### ISSUE THREAD

**Issue by ErezZM** [crunchy-labs/crunchy-cli#52]
app.exe archive --resolution best -l all --directory "Season {season_number} ({audio})" --output "{series_name} [S{season_number}E{episode_number}] - {title} - [{resolution}].mkv" %stream%

I've used this command,
And when it's done downloading the Japanese dub, it's continue to German dub, and the German gets merge
with all of the videos available for the series and all of the audios, without using -m audio/video option.

**Comment by ErezZM** [comment]
Tried for Platinum End,
https://beta.crunchyroll.com/series/G8DHV722J

**Comment by ByteDream** [comment]
`-m auto` is activated by default. It is the smart alternative to manually using `-m audio` or `-m video`. If all videos in the different languages have the same length, it downloads the japanese video and only the audio for all other languages. If some videos differ in their length, it also merges every video of the different language into the mkv file.
So it merges the german video because it probably has a different length than the japanese one.

**Comment by ErezZM** [comment]
Oh, and Crunchyroll tagged wrong the first season, they call it "S2 - Platinum End",
when i do try to use "-m audio" it isn't merge, i think because you programmed it to find dubs by season number.
I don't know what is going on Crunchyroll...

**Comment by ErezZM** [comment]
And how can i disable -m auto?
And it isn't that smart to make it default, because some dubs have different signs as subtitles...

**Comment by ByteDream** [comment]
> I don't know what is going on Crunchyroll...

me neither.

> And it isn't that smart to make it default, because some dubs have different signs as subtitles...

what to you mean by signs?

**Comment by ErezZM** [comment]
I mean, for example, on English Dub, there is subtitles without subs, only types, like a sign translated to english from japanese.

**Comment by ByteDream** [comment]
It should be possible to turn off the subtitles, this would be the only option. I think a lot is messed up because crunchyroll flagged the stream which contains all normal subtitles as second season ...

**Comment by ErezZM** [comment]
So, can you make an option to disable -m?

**Comment by ByteDream** [comment]
`-m` is essential, the command could not work as it should without it. You can use `-l` / `--language` to control which audio should be included in the mkv and `-s` / `--sublang` which subtitles should be included. `-m` is only required if you want to include multiple audio tracks (like you do in your command). In this case, crunchy-cli must know how it should handle videos which have different length.
