### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by ErezZM** [crunchy-labs/crunchy-cli#53]
Make an option to Disable --merge auto default.

I just want to download series without merging them with different audios and videos.

app.exe archive %stream% -l all -r best -d "{series_name}\Season {season_number}\{audio}" -o "{series_name} [S{season_number}E{episode_number}] - {title} - [{resolution}].mkv"

This is the command i'm using.
As a result, it gives my Episode with a few videos and a few audios.
I just want it to download Episode 1 [Japanese].mkv, Episode 1 [English].mkv, etc...

**Comment by ByteDream** [comment]
This could be an option for a future release, but I cannot say when that will be.
For the moment you could write yourself a script which does what you requested.

**Comment by ErezZM** [comment]
I've tried to run the command with different language every time with a batch file, but when i'm trying to download an invalid language, which doesn't exist, it's start downloading the japanese and thinks it's downloading the invalid one and stops at episode 10 and just close.

**Comment by ByteDream** [comment]
The same as in #49 applies.
