### ISSUE TITLE
Filter by Season name

### ISSUE THREAD

**Issue by BlastBolt5** [crunchy-labs/crunchy-cli#55]
Would it be possible to add a feature where you can set a filter by season name, atm having an issue where S3 and S4 are labeled S3 but have different names so it won't grab all the episodes

**Comment by ByteDream** [comment]
Which series do you mean and what was the command you've used?

**Comment by BlastBolt5** [comment]
Sword art online 

> crunchy-cli archive -r best -g 2 -d "Sword Art Online" -o "{series_name} - S{season_number}E{episode_number} - {title}.mkv" https://beta.crunchyroll.com/series/GR49G9VP6/sword-art-online

**Comment by ByteDream** [comment]
A temporary fix for this would be to download each episode on its own. I'll look into it to fix the problem but this might take a while.

**Comment by AntonyCilleros** [comment]
I have the same issue with jojo's bizarre adventure for downloading the season 2 in vf

**Comment by DCCXX** [comment]
Same problem with  ["Dropkick on My Devil!" (CR)]( https://www.crunchyroll.com/series/G62487M9Y/dropkick-on-my-devil). Named episodes are from season 'X', while the 'Untitled' ones are from season 'Dash'.

<details><summary>archive</summary>
<p>

`~/crunchy-cli/crunchy-cli archive -l all -r best -m auto -o "S{season_number}E{episode_number} - {title}.mkv" https://www.crunchyroll.com/series/G62487M9Y/dropkick-on-my-devil`

<details><summary>audio</summary>
<p>

↓ ar-ME has no matching episodes
↓ ar-SA has no matching episodes
↓ de-DE has no matching episodes
↓ en-US has no matching episodes
↓ es-419 has no matching episodes
↓ es-ES has no matching episodes
↓ es-LA has 12 less episodes than existing in japanese (24)
↓ fr-FR has no matching episodes
↓ it-IT has no matching episodes
↓ pt-BR has no matching episodes
↓ pt-PT has no matching episodes
↓ ru-RU has no matching episodes
↓ zh-CN has no matching episodes
↳ Parsed url 1

</p>
</details>

➞ Dropkick on My Devil! Season 1
➞ 	1. Armageddon Karuta X » 1920x1080px, 23.97 FPS (S01E01)
➞ 	2. All the Pills Are Hard Candies » 1920x1080px, 23.97 FPS (S01E02)
➞ 	3. Untitled » 1920x1080px, 23.97 FPS (S01E03)
➞ 	4. Untitled » 1920x1080px, 23.97 FPS (S01E04)
➞ 	5. To Love and Be Loved by Thirty Million » 1920x1080px, 23.97 FPS (S01E05)
➞ 	6. Gilding Kamuy: Kushiro » 1920x1080px, 23.97 FPS (S01E06)
➞ 	7. Untitled » 1920x1080px, 23.97 FPS (S01E07)
➞ 	8. Riding a Dolphin Into Chaos » 1920x1080px, 23.97 FPS (S01E08)
➞ 	9. Untitled » 1920x1080px, 23.97 FPS (S01E09)
➞ 	10. Ask the Sky! My Name Is Jashin-chan! » 1920x1080px, 23.97 FPS (S01E10)
➞ 	11. Untitled » 1920x1080px, 23.97 FPS (S01E11)
➞ 	12. Forever Dropkick » 1920x1080px, 23.97 FPS (S01E12)

</p>
</details>

<details><summary>download</summary>
<p>

`~/crunchy-cli/crunchy-cli download -a de-DE -s de-DE -r best -o "S{season_number}E{episode_number} - {title}.ts" https://www.crunchyroll.com/de/series/G62487M9Y/dropkick-on-my-devil` 

<details><summary>audio</summary>
<p>

↓ Untitled has no de-DE audio, using ja-JP as fallback
↓ Armageddon Karuta X has no de-DE audio, using ja-JP as fallback
↓ All the Pills Are Hard Candies has no de-DE audio, using ja-JP as fallback
↓ Untitled has no de-DE audio, using ja-JP as fallback
↓ Untitled has no de-DE audio, using ja-JP as fallback
↓ The Deadly Party Whistle has no de-DE audio, using ja-JP as fallback
↓ Untitled has no de-DE audio, using ja-JP as fallback
↓ How to Have a Wicked Time in Jinbocho has no de-DE audio, using ja-JP as fallback
↓ Untitled has no de-DE audio, using ja-JP as fallback
↓ To Love and Be Loved by Thirty Million has no de-DE audio, using ja-JP as fallback
↓ ... and 14 more
↳ Parsed url 1

</p>
</details>

➞ Dropkick on My Devil! Season 1
➞ 	1. Untitled » 1920x1080px, 23.97 FPS (S01E01)
➞ 	2. Armageddon Karuta X » 1920x1080px, 23.97 FPS (S01E01)
➞ 	3. All the Pills Are Hard Candies » 1920x1080px, 23.97 FPS (S01E02)
➞ 	4. Untitled » 1920x1080px, 23.97 FPS (S01E02)
➞ 	5. Untitled » 1920x1080px, 23.97 FPS (S01E03)
➞ 	6. The Deadly Party Whistle » 1920x1080px, 23.97 FPS (S01E03)
➞ 	7. Untitled » 1920x1080px, 23.97 FPS (S01E04)
➞ 	8. How to Have a Wicked Time in Jinbocho » 1920x1080px, 23.97 FPS (S01E04)
➞ 	9. Untitled » 1920x1080px, 23.97 FPS (S01E05)
➞ 	10. To Love and Be Loved by Thirty Million » 1920x1080px, 23.97 FPS (S01E05)
➞ 	11. Untitled » 1920x1080px, 23.97 FPS (S01E06)
➞ 	12. Gilding Kamuy: Kushiro » 1920x1080px, 23.97 FPS (S01E06)
➞ 	13. The Shape of a Smile: What I Found in Obihiro » 1920x1080px, 23.97 FPS (S01E07)
➞ 	14. Untitled » 1920x1080px, 23.97 FPS (S01E07)
➞ 	15. Riding a Dolphin Into Chaos » 1920x1080px, 23.97 FPS (S01E08)
➞ 	16. Untitled » 1920x1080px, 23.97 FPS (S01E08)
➞ 	17. Lavender-Colored Eyes Misting Over in Furano » 1920x1080px, 23.97 FPS (S01E09)
➞ 	18. Untitled » 1920x1080px, 23.97 FPS (S01E09)
➞ 	19. Ask the Sky! My Name Is Jashin-chan! » 1920x1080px, 23.97 FPS (S01E10)
➞ 	20. Untitled » 1920x1080px, 23.97 FPS (S01E10)
➞ 	21. Untitled » 1920x1080px, 23.97 FPS (S01E11)
➞ 	22. The Jinbocho Blood Donation Center » 1920x1080px, 23.97 FPS (S01E11)
➞ 	23. Chapter Chitose » 1920x1080px, 23.97 FPS (S01E12)
➞ 	24. Forever Dropkick » 1920x1080px, 23.97 FPS (S01E12)

</p>
</details>

Danke im Voraus. :3
