### ISSUE TITLE
crunchy info and downloads with www... failed 

### ISSUE THREAD

**Issue by LordBex** [crunchy-labs/crunchy-cli#58]
Der crunchy info Befehl funktioniert nicht mehr liegt vermutlich daran das crunchyroll die beta beendet hat
Die 'Beta-Version' ist nun ganz normal unter https://www.crunchyroll.com/de/ aufzufinden.

```
$ crunchy info
➞ An error occurred: error for endpoint https://www.crunchyroll.com/accounts/v1/me (403): invalid json response: invalid character '<' looking for beginning of value
```

Auch downloads welche mit www anstelle von beta ausgeführt werden brechen ab
```
[err] An error occurred: failed to get episodes: invalid url https://www.crunchyroll.com/de/series/G0XHWM5GQ/the-human-crazy-university
```
tausche ich das www hingegen mit beta aus funktioniert der download normal 

liegt wahrscheinlich daran das der parser nicht damit umgehen kann das unter www nun die beta Seite ist

**Comment by pratyushpati11** [comment]
That's cause beta.crunchyroll doesn't exist anymore.It's again www.crunchyroll.It's need a re write again

**Comment by ByteDream** [comment]
Closing in favor of #59 (has some more details in english)
