### ISSUE TITLE
Problem with Spaces in Folder- and Filename?

### ISSUE THREAD

**Issue by HannesMrg** [crunchy-labs/crunchy-cli#62]
I am using the newest Version on Windows and specify an Output Folder and Name with **Spaces** in it. Without Spaces it works.

When i run(cmd/powershell): 
```
.\crunchy.exe archive -l de-DE -l ja-JP -r best -d "F:\Anime\{series_name}\{season_number} {season_name}\" -o "S{season_number}E{episode_number} {title}.mkv" https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece[S1E1]
```

It Results in (notice the {title}.mkv which shouldnt be there):
```
=> Failed to parse url 1
=> An error occurred: failed to get episodes: invalid url {title}.mkv https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece
```

I have also tried escaping the spaces with `^` and ` and enclosing Paths with double and Single Quotation Marks.
Is this a Bug, or does my linux brain just not understand how to use the Windows Shell?

**Comment by IchBinLeoon** [comment]
Removing the `\` at the end of the directory path should fix the issue. Otherwise, you can also use `/` instead of `\`:
```
-d "F:/Anime/{series_name}/{season_number} {season_name}/"
```
A trailing `/` makes no difference in this case.
