### ISSUE TITLE
Subtitle size/styling does not match Crunchyroll.

### ISSUE THREAD

**Issue by ohitstom** [crunchy-labs/crunchy-cli#66]
Subtitles are too small, lack shadow, and have a thinner outline.

**Screenshots**
![Screenshot_20221031-030943.png](https://user-images.githubusercontent.com/22730962/198924731-b12f1651-465f-47de-95a0-beb1fd3a9a6c.png)
![Screenshot_20221031-031851.png](https://user-images.githubusercontent.com/22730962/198924751-f5c1d398-34e7-4486-ba67-dce4df1dd6a3.png)

The second image is Crunchyroll.

**Client (please complete the following information):**
 - OS: Windows
 - Version Latest

**Additional context**
This needs fixing asap please, also an option to change the font would be awesome. I personally really like Roboto.

**Comment by ByteDream** [comment]
Which command are you using to download the episode?

**Comment by ohitstom** [comment]
> Which command are you using to download the episode?

```
crunchy-v2.3.5_windows.exe archive https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia -d "D:\Main Personal\Torrents\Anime\Batch\Boku no Hero Academia" -o "{title} S{season_number}E{episode_number}.mkv"```

**Comment by ByteDream** [comment]
This is probably mostly up to your video player. If I play the videos in two different players (vlc & haruna) the subtitles are shown differently (they're also also in german bc I can only download them in german :/)

vlc
![image](https://user-images.githubusercontent.com/63594396/199067107-3632a19b-d517-4793-ae2f-22754b6c614f.png)

haruna
![image](https://user-images.githubusercontent.com/63594396/199067153-e032b8ea-e9f8-4730-b6a8-61d2232ffe35.png)

crunchyroll.com
![image](https://user-images.githubusercontent.com/63594396/199067219-1c7eaa08-eea1-4c29-8c9d-a1878fd41216.png)

**Comment by ohitstom** [comment]
This is definitely not an issue with my video player I tried it on multiple players, this issue is only evident on mobile. Please check that.

**Comment by Askadelion** [comment]
i also use the german version and i use the MPV and on the APPLE TV PLEX it is a resize error some players compensate it by themselves but in aegisub ass there is a flag that fixes it called "ScaledBorderAndShadow" this is missing in the ass download. If it is set it looks the same in almost all players.

**Comment by Askadelion** [comment]
for testing you can use aegisub set the subtitle size to 640x360 and open it in aegisub without resample then you will have the same effect

**Comment by ohitstom** [comment]
> Do you have another example where this is the case?
> As said I can't exactly reproduce bc I haven't access to your subtitle language on crunchy

I've only ever experienced it using this cli, it's the same across all videos I've downloaded with it.

Subplease which also rip from Crunchyroll don't have this issue and play at the correct font size and border width on mobile on multiple media sources.

Do you use libass at all in the cli?
ScaledBorderAndShadow is what fixed it for the guy on discord.

Also please try the same sources on mobile with vlc OR mpv they both have the same output of a tiny font with little to no border.

**Comment by Askadelion** [comment]
![grafik](https://user-images.githubusercontent.com/41443013/199069072-1d4084b1-c70b-4d76-9b76-c41853fcf8fc.png)
![grafik](https://user-images.githubusercontent.com/41443013/199069333-2e11f7ad-b889-45a1-a51c-ab1a3388da94.png)
![grafik](https://user-images.githubusercontent.com/41443013/199069419-2897754a-4f3c-40b4-aa01-07a06c847a9f.png)

**Comment by ByteDream** [comment]
> Do you use libass at all in the cli?

Nope, first time that I've heard from such issues.

**Comment by Askadelion** [comment]
> Nope, first time that I've heard from such issues.

most ignore it

**Comment by ByteDream** [comment]
`ScaledBorderAndShadows: yes` for `archive` was added in [v2.3.6](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v2.3.6).
