### ISSUE TITLE
Add ability to have an archive file like yt-dlp

### ISSUE THREAD

**Issue by BlastBolt5** [crunchy-labs/crunchy-cli#67]
Would love to have just check a series for new episodes but running archive, so if no new episodes are found it'll just exit or only download new ones

**Comment by ByteDream** [comment]
Can be done. I'll set it as milestone for the next major release since this can be relatively easy done by hand

**Comment by BlastBolt5** [comment]
ok sweet thank you, gonna have to parse the rss feed for anime updates till then

**Comment by BlastBolt5** [comment]
I didn't know if i should just add this here but would you also be able to make it so there would be a command that instead of downloading it would just list out the url's for the different episodes, would make it useful for scripting or something

**Comment by ByteDream** [comment]
I'll close this issue as it is not really a goal of the downloader to directly have such a feature built in. It's rather a feature which is provided via a script (like parsing the rss feed, as you already doing). The search command (#20) may provide a functionality to get all episodes / seasons of a series which then can be used as a alternative to the rss feed parsing.

 > I didn't know if i should just add this here but would you also be able to make it so there would be a command that instead of downloading it would just list out the url's for the different episodes, would make it useful for scripting or something

This would/could be a feature of a search command (#20).
