### ISSUE TITLE
archive only one audio track

### ISSUE THREAD

**Issue by 0xB00B** [crunchy-labs/crunchy-cli#68]
How can I do this ?

**Comment by ByteDream** [comment]
Was possible in versions pre 2 (which do not work anymore). I removed it because I didn't saw any use case for it. It can be re-added in the next major version.
Until then you have to archive the videos and extract the subtitles.

**Comment by 0xB00B** [comment]
nvm, archive option is what I needed.

Btw, how do I set the video codec to av1 in archive mode?

**Comment by ByteDream** [comment]
Currently you can't. This can be added with #65 in mind too. I see how I'll implement it, probably a flag to manually set ffmpeg optiions.
