### ISSUE TITLE
[Request] Add option to pipe download to stdout

### ISSUE THREAD

**Issue by Rainyan** [crunchy-labs/crunchy-cli#69]
**Describe the bug**

Feature request: Add option to stream file into stdout pipe by specifying `--output -` without downloading the episode to disk.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy download -o - https://www.crunchyroll.com/watch/GK9U3JDKN/a-bolt-from-the-blue |mpv -
```

**Expected behavior**
Crunchy pipes the media to stdout, and video player then displays the media by reading it from `-`

**What actually happens**
Command prompt displays `[file] Reading from stdin...` but nothing happens.

**Client (please complete the following information):**
 - OS: Windows 10
 - Version crunchy-cli version 2.3.6

**Additional context**

This is a feature in youtube-dl/yt-dlp whereby you can specify:

`yt-dlp -o - https://some.media.url |my-video-player -` to pipe the media into your media player directly.

**Comment by ByteDream** [comment]
The download process is currently not designed to support this.
To maximize performance it's using a concurrent worker model to download videos. The disadvantage of this model is that the download is not linear but rather "random" (i'm to lazy describe the download process deeper). So until not all segments (= tiny chunks of video data, crunchy stores their videos this way) are downloaded there might be the chance that in the middle of your video some seconds of video data are simply missing. To prevent this, crunchy-cli always waits until the full video is downloaded to then process it further. This download model has also the side effect that it caches each segment on disk (in the temporary directory provided by your OS) so the video file is one way or another already on your disk. 

The next major version will use a queue based download system where the download is linear and therefore can be piped to stdout while still downloading.

**Comment by ByteDream** [comment]
Support for this was added in [v3.0.0-dev.1](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.1)
