### ISSUE TITLE
[Question] Subtitle/Audio Only

### ISSUE THREAD

**Issue by YMrPro** [crunchy-labs/crunchy-cli#70]
Hello There,
Is there a way to download Subtitle only or Audio only without needing to download the full episode and extract them manually?

**Comment by ByteDream** [comment]
Subtitle only is not possible, but can / will be added in the next major version.
Only audio is also not possible because Crunchyroll stores their videos with audio and video merged so if you'd want only audio you must extract it from the whole video

**Comment by YMrPro** [comment]
Ok, TYSM

**Comment by crackerbad** [comment]
crunchyroll has the audio separately, with yt-dlp you can download only the audio.
You need to add this argument `--extractor-args crunchyrollbeta:format=download_dash` and then you will see the audio only options.

![D20SLA6 1](https://user-images.githubusercontent.com/14244856/202066801-635cb994-8602-4db7-88c1-c2f999f5d173.png)

**Comment by ByteDream** [comment]
> crunchyroll has the audio separately, with yt-dlp you can download only the audio. You need to add this argument `--extractor-args crunchyrollbeta:format=adaptive_dash` and then you will see the video and audio only options.
> 
> ![github](https://user-images.githubusercontent.com/14244856/202067579-348efa40-454e-424c-8478-f7e48f7174d0.png)

Thanks for the comment! I haven't had time to look at it yet, but I'm sitting on it now.
