### ISSUE TITLE
EOF Error

### ISSUE THREAD

**Issue by KTtL** [crunchy-labs/crunchy-cli#71]
**Describe the bug**
When downloading a series, I receive the following error at a random point in time. (Usually halfway through downloading episode three or four of a series)

I get the following error: ```An error occurred: error while downloading: unexpected EOF```

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy archive -l en-US -l ja-JP -s en-US -d "documents" -o "S{season_number}E{episode_number} {title}.mkv" https://www.crunchyroll.com/series/GEXH3WGGV/otherside-picnice
```

**Expected behavior**
Expected to download the complete 12 episode series with English and Japanese Audio as well as English Subtitles.

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows
 - Version 2.3.6

**Additional context**
No issues until a few hours ago. Have tried reinstalling the program and restarting computer. Happens with any series/film.

**Comment by ByteDream** [comment]
This might be a temporary Crunchyroll issue. Does it still appear?
If so, can you retry with the latest dev release ([v3.0.0-dev.1](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.1)) and see if it still occurs with this version?

**Comment by KTtL** [comment]
It seems to be working fine now (still version 2.3.6). Sorry for being so quick to post an issue and thank you!
