### ISSUE TITLE
Windows failed to connect to the server

### ISSUE THREAD

**Issue by ByteDream** [crunchy-labs/crunchy-cli#74]
**Describe the bug**
Failed to connect to the server

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy login --credentials "user:password"
```

**Expected behavior**
Working normal (just like on linux)

**Screenshots**
![image](https://user-images.githubusercontent.com/63594396/204375700-bc16e5c4-96f0-476d-942c-e818eb633a47.png)

**Client (please complete the following information):**
 - OS: Windows
 - Version v3.0.0-dev.1

**Additional context**
This error occurs on win10. crunchy-cli requires tls1.3 which is currently only supported on win11
https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support. Furthermore I can't say that it works on win11 (I have no testing machine atm) since the SSL library Windows uses not work too.
On Linux and Mac which both uses OpenSSL this error does not occur. 

TLS1.3 is required to bypass the bot check Crunchyroll has installed.

**Comment by DxsSucuk** [comment]
Why not fallback to TLSv1.2?

**Comment by ByteDream** [comment]
TLS1.3 is _required_ to bypass the cloudflare bot check Crunchyroll as activated

**Comment by DxsSucuk** [comment]
Wouldn't that be better overall to switch to a library supporting TLS1.3 to keep it platform independent?

**Comment by ByteDream** [comment]
I've tried this with [rustls](https://github.com/rustls/rustls) at the beginning but hadn't any success. I guess the main difference between rustls and OpenSSL is the ClientHello message, sent at first when a new https connection is established. rustls sends a different ClientHello body than OpenSSL and cannot be tweaked so deeply that it clones the OpenSSL body / behavior.
I currently try to build the binary with OpenSSL support on Windows, but that's a bit hard because building C libraries on Windows is just so different and much weirder than on Linux.

**Comment by ByteDream** [comment]
Fixed in [v3.0.0-dev.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.2)
