### ISSUE TITLE
Changing output results in "a unexpected error occurred: program not found"

### ISSUE THREAD

**Issue by ionstorm66** [crunchy-labs/crunchy-cli#77]
**Describe the bug**
Changing output results in "a unexpected error occurred: program not found". Removing the output argument allows program to work.

**To Reproduce**
Steps / command to reproduce the behavior:
```
.\crunchy.exe download -o "{series_name} - S{season_number}E{episode_number} - {title}.ts" -s en-US https://www.crunchyroll.com/watch/GK9U3JEE7/from-kyoto
```

It even shows the correct name in the console

```
PS E:\tmp\crunchy> .\crunchy.exe download -o "{series_name} - S{season_number}E{episode_number} - {title}.ts" -s en-US https://www.crunchyroll.com/watch/GK9U3JEE7/from-kyoto
:: √ Logging in
:: √ Parsed url 1
:: √ Loaded series information for url 1
:: Chainsaw Man Season 1 (Chainsaw Man)
::      1. FROM KYOTO » 1920x1080px, 23.97 FPS (S01E09)
:: Downloading FROM KYOTO to 'Chainsaw Man - S1E9 - FROM KYOTO.ts'
::      Episode: S01E09
::      Audio: ja-JP
::      Subtitles: en-US
::      Resolution: 1920x1080
::      FPS: 23.97
:: a unexpected error occurred: program not found
PS E:\tmp\crunchy>
```

**Expected behavior**
Should download with the correct name.

**Client (please complete the following information):**
 - OS: Windows
 - Version 3.0.0

**Comment by ByteDream** [comment]
Does this still occur in [v3.0.0-dev.3](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.3)?

**Comment by adracea** [comment]
I believe the issue might have been related to a combination of missing ffmpeg binaries accessible and the fact that when changing the output string from default we were automatically triggering ffmpeg usage. As @ByteDream mentioned, I believe this to be fixed in the `dev.3` release.

**Comment by ByteDream** [comment]
Closed as fixed? (as no further information got provided)
