### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Cazka** [crunchy-labs/crunchy-cli#79]
https://github.com/crunchy-labs/crunchy-cli/blob/578e5ea5b7cc927147e77b983fa54bcb5c4daa79/crunchy-cli-core/src/lib.rs#LL210-L212

the option `--etp_rt` doesnt exist, it should be `--etp-rt`

**Comment by ByteDream** [comment]
Already fixed in b814529, will be available in the next dev release.

https://github.com/crunchy-labs/crunchy-cli/blob/b814529aa21b455686bb6c34d10caa4e95a34cd6/crunchy-cli-core/src/lib.rs#L216-L218
