### ISSUE TITLE
Crunchyroll is publishing different season under the same pair season_number/episode_number

### ISSUE THREAD

**Issue by aniplayIt** [crunchy-labs/crunchy-cli#82]
**Describe the bug**
I just found that on Demon Slayer crunchyroll decided to put the 
S2 - Demon Slayer: Kimetsu no Yaiba Mugen Train Arc that according to the filter I should be able to download with [S2E1] ... [S2E7]
and the
S2 - Demon Slayer: Kimetsu no Yaiba Entertainment District Arc that according to the filter I should be able to download with [S2E1] ... [S2E11]

However using the filter trying to download the S1E1 I always download both episodes. How can I choose which one to download?

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy download --audio ja-JP -s it-IT -o episode.mp4 -r 1080p https://www.crunchyroll.com/it/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba\[S2E1\]
➞ Parsed url 1  
➞ Demon Slayer: Kimetsu no Yaiba Season 2
➞ 	1. Il Pilastro del Suono Uzui Tengen » 1920x1080px, 23.97 FPS (S02E01)
➞ 	2. Il Pilastro delle Fiamme Rengoku Kyojuro » 1920x1080px, 23.97 FPS (S02E01)

➞ Downloading episode `Il Pilastro del Suono Uzui Tengen` to `episode.mp4`
➞ 	Episode: S02E01
➞ 	Audio: ja-JP
➞ 	Subtitle: 
➞ 	Resolution: 1920x1080px
➞ 	FPS: 23.97

```

**Expected behavior**
A way to choose which episode download from args

**Screenshots**
https://ibb.co/qkDC0BF S2 - Demon Slayer: Kimetsu no Yaiba Mugen Train Arc
https://ibb.co/nQpGbXg S2 - Demon Slayer: Kimetsu no Yaiba Entertainment District Arc

**Client (please complete the following information):**
 - OS: MacOS
 - Version 2.3.6

**Additional context**

**Comment by ByteDream** [comment]
Already mentioned in #55. The only way to download the single episodes with this weird season naming is to provide the direct episode link. In your case this would be `https://www.crunchyroll.com/it/watch/G7PU4QMZ3/flame-hashira-kyojuro-rengoku` (Mugen Train) and `https://www.crunchyroll.com/it/watch/GN7UDQ2EW/sound-hashira-tengen-uzui` (Entertainment District). I'm trying to find a good way to filter these special cases, but I haven't found a solution yet.
I'll leave this open as the title is more meaningful than the one at #55.

**Comment by aniplayIt** [comment]
> Already mentioned in #55. The only way to download the single episodes with this weird season naming is to provide the direct episode link. In your case this would be `https://www.crunchyroll.com/it/watch/G7PU4QMZ3/flame-hashira-kyojuro-rengoku` (Mugen Train) and `https://www.crunchyroll.com/it/watch/GN7UDQ2EW/sound-hashira-tengen-uzui` (Entertainment District). I'm trying to find a good way to filter these special cases, but I haven't found a solution yet. I'll leave this open as the title is more meaningful than the one at #55.

I tried downloading directly with the link but:
`An error occurred: downloading episodes by url and specifying a language is no longer supported (thx crunchyroll). use the series url instead and filter after the given episode (https://github.com/crunchy-labs/crunchy-cli/wiki/Cli#filter)`

**Comment by ByteDream** [comment]
Ahh yes this was a thing in this version(s), forgot about it. In [v3.0.0-dev.3](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.3) with the corresponding binary for your system and the command `./crunchy --credentials "user:password" download -s it-IT -o episode.mp4 -r best <url>` should work to download single episodes. The url _must_ point to the episode which has the audio you want (in your case the japanese one).
So it would be `https://www.crunchyroll.com/it/watch/G2XU057GN/flame-hashira-kyojuro-rengoku` (Mugen Train) and`https://www.crunchyroll.com/it/watch/GJWU2XQDD/sound-hashira-tengen-uzui` (Entertainment District)

**Comment by aniplayIt** [comment]
Ok I'll have a look in the v3 version but will wait for a stable release

**Comment by thedaa** [comment]
> Already mentioned in #55. The only way to download the single episodes with this weird season naming is to provide the direct episode link. In your case this would be `https://www.crunchyroll.com/it/watch/G7PU4QMZ3/flame-hashira-kyojuro-rengoku` (Mugen Train) and `https://www.crunchyroll.com/it/watch/GN7UDQ2EW/sound-hashira-tengen-uzui` (Entertainment District). I'm trying to find a good way to filter these special cases, but I haven't found a solution yet. I'll leave this open as the title is more meaningful than the one at #55.

Dunno if you already found a solution but each season/dub has its own id
