### ISSUE TITLE
Need to help with install on Mac M1

### ISSUE THREAD

**Issue by Raiznb** [crunchy-labs/crunchy-cli#85]
I can't figure out how to install .darwin on mac with m1, please help me

**Comment by Raiznb** [comment]
I tried to build it directly with cargo but when i start crunchy-cli i get these
<img width="1512" alt="crunchy-cli" src="https://user-images.githubusercontent.com/108086166/208417205-c2a6bf42-dd2c-41c7-b5ed-10e5668a537a.png">
and when i trying to execute crunchy command
zsh: command not found: crunchy

**Comment by adracea** [comment]
hey, can you try the artifact for m1darwin : `https://github.com/crunchy-labs/crunchy-cli/actions/runs/3731017733` ?

**Comment by adracea** [comment]
> I tried to build it directly with cargo but when i start crunchy-cli i get these <img alt="crunchy-cli" width="1512" src="https://user-images.githubusercontent.com/108086166/208417205-c2a6bf42-dd2c-41c7-b5ed-10e5668a537a.png"> and when i trying to execute crunchy command zsh: command not found: crunchy

This also looks like it's actually working ? The way you run it is with `./crunchy-cli` or add it to your `PATH` and then `crunchy-cli` should work without the `./` on the binary.

**Comment by Raiznb** [comment]
> > I tried to build it directly with cargo but when i start crunchy-cli i get these <img alt="crunchy-cli" width="1512" src="https://user-images.githubusercontent.com/108086166/208417205-c2a6bf42-dd2c-41c7-b5ed-10e5668a537a.png"> and when i trying to execute crunchy command zsh: command not found: crunchy
> 
> This also looks like it's actually working ? The way you run it is with `./crunchy-cli` or add it to your `PATH` and then `crunchy-cli` should work without the `./` on the binary.

i just load cli to terminal, i cannot use any of these command and options

**Comment by adracea** [comment]
Hey can you try the following:
1. open up the terminal(on its own)
2. cd to the CLI's folder/download location
3. use ./crunchy-cli to do any of the various commands.

The problem you seem to be having is that you're basically double-clicking on the binary so it opens it up, boots the cli with no command and then does the `exit` which closes the terminal.

**Comment by Raiznb** [comment]
> Hey can you try the following:
> 
>     1. open up the terminal(on its own)
> 
>     2. cd to the CLI's folder/download location
> 
>     3. use ./crunchy-cli to do any of the various commands.
> 
> 
> The problem you seem to be having is that you're basically double-clicking on the binary so it opens it up, boots the cli with no command and then does the `exit` which closes the terminal.
<img width="1512" alt="crunchy" src="https://user-images.githubusercontent.com/108086166/208443210-58865fed-e19a-431b-b14b-3689bc24daaa.png">
(

**Comment by Raiznb** [comment]
think i will go to another option, thanks for help (

**Comment by Raiznb** [comment]
.

**Comment by IchBinLeoon** [comment]
> > Hey can you try the following:
> > ```
> > 1. open up the terminal(on its own)
> > 
> > 2. cd to the CLI's folder/download location
> > 
> > 3. use ./crunchy-cli to do any of the various commands.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The problem you seem to be having is that you're basically double-clicking on the binary so it opens it up, boots the cli with no command and then does the `exit` which closes the terminal.
> 
> <img alt="crunchy" width="1512" src="https://user-images.githubusercontent.com/108086166/208443210-58865fed-e19a-431b-b14b-3689bc24daaa.png">
> (

You need to execute `./crunchy-cli` in the directory with the binary. 
In your case, that would be `/Users/pyx/crunchy-cli/target/release/`.
