### ISSUE TITLE
-d/--directory flag not working using archive

### ISSUE THREAD

**Issue by julius1504** [crunchy-labs/crunchy-cli#91]
OS: Windows
Version: 3.0.0-dev.4

Working command (no directory specified):
`crunchy archive --ffmpeg-preset nvidia --ffmpeg-preset h265 -l de-DE -l ja-JP -r 1280x720 -o S{season_number}E{episode_number}-{title}-{resolution}-x265.mkv URL[S04]`

Failing command (with directory):
`crunchy archive --ffmpeg-preset nvidia --ffmpeg-preset h265 -l de-DE -l ja-JP -r 1280x720 -d D:\Crunchyroll\{series_name}\{season_number} -o S{season_number}E{episode_number}-{title}-{resolution}-x265.mkv URL[S04`]

Error given:
![Screenshot_1](https://user-images.githubusercontent.com/77297176/209563746-5c3237c7-6b8a-4071-b088-80257266c79c.png)

**Comment by adracea** [comment]
Hello, I'm not sure `-d` made it into the rust rewrite, but, specifying the path as part of the `-o` should work.

**Comment by julius1504** [comment]
> Hello, I'm not sure `-d` made it into the rust rewrite, but, specifying the path as part of the `-o` should work.

Thank you. Unfortunately, it didnt work.

using
`-o D:\cr-downloads\{series_name}\S{season_number}-{season_name}\S{season_number}E{episode_number}-{title}-{resolution}-x265.mkv`

returned an unexpected error with FFmpeg that doesnt come up when just using a file name plus
`D:\cr-downloads\{series_name}\S{season_number}-{season_name}\S5E1-HLB-1920x1080-x265.mkv: No such file or directory`

**Comment by adracea** [comment]
Yes, you are correct. A folder would not get created in this way to reflect the current example you give. This would be a feature/enhancement.

You can though mention already existing folders.

**Comment by julius1504** [comment]
The folder D:\Crunchyroll does exist, but not the series and season folders. Creating these myself would take away any use for the automation im trying to achive.

Still, thanks for your help!

**Comment by ByteDream** [comment]
> Hello, I'm not sure `-d` made it into the rust rewrite, but, specifying the path as part of the `-o` should work.

That's correct, the functionality of `-d` could be archived with `-o` as well (_in theory_)



> Yes, you are correct. A folder would not get created in this way to reflect the current example you give. This would be a feature/enhancement.
> 
> You can though mention already existing folders.

Yep exactly, it does not create folders if they don't exists.
